containers/storage

drivers/overlay/overlay.go
types/options.go

This prevents issues inside podman where the `mount_program` is detected and subsequently erased, e.g. via the usage of the `--root` option.
This fixes https://github.com/containers/podman/issues/13459
This fixes https://github.com/containers/podman/issues/13458

Move the mount_program autodetection into the graphdriver Init()

---

pkg/unshare/unshare_linux.go

Pass along SIGHUP, SIGINT, and SIGTERM if the parent receives them while the child process is running.  Set SIGKILL as the child's parent-death signal so that, if we exit for some reason before the child does, it will be stopped.  This addresses part of https://github.com/containers/buildah/issues/3544.

MaybeReexecUsingUserNamespace: handle SIGHUP/SIGINT/SIGTERM

---

pkg/idtools/idtools.go

The godoc for pkg/idtools.ToHost() mentions that it makes an exception when either of the IDs to be mapped is 0, but that special case was removed in #1057.

idtools: don't say ToHost() makes exceptions in its godoc when it doesn't

---

pkg/unshare/unshare_linux.go

A fairly common failure is newuidmap and newgidmap not being setuid and
setgid. If these commands fail, check the permissions on the binaries in
order to give the user better information on why they failed.

Check filecaps on newuidmap and newgidmap on failure

---

pkg/unshare/unshare_linux.go

Make IsSetID public so that Podman can use it

---

drivers/chown_unix.go
pkg/system/xattrs_linux.go
pkg/system/xattrs_unsupported.go

Signed-off-by: Robert Zaage <robert@zaage.it>

fix storage-chown-by-maps doesnt handle -EOVERFLOW on lgetxattr [Closes #1183]

---

containers.go
errors.go
images.go
images_test.go
layers.go
store.go
utils.go

Reverts containers/storage#1191
Backport was re-evaluated only for `release-1.23` buildah branch and backport for `release-1.19` buildah is no longer under consideration. So we must revert this.

Revert "[backport v1.24] Lock during store diff and add race-free `AddNames` and `RemoveNames` api."

---

pkg/archive/archive_linux.go
pkg/archive/archive_linux_test.go

Force the mode for whiteouts that have been converted from overlay format (produced by overlay native diff) to aufs format to 0x0, to match the permissions we assign to whiteouts we create when using naive diff.
Fixes #1195.

pkg/archive/overlayWhiteoutConverter.ConvertWrite(): force mode to 0

---

drivers/overlay/check.go
drivers/overlay/idmapped_utils.go
drivers/overlay/overlay.go

use idmapped mounts for the overlay lower layers when the kernel
supports them.
For each lower directory with ID=0...N-1, it creates a idmapped mount
at $GRAPHROOT/overlay/$LAYER/mapped/$ID.  The final overlay mount will
use these idmapped mounts instead of the original source directory.
The upperdir is not idmapped, so files are created with the same
IDs used by the user namespace.

overlay: use idmapped lower layers where supported

---

drivers/overlay/overlay.go
layers.go
tests/idmaps.bats

When we create a copy of an image's top layer that's intended to be identical to the top layer, except for having some set of ID mappings already applied to it, copy over the template layer's compressed and uncompressed digest and size information, compression information, tar-split data, and lists of used UIDs and GIDs, if we have them.
The lack of sizing information was forcing ImageSize() to regenerate the diffs to determine the size of the mapped layers, which shouldn't have been necessary.
Teach the overlay DiffGetter to look for files in the diff directories of lower layers if we can't find them in the current layer, so that tar-split can retrieve content that we didn't have to pull up.
Fixes https://github.com/containers/podman/issues/13755.

Fully populate layer records for mapped image top layers

---

utils.go

... by actually using it, removing some duplication, and perhaps micro-optimizing some memory allocations.

Fix an unused line in applyNameOperation

---

store.go
tests/idmaps.bats

When deleting an image, always delete an image's mapped top layers, even ~if~ when the unmapped top layer is shared with other images and must therefore not be deleted.

DeleteImage(): always delete mapped top layers

---

layers.go

When we're creating a layer using another layer as a template, add the new layer's uncompressed and compressed digest to the maps we use to index layers using those digests.
When we forgot to do that, searching for a layer by either would still turn up the original template, so this didn't really break anything.
We also had a case in layerStore.PutAdditionalLayer() where we mistakenly mixed up the uncompressed and compressed digests when populating the by-uncompressed-digest map; fix that while we're in here.

layerStore.Put(): update digest-based indexes when creating from templates

---

Makefile
drivers/driver_freebsd.go
drivers/register/register_zfs.go
drivers/zfs/zfs.go
drivers/zfs/zfs_freebsd.go
drivers/zfs/zfs_linux.go
storage.conf-freebsd

This corrects some minor bit-rot in the zfs driver and adds a sample storage.conf

Fix FreeBSD support

---

drivers/overlay/overlay.go

In all call paths, the layerStore owning the driver is expected to be locked, so, so this seems redundant.
See also https://github.com/containers/storage/pull/1140#issuecomment-1101507419 .

Remove locker.Locker from drivers/overlay

---

drivers/overlay/overlay.go

When using link entry, in some situations the link prefix wasn't add
which cause mount of overlay to fail.
This causes failure to podman operation.
Close #1216

overlay driver: fix incorrect path of link dir

---

drivers/zfs/zfs_freebsd.go
pkg/mount/flags_freebsd.go
pkg/mount/mounter_freebsd.go

This uses MNT_FORCE as an approximation of Linux MNT_DETACH and passes through key/value options such as devfs' ruleset=N option to the kernel. Also, I removed the code which truncates the zfs mount point to work around a path name limit in obsolete versions of FreeBSD which was fixed in FreeBSD 12.

FreeBSD fixes for pkg/mount

---

drivers/chown_unix.go
drivers/graphtest/graphtest_unix.go
pkg/idtools/idtools.go
pkg/idtools/idtools_test.go

when chowning an image, fall back to the overflow ID when a UID or GID cannot be mapped to the target user namespace.
This ensures the chown driver works similar to what we do with idmapped mounts when it is supported for overlay.
It is needed for CRI-O to support user namespaces in Kubernetes since the Kubelet picks a static size for the user namespace and it might break some images using IDs outside the picked range.

chown: use overflow id as fallback when chowning

---

drivers/overlay/overlay.go

- <s>Use the `Driver.locker` lock when creating a layer in the overlay driver. I don’t know why that lock is necessary, but if it is necessary at all, it seems that it should be held on that code path. Alternatively, maybe that lock should be removed entirely?</s>
- Don't just add files to the layer’s directory; if we find anything pre-existing, remove that, including the symbolic link in `linkDir`, to ensure the layer is created in a known state.
Compare also **EDIT <s>#1133</s> #1139**.

(Alternative to 1148): Don't blindly reuse state from a previous layer when re-creating it

---

layers.go

This implements the suggestion in #1139, along with **EDIT partially** fixing #1147 ; as an alternative to #1140 .
Conceptually I like this much better than #1140, but it’s quite a bit more invasive, and potentially risky by invoking the layer removal code in previously-unreachable situations.
Marking as draft because it’s completely untested so far.

(Alternative to 1140): Record layers as incomplete before trying to create them

---

drivers/overlay/idmapped_utils.go

so use the simpler and more portable time.Sleep() version

overlay: unix.SYS_PAUSE is not defined on aarch64

---

pkg/chrootarchive/archive.go
pkg/chrootarchive/chroot_linux.go

do not attempt to load NSS modules at init() time but do it just
before creating the chroot environment.
Closes: https://github.com/containers/storage/issues/1227

pkg/chrootarchive: move NSS load to chrootarchive package

---

Makefile
pkg/mount/mounter_freebsd.go
pkg/mount/mounter_unsupported.go

Add freebsd to the local-cross build target

---

store.go
tests/idmaps.bats

do not attempt to create a layer using a TemplateLayer if the source
layer is in a different store, since the lookup for the source layer
would fail in the layers store.
The reproducer for the error:
Error: error creating container storage: error creating an ID-mapped copy of layer "4fc242d58285699eca05db3cc7c7122a2b8e014d9481f323bd9277baacfa0628": layer not known
Closes: https://github.com/containers/storage/issues/1232

store: skip template copy with layer in different store

---

drivers/overlay/overlay.go

do not store the result of the check when running with euid != 0.  The
check must happen and its result stored only once the process is
re-executed in its user namespace and runs with euid == 0.
It doesn't make any real difference at the moment since the  kernel
feature is going to be supported only for root in the initial user
namespace.

overlay: do not check for idmapped mounts if euid!=0

---

pkg/chunked/storage_linux.go

after the missing parts are merged, it is necessary to recalculate the chunks to ask to the server.

chunked: recalculate correctly the chunks to request

---

pkg/system/meminfo_freebsd.go
pkg/system/meminfo_unsupported.go

Implement ReadMemInfo on FreeBSD

---

pkg/unshare/unshare.c
pkg/unshare/unshare.go
pkg/unshare/unshare_cgo.go
pkg/unshare/unshare_freebsd.c
pkg/unshare/unshare_freebsd.go
pkg/unshare/unshare_linux.go
pkg/unshare/unshare_unsupported.go
pkg/unshare/unshare_unsupported_cgo.go

This does not really 'unshare' anything but does implement the setsid,
setpgrp and ctty options as well as the pipe-based signalling protocol
with the parent process which made it slightly easier to port buildah's
chroot isolation mechanism.

Limited support for pkg/unshare on FreeBSD

---

store.go
store_test.go
types/options.go

Also add interfaces to allow callers to see the pull options.
While experimenting with pushing and pulling with zstd, I found
that storage pulloptions were not being used in rootless mode.

PullOptions should work for rootless users also

---

types/options.go
types/options_test.go

`ReloadConfigurationFile()` does not return an error but `fmt.Print`s them which is quite ugly but I didn't touch that.
@rhatdan @giuseppe PTAL

style clean up in storage.conf code

---

drivers/chown_unix.go
pkg/system/xattrs_linux.go
pkg/system/xattrs_unsupported.go

Backport https://github.com/containers/storage/pull/1190/files to
addresses https://bugzilla.redhat.com/show_bug.cgi?id=2072452 which
is required for a priority customer fix.
Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

[release-1.38] Backport EOVERFLOW on lgetxattr

---

.cirrus.yml

bump fedora release to 36
bump fedora prior to 35
bump ubuntu release to 22.04
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

Cirrus: use latest fedora and ubuntu releases

---

docs/containers-storage.conf.5.md
storage.conf

[CI:DOCS] Document the pull_options

---

docs/containers-storage.conf.5.md
pkg/chunked/storage_linux.go
storage.conf

drop host deduplication by just looking at the file path.  It could be
useful in very specific use cases, but it is too expensive for generic
images.  If the need arises, we first need to create an index of the
files that we can deduplicate so there is no need to calculate the
checksum on the fly.

chunked: drop host dedup feature

---

docs/containers-storage.conf.5.md

Fixes: https://github.com/containers/storage/issues/1259

Move skip_mount_home to overlay specific flag in man page

---

drivers/chown_unix.go
tests/idmaps.bats

If the inode was already encountered and chowned, use link(2) instead
of chown(2).
This is needed when the underlying storage (as it could be overlay
with index=off) breaks the hard link on copy up.
https://github.com/containers/storage/pull/1144 added the initial
check.
Closes: https://github.com/containers/storage/issues/1257

chown: use Link instead of Chown for dup inodes

---

drivers/driver_linux.go

when checking that a mount has a specific file system type, also
validate that it is different than its parent directory.
This helps when using virtiofs as the underlying file system since the
check used for fuse-overlayfs would fail since they both use FUSE.

drivers: enhance check for mount fs type

---

pkg/idtools/idtools_supported.go

We lost this feature when we moved to using libsubid for looking up
user additional ranges.
If the lookup using the username fails then attempt again using the
UID, since /etc/subuid and /etc/subgid allow that.
Closes: https://github.com/containers/storage/issues/1264

idtools: add lookup by UID with libsubid

---

drivers/driver_linux.go

when checking that a mount has a specific file system type, also
validate that it is on a different than its parent directory.
This helps when using virtiofs as the underlying file system since the
check used for fuse-overlayfs would fail since they both use FUSE.
(cherry picked from commit da09b934b6e019279b0489ace2e0194450f36a5b)

[release-1.24] drivers: enhance check for mount fs type

---

drivers/overlay/overlay.go

on newer kernels we use idmapped mounts for the overlayfs.
When running in a user namespace that doesn't include the root user
from the host, the linDir cannot be accessed since CAP_DAC_OVERRIDE
doesn't work with IDs that are not part of the mapping.
To avoid this problem, create the linkDir with permissions 0755.
Closes: https://github.com/containers/storage/issues/1270

overlay: create linkDir with mask 0755

---

drivers/driver_linux.go

When checking that a mountpoint is a specific file system type, also validate that it is on a different filesystem than its parent directory.
This helps when using virtiofs as the underlying file system for storage since the check used for fuse-overlayfs would previously fail since they both use FUSE.
Cherry-picked from https://github.com/containers/storage/pull/1261.

[release-1.40] drivers: enhance check for mount fs type

---

store.go
types/options.go

when the configuration file was explicitly specified, all the graph
drivers options are copied, not only the ones allowed for rootless.
Closes: https://github.com/containers/storage/issues/1278

options: copy all options on explicit config file

---

drivers/quota/projectquota.go

Use mknod() followed by rename() to create the "backingFsBlockDev" device, instead of unlink() followed by mknod(), to remove the window where the node won't exist if we're just going to end up replacing it with an identical device node.

drivers/quota.makeBackingFsDev(): use mknod+rename

---

pkg/chrootarchive/archive_unix.go

Only return errors when they exists

---

pkg/archive/diff.go

if the parent directory is missing when creating a directory or
extracting a file from the tarball, then create the missing parent
directories with mode 0755 instead of 0600 so that a container can run
with uid != 0.
Closes: https://github.com/containers/storage/issues/1288

diff: create missing layers dirs with 0755

---

go.mod
go.sum
vendor/modules.txt

* https://avd.aquasec.com/nvd/2022/cve-2022-29162/
* this is a HIGH severity CVE
This PR _only_ updates the github.com/opencontainers/runc package, and then runs
```
go mod tidy
go mod vendor
```
Please let me know if there's anything more I need to do for this PR. Thank you
Signed-off-by: Kira Boyle <kira@replicated.com>

update github.com/opencontainers/runc to 1.1.3 to resolve CVE-2022-29162

---

drivers/devmapper/device_setup.go

We missed that error check during the conversion, which is now fixed.

Fix missing error check in device mapper

---

drivers/devmapper/device_setup.go

The function readLVMConfig always returns an error.
Signed-off-by: Alice Frosi <afrosi@redhat.com>

fix return error in device mapper

---

images.go
pkg/archive/archive.go
pkg/chrootarchive/archive.go
pkg/system/meminfo_freebsd.go

There are a few places that look like we could end up passing a `nil` value to `fmt.Errorf()`'s "%w" specifier, and one where we were calling `Validate()` on a `Digest` a second time to wrap an error result instead of just reusing it.

Remove a couple of cases of possibly wrapping `nil` as errors

---

pkg/unshare/unshare_cgo.go
pkg/unshare/unshare_gccgo.go

This commit declare C init() function as static, since this is a constructor there is no need to export this symbol, avoiding errors like 'multiple definitions error' when linking the binary.
Fixes: #1304

pkg/unshare: declare init() as static

---

drivers/overlay/idmapped_utils.go

do not clone the source directory in recursive mode (the equivalent of
MS_BIND|MS_RECURSIVE) but use only a regular bind mount.  If
not recursive bind mount is used then the existing overlay mounts are
not replicated.  In this way a new idmapped mount won't need to map
the overlay mount as well, causing the mount_settattr(2) syscall to
fail with EINVAL since it is not possible to idmap an overlay mount
yet.
Closes: https://github.com/containers/storage/issues/1308

overlay: do not clone source recursively

---

pkg/unshare/unshare_linux.go

in addition to check the UID of the user that launched the command,
also check whether the process has CAP_SYS_ADMIN (in the same way as
podman/pkg/rootless does) and also check that the current user
namespace has all the IDs available.
Closes: https://github.com/containers/storage/issues/1311
After this change, podman/pkg/rootless can use the function directly
instead of defining another version with similar functionalities.

unshare: improve rootless detection

---

drivers/copy/copy_test.go
drivers/overlay/overlay_test.go
images_test.go
pkg/archive/archive_linux_test.go
pkg/archive/archive_test.go
pkg/archive/archive_unix_test.go
pkg/archive/archive_windows_test.go
pkg/archive/changes_posix_test.go
pkg/archive/changes_test.go
pkg/archive/copy_unix_test.go
pkg/archive/diff_test.go
pkg/archive/utils_test.go
pkg/chrootarchive/archive_test.go
pkg/chrootarchive/archive_unix_test.go
pkg/directory/directory_test.go
pkg/fileutils/fileutils_test.go
pkg/idtools/idtools_unix_test.go
pkg/ioutils/fswriters_test.go
pkg/mount/mounter_linux_test.go
pkg/system/chtimes_test.go
pkg/system/chtimes_unix_test.go
pkg/system/chtimes_windows_test.go
pkg/system/lstat_unix_test.go
pkg/system/rm_test.go
pkg/system/stat_unix_test.go
pkg/system/utimes_unix_test.go
store_test.go
types/utils_test.go

A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
require.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```

test: use `T.TempDir` to create temporary test directory

---

drivers/overlay/overlay.go

When we use a subprocess to mount a read-only layer, include the layer's own diff in the list of lowers, since it's not being used as an upper.  Fixes #640.

overlay: use the right lowers for read-only mounts via subprocess

---

drivers/chown.go

Don't pass the output of a subprocess to `fmt.Errorf()`, which will try to treat it as a format specifier.  Just use `errors.New()` to create an error using the text verbatim.
Fixes #1316.

Don't use subprocess output as a format specifier

---

layers.go

There was a race condition if a goroutine accessed to layerStore public
methods under RO lock and at the same time ReloadIfChanged was called.
In real life, it can occurr when there are two concurrent PlayKube
requests in Podman.
Signed-off-by: Mikhail Khachayants <tyler92@inbox.ru>

Fix data race between ReloadIfChanged and read-only usage of layerStore

---

drivers/overlay/check_116.go

Fixes: https://github.com/containers/storage/issues/1321

Don't fail on walking os of EOPNOTSUPP for Llistxatt

---

drivers/overlay/overlay.go

if a mount program is specified, change the content and the verbosity for the message printed.
Closes: https://github.com/containers/podman/issues/15698

overlay: change log message verbosity

---

layers.go

... to ensure that any changes after we start reading the data trigger a future reload.

Update layerspathModified before reading the contents

---

pkg/unshare/unshare_linux.go

per https://github.com/containers/storage/pull/1312#discussion_r966242314 .

Explain why a substring match is sufficient when reading uid_map

---

pkg/system/meminfo_freebsd.go

This wasn't picked up by the freebsd cross build because meminfo_freebsd.go relies on cgo.

ReadMemInfo: Add missing import of errors

---

pkg/lockfile/lockfile_unix.go

Fix one issue and a couple of nits in pkg/lockfile. Please see individual commits for details.

pkg/lockfile: nits

---

pkg/archive/archive_linux_test.go
pkg/archive/copy_unix_test.go

A recent PR merge added mid-sentence blank links to a few comments. Revert those changes and update adjacent comments to follow suit.

Comment fixups

---

drivers/overlay/check.go
drivers/overlay/overlay.go

Add missing punctuation to a couple of error messages, and include which mount options we tried to use when we complain about `mount()` failing.

Tweak a couple of error messages

---

pkg/lockfile/lockfile_unix.go

There's at least one Go platform where that is not true.
Making that assumption without any warning is just a trap for future readers.
Instead, just do the obviously correct thing, per the API documentation.
On macOS, this compiles to _literally exactly the same binary code_.
So, let the compiler be clever so that we don't have to.

Remove an undocumented assumption that O_RDONLY == 0

---

drivers/overlay/overlay.go

If we're going to complain about the booted kernel, include information about which kernel it is.

overlay: when we warn about the kernel, mention the version

---

containers.go
drivers/driver.go
store.go
userns.go
utils.go

Use constants for the names of flags that we set in `Flags` maps that we store in layer/image/container records, to make it easier to avoid possible breakages due to typos in the future.

Use defined constants for flag names

---

layers.go

When removing layers, try to remove layers before removing their parents, as the lower-level driver may enforce the dependency beyond what the higher-level logic does or knows.
Do this by sorting by creation time as an attempt at flattening the layer tree into an ordered list.  It won't be correct if a parent layer needed to be recreated, but it's more likely to be correct otherwise.

layers.Wipe(): try to remove layers before their parents

---

tests/tools/Makefile

We don't use ffjson any more, so don't try to build it.

tests/tools/Makefile: we don't use ffjson any more

---

tests/idmaps.bats

Don't try to test with a .imagestore option on btrfs, devicemapper, or zfs.

tests/idmaps.bats: only test .imagestore on overlay and vfs

---

pkg/system/meminfo_unix_test.go
pkg/system/stat_freebsd_test.go
pkg/system/stat_linux_test.go
pkg/system/stat_unix_test.go
pkg/system/utimes_freebsd.go

The code was passing timespec arguments to lutimes which expects timeval arguments. This likely only ever 'worked' because the nanoseconds field is nearly always zero.

Fix LUtimesNano on FreeBSD

---

pkg/system/rm.go
pkg/system/rm_common.go
pkg/system/rm_freebsd.go

pkg/system: Allow EnsureRemoveAll to delete trees with immutable files

---

tests/helpers.bash
tests/idmaps.bats

All the other integration tests pass on FreeBSD with the zfs driver. Some of them fail with the vfs driver but those also fail on Linux.

tests/idmaps.bats: only run idmaps tests on Linux

---

types/options.go

HPC Customers noticed that storage was attempting to read files in /usr and /etc, even though they set XDG_CONFIG_HOME, they expect to only read config files in this directory.
Fixes: https://github.com/containers/podman/issues/15680
(Actually partial fixes), need to look at other config files.

If XDG_CONFIG_HOME env is set we should use it and ignore defaults

---

tests/helpers.bash

This was setting the time to 1970-1-1 00:00 in the local timezone instead of UTC which causes test failures if the local timezone has a positive offset from UTC. Fixes #1365.

tests/helpers.bash: Fix setting the mtime to epoch in createrandom

---

types/options.go

Follow up to https://github.com/containers/storage/pull/1357
Podman tests suggest that do not need to use XDG_CONFIG_HOME if storage.conf does not exists.  In that case we fall back to /etc/containers/storage.conf and /usr/share/containers/storage.conf

Use system defaults if storage.conf does not exist in XDG_CONFIG_HOME

---

layers.go

There was a possibility to panic due to such behavior: attempted to update last-writer in lockfile without the write lock
Fixes: https://github.com/containers/storage/issues/1324
Signed-off-by: Mikhail Khachayants <tyler92@inbox.ru>

Fix accessing to layer without lock

---

pkg/archive/archive.go
pkg/archive/archive_freebsd.go
pkg/archive/archive_unix.go
pkg/archive/archive_unix_test.go
pkg/archive/archive_windows.go
pkg/parsers/operatingsystem/operatingsystem_unix_test.go
pkg/system/mknod.go
pkg/system/mknod_freebsd.go

This exposed a couple of FreeBSD bugs in pkg/archive which are also fixed here.

Make the unit tests work for FreeBSD

---

drivers/driver_linux.go

In the context of github.com/containers/storage/drivers.GetFSMagic() when log-level debug is enabled show the filesystem type/or ID that is returned by the statfs(2) system call in particular when the ID is not known to podman. This might suggest an unsupported configuration.
Signed-off-by: Aaron Tomlin <atomlin@redhat.com>

drivers/driver_linux: Show fstype in GetFSMagic() if debug logging is enabled

---

containers.go
images.go

Match containers and image lock to the new layer lock method. in https://github.com/containers/storage/pull/1351

Fix accessing containers and image locks

---

drivers/overlay/overlay.go

If the backing filesystem is not supported with OverlayFS as a container storage driver/or graph driver then do not continue. In this context, report the incompatibility by notifying the user of an unsupported configuration. The filesystem type/or ID that is returned by the statfs(2) system call is reported too, to assist further troubleshooting efforts. It can be used to deduce the actual filesystem used for the container storage graph directory.
Signed-off-by: Aaron Tomlin <atomlin@redhat.com>

drivers/overlay: Notify the user if the backing filesystem is not supported with OverlayFS

---

containers.go
images.go
layers.go
pkg/lockfile/lockfile.go
pkg/lockfile/lockfile_test.go
pkg/lockfile/lockfile_unix.go
pkg/lockfile/lockfile_windows.go

It is not valid as currently implemented, and there is no known user.
See #1344 for more discussion.

Remove lockfile.Locker.RecursiveLock (alternative to #1344)

---

containers.go
deprecated.go
images.go
images_test.go
layers.go
store.go
userns.go

c/storage currently exports `ContainerStore`,`ImageStore`,`LayerStore`, and several component interfaces, publicly.
Meanwhile there are no _public_ ways to obtain implementations of these interfaces (and no non-public callers in Podman or CRI-O that I can find); and the public interfaces at least _look_ like an impediment to changing the C/I/L store interfaces (e.g. to change locking).
To clarify that, make the used C/I/L store implementations private (and keep the public interfaces in `deprecated.go` purely for formal API compatibility).
Then, as a proof of concept, remove unused <s>`RecursiveLock` (compare #1344),</s> `LoadLocked`, and `Lookup` methods.
@nalind RFC. I might well be missing something about external users of these interfaces.
Cc: @vrothberg for the `RecursiveLock` method …

Make {container, layer, image} store APIs private

---

pkg/mount/unmount_unix.go
pkg/system/rm.go
store.go

A couple of beatifications along with a change in hope to improve on containers/podman/issues/11594.  Please refer to the individual commits.
@giuseppe @nalind @rhatdan WDYT?

container deletion - EBUSY improvement

---

store.go

Factor out the repetitive “find primary + additional stores, and lock them in order” parts out of the top-level storage.Store API into helpers: `readAll{Layer,Image}Stores`.
Overall, this is just a refactoring that should not change behavior. The goal is to decrease the number of individual call sites to the locking code — so that the code refactored here does not need to be touched again for locking changes.
The more complex readers that don’t fit the simple locking schemes of these helpers remain unchanged; the locking in them will be updated individually.
This could be a bit better with Go 1.18, but that’s for the future.
See individual commit messages for (a bit) more detail.
#1383 is a counterpart for the write paths.

Factor out the infrastructure for reading primary + additional stores

---

store.go

Factor out the repetitive “find and lock C/I/L store” parts out of the top-level `storage.Store` API into helpers: `writeTo{Container,Image,Layer}Store` and `writeToAllStores`.
Overall, this is just a refactoring that should not change behavior. The goal is to decrease the number of individual call sites to the locking code — so that the code refactored here does not need to be touched again for locking changes.
The more complex writers that don’t fit the simple locking schemes of these helpers remain unchanged; the locking in them will be updated individually.
See individual commit messages for (a bit) more detail. It might be more convenient to review this in a view that ignores whitespace changes.

Consolidate the common parts of simple writers

---

store.go
userns.go

- `imageTopLayerForMapping`, in the `cParentLayer` loop, was reading all additional layer stores, although only some of them might have been locked at that point.
- `getAutoUserNS` → `getMaxSizeFromImage` was assuming that all layer stores are locked, but in fact the additional layer stores were all unlocked at that point
- `getMaxSizeFromImage` was calling `store.getLayerStore()` and the like, which could potentially trigger a reload via `graphLock` and return a _different_ store than the one that was locked
So, lock _all_ layer stores in `CreateContainer` (at least on the path where images are involved), and pass the locked layer stores down the call stack.
Also, document a bit more explicitly what's going on.

Fix layer locking in CreateContainer

---

store.go

Only lock the primary layer store for reading in `CreateImage` and `Layers`; I can’t see any reason for the exclusivity.
Cc: @nalind in case I’m missing something, primarily in `CreateImage`.

Lock layers only for reading

---

containers.go
images.go
images_test.go
layers.go
store.go

Instead of going
-	3 store methods
-	store.updateNames+enum
-	3 sub-store methods
-	subStore.updateNames+enum
-	applyNameOperation+enum,
simplify to
-	3 store methods
-	store.updateNames+enum
-	subStore.updateNames+enum
-	applyNameOperation+enum,
Should not change behavior. Looking purely at `updateNameOperation`, invalid values would now be detected after doing more work, but there is no way for an external caller to trigger use of an invalid value anyway.

Simplify the name update call stack

---

store.go

It's completely unclear to me why this is necessary; the unmount calls actually write to the separate mountpoints.json file, with a separate lock.
When this was originally introduced in b046fb5a9a1ad6d25bd6c854400f090131c8a21c , there wasn't a separate `mountpoints.json` file (changed in 0183a293dc01f22561b83448340c08e55f9b979b ), and store.go was manually calling `Touch()` everywhere (changed in c496eac6c393dee3a50610deaa19d45351026dec) ; so my best guess is that this is just an artifact of making those two API changes, and the `Touch()` is not actually necessary.
@nalind @rhatdan is there some non-obvious purpose for the `Touch()` call here?

Remove a manual layerStore.Touch() call from store.Shutdown()

---

pkg/lockfile/lockfile_unix.go

A newly created lock-file is of size zero, which happens for example if you reset the storage state. In this state, lockfile.Modified() always returns true, because it thinks any short read means something changed.
I ran into this with the image store, which was empty (using images from a different store), and it keept re-reading the image store all the time even if nothing changed (i.e. both lock file reads returned zero bytes).
The proper way to handle this seems to be to compare partial reads also.
Signed-off-by: Alexander Larsson <alexl@redhat.com>

Correctly handle lockfiles without writes

---

drivers/overlay/mount.go
drivers/overlay/overlay.go
tests/layers.bats

If we have enough layers that even using relative paths for symlinks to the diff directories won't make the list of lower directories and options fit in a single page,
* ~create a temporary directory~
* ~mount a tmpfs there~
* ~bind mount from the diff directories to subdirectories of the temp directory with short names~
* ~mount using those bind-mounted directories as the lower directories~
* ~detach the temporary directory~
* ~remove the temporary directory~
* open the various lowers for reading
* use the descriptor names in the `lowerdir=` list
This is ~noticeably~ slower, so don't take these extra steps unless we know we absolutely have to.
Should help with https://github.com/cri-o/cri-o/issues/6261.

overlay: try harder with more layers

---

drivers/overlay/overlay.go

Since maxDepth is 500 and not 128, the comment doesn't make sense. Instead of defining a new named constant, just use the value, since the choice of 128 was already explained in the paragraph just above it.

Fixup a comment in the overlay driver

---

types/options_test.go
types/utils_test.go

Now that we require Go 1.17, benefit from it at least in this respect.

Use testing.T.Setenv

---

containers.go
images.go
images_test.go
layers.go
store.go

Final big part of the preparatory infrastructure work on locking.
Move the conceptual responsibility for locking/loading `containerStore`, `imageStore` and `layerStore` from the caller (`store`) into the three individual C/I/L objects. And in those objects, centralize it.
I.e. this goes from
```go
func (s *store) method(…) {
…
layerStore.Lock()
defer layerStore.Unlock()
if err := store.ReloadIfChanged(); err != nil { … }
```
to
```go
func (s *store) method(…) {
…
if err := layerStore.startWriting(); err != nil { … }
defer layerStore.stopWriting()
```
that will, finally, allow us to change the design in a single place, `startReading` / `startWriting`. E.g. to:
- Do in-process locking correctly (#1332 )
- Clean up inconsistent state, and write it back to disk, even if the caller is a reader …

Move locking responsibility from store.go to the container/image/layer stores

---

pkg/lockfile/lockfile_unix.go

If we ever check the last-writer of a lock file and get back a zero value, don't only check if subsequent last-writer values match its first zero bytes, which is always true, as a test to see if the last-writer value has remained unchanged.
Related: https://github.com/containers/podman/pull/16211

Fix lockfiles never detecting changes

---

store.go

Don't create "mounts" or "tmp" subdirectories under the graph root at startup, since we ended up not using them.
Resolves https://github.com/containers/podman/discussions/16195.

Don't create $root/{mounts,tmp}, which we don't use

---

pkg/mount/unmount_unix.go

Move the break statement out of the switch to actually break out of the loop as intended.
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

fix break during unmount

---

images.go
layers.go
store.go

Don't immediately unlock the layer store after locking it.
Luckily it only matters for additional stores.

Fix locking bugs

---

pkg/lockfile/lockfile_test.go

Test changes introduced in #1396.  Should fail if either #1396 or #1391 is reverted.

Add TestLockfileMultiprocessModified()

---

pkg/archive/archive.go
pkg/archive/changes_bsd_test.go
pkg/archive/changes_unix.go
pkg/archive/diff.go
pkg/archive/fflags_bsd.go
pkg/archive/fflags_unsupported.go
pkg/system/lchflags_bsd.go
pkg/system/rm.go
pkg/system/rm_freebsd.go
pkg/system/stat_common.go
pkg/system/stat_freebsd.go
pkg/system/stat_freebsd_test.go
pkg/system/stat_unix.go
tests/delete-container.bats
tests/import-layer.bats

The implementation could be shared with darwin and other BSDs if needed but initially is only enabled on FreeBSD. This uses the SCHILY.fflags PAX option to encode flags which is supported by libarchive (bsdtar) and star. The flag save/restore entry points are exported, allowing them to be used by buildah/copier.
To support applying diffs to trees with flags, I added logic to reset immutable flags during the UnpackLayer process - this is slightly complicated by the desire to support immutable directories which needs to defer setting fiags on directories to after all modifications to the directory contents. Fortunately, something similar is already in place for setting directory modify times.

Add support for exporting and importing file flags on FreeBSD

---

containers.go
images.go
layers.go
pkg/lockfile/lockfile.go
pkg/lockfile/lockfile_test.go
pkg/lockfile/lockfile_unix.go
pkg/lockfile/lockfile_windows.go

As detailed in #1388, `Lockfile.Locked()` does not return the right values if there are multiple users of the same lock within a single process.
So, replace the users by callers correctly tracking locking state; and add `LockFile.AssertLocked` and `Lockfile.AssertLockedForWriting` purely for diagnostic purposes. These functions can trigger a panic in clearly invalid situations, but can’t be used by callers to avoid tracking state correctly. That’s a bit risky, so I’ll at least trigger Buildah and Podman CI runs with this change
Following the precedent of #1376 , this removes the `Locked` method, breaking API of c/storage.
See individual commit messages for details.
Fixes #1388 (and makes another small step towards fixing #1136; the relevant places are now annotated).

API break: Remove Lockfile.Locked

---

pkg/lockfile/lockfile_test.go
pkg/system/stat_common.go
pkg/system/stat_windows.go

This is my penance for not actually finishing the warning cleanup, so that I could bump the `golangci-lint` version and make these things enforced on every pull request.
So, I get to run the recent version of `golangci-lint` locally, ignore the things I didn’t fix yet, and fix the newly introduced issues after the fact.

Fix some warnings again

---

containers.go
images.go
layers.go

See individual commit messages for details
Cc: @nalind to make sure I’m not missing some error resiliency trade-off.
I’ll run this through Buildah and Podman CI together with some follow-up PRs.

Don’t silently ignore errors when decoding JSON or deleting incomplete layers

---

drivers/overlay/overlay.go

commit 7c5964df95c892cfbdbce594cf5a8e2973c70fd7 changed the way the mountFrom program works by always using the /proc/self/fd/%d path for the lower dirs.  Hence there is no gain to pass a path relative to the storage, but we can just pass the absolute path as the resulting file path length is the same and won't affect how many layers we can specify.
This fixes idmapped mounts when the total length of lower layers is > 4096 and it also solves the problem of using layers from additional stores.
Closes: https://github.com/containers/storage/issues/1410

overlay: drop relLowers workaround

---

drivers/overlay/idmapped_utils.go

the two arguments to clone are swapped on s390x. This patch fixes the call when running on s390x.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2108887

overlay: fix call to clone on s390x

---

pkg/unshare/unshare_linux.go

this check would prevent the function to ever be used when running as root, since we won't check what capabilities are currently available to the process.

unshare: fix creating a userns when running as root

---

pkg/chunked/compression_linux.go
pkg/chunked/internal/compression.go

we do not own containers.io so let's use io.github.containers, since the project is part of the containers organization under github.
@ktock FYI

chunked: use io.github.containers

---

drivers/overlay/idmapped_utils.go

the two arguments to clone are swapped on s390x. This patch fixes the call when running on s390x.  Cherry-picked from #1418.

[release-1.42] overlay: fix call to clone on s390x

---

drivers/quota/projectquota.go

There is the rare case that something removed the backingFsBlockDev, which usually points to `/var/lib/containers/storage/overlay/backingFsBlockDev`. In that case, all `SetQuota` operations would fail on overlay layer creation.
We now work around that error by recreating the backingFsBlockDev.
/hold
I have to test this on CRI-O and rebase the change to c/storage v1.37.0
Refers to https://github.com/containers/storage/pull/1326

[main] Recreate missing backingFsBlockDev on setting xfs project quota

---

pkg/parsers/kernel/uname_freebsd.go
pkg/parsers/kernel/uname_unsupported.go
pkg/parsers/kernel/uname_unsupported_type.go

This is needed by podman/test/utils.
[NO NEW TESTS NEEDED]

pkg/parsers: Enable GetKernelVersion on FreeBSD

---

pkg/parsers/kernel/uname_unsupported.go

In Buildah:
```
GO111MODULE=on go mod vendor
internal error: failed to find embedded files of github.com/containers/storage/pkg/parsers/kernel: /Users/mitr/Go/pkg/mod/github.com/mtrmac/storage@v0.0.0-20221110150436-c5fb20795713/pkg/parsers/kernel/uname_unsupported.go:8:2: string literal not terminated
```

Fix a typo that breaks build / vedoring

---

containers.go
images.go
layers.go
pkg/parsers/kernel/uname_unsupported.go

When we reload the store in a reader, drop the lock, lock for writing, reload again to trigger cleanup, and then lock again for reading and proceed with the originally intended operation.
This should fix #1136 , although that’s not yet proven. (It only took 6 weeks of work to get this far…)
<s>Built on top of #1399 and #1406 .</s>

Clean up inconsistent stores also in readers

---

containers.go
images.go
store.go

- Don’t write to `BigDataDigests` and `BigDataSizes` in methods that only have a read lock — either avoid that, or use a write lock
- Stop using type checks to see if an image store is primary, or read-write; it just doesn’t work like that.
---
\*Grumble\* I’m getting increasingly desperate for #1389 . Staring at locking code trying to not make a mistake feels like writing C memory allocation code manually — however good a human can get at it, machines do it faster, and they never get tired or inattentive.

More small locking fixes

---

drivers/overlay/overlay.go

OpenZFS works fine as backing fs for overlayfs after the following commits:
https://github.com/openzfs/zfs/commit/e015d6cc0b60d4675c9b6d2433eed2c8ef0863e8
https://github.com/openzfs/zfs/commit/86db35c447aa3f4cc848497d78d54ec9c985d1ed
https://github.com/openzfs/zfs/commit/dbf6108b4df92341eea40d0b41792ac16eabc514
Right now this only works with OpenZFS master, but it will find its way to 2.2 eventually, and right now testing it is entirely blocked by this check.

overlay: allow overlaying on top of zfs

---

.cirrus.yml
cmd/containers-storage/main.go
containers.go
contrib/cirrus/build_and_test.sh
drivers/aufs/aufs.go
drivers/btrfs/btrfs.go
drivers/devmapper/driver.go
drivers/driver.go
drivers/overlay/overlay.go
drivers/vfs/driver.go
drivers/windows/windows.go
drivers/zfs/zfs.go
layers.go
pkg/ioutils/fswriters.go
storage.conf
store.go
tests/create-container.bats
tests/helpers.bash
types/options.go
utils.go

This is the containers/storage part of https://github.com/containers/podman/pull/16371
It adds a new global storage mode option called 'transient_store'. If this is true then the primary databases for container-specific data (i.e. not image data) is made transient, by placing the storage in runroot (i.e. on tmpfs).
In particular, for c/s this implies:
* `.../storage/overlay-containers` is renamed `.../storage/overlay-transientcontainers`, and its `layers.json` is stored in the runroot.
* There is a new location `../storage/overlay-transientlayers/` that is similar to `../storage/overlay-layers/`, but is only used for the container layers (not images), and that has the `layers.json` file in runroot.
This completely erases the time spent fdatasync() calls for the json files written during …

Support transient storage mode

---

drivers/quota/projectquota.go

Cherry-pick of https://github.com/containers/storage/pull/1325/commits/aa0d39469a7e4de2c30e29ea596b767e1ff36ce1 into `release-1.37` for CRI-O 1.24/23.

[release-1.37] Recreate missing backingFsBlockDev on setting xfs project quota

---

drivers/quota/projectquota.go

Cherry-pick of https://github.com/containers/storage/pull/1325/commits/aa0d39469a7e4de2c30e29ea596b767e1ff36ce1 into `release-1.37` for CRI-O 1.22.
I would need a new v1.34.2 release after that got merged.
@containers/storage-maintainers PTAL

[release-1.34] Recreate missing backingFsBlockDev on setting xfs project quota

---

layers.go
store.go

Motivated by #1433 seeing unexpected layer store refreshes / existence of parallel layer stores for the same directory in a single process, this:
- Attempts to document the concurrency design and rules for accessing `store` fields and `store.graphLock`. I’m not at all sure it’s correct, at least I want to establish the precedent that the design is expected to be documented
- Consolidates the uses of `store.graphLock` to guard against `Shutdown` calls to `store.startUsingGraphDriver` / `store.stopUsingGraphDriver` helpers, instead of copy&pasted and code slowly deviating over time. This is similar to the CIL`Store.startWriting` approach.
- Fixes users that specifically rely on `store.graphLock` and can trigger a graph driver reload to actually use the reloaded graph driver for their …

Document and improve store locking

---

layers.go
pkg/ioutils/fswriters.go

We're currently reloading the layers json file every time we (ourselves) write it
This PR fixes this.

Avoid unnecessary reloads of store data

---

userns.go

Using `%q` as format specifier for size prints non-meaningful error messages instead use `%v` which will print in default format.
Example Bad error message
```console
Error: identifier is not a container: preparing container for next step:
creating build container: creating container: the container needs a user
namespace with size '𘛋' that is bigger than the maximum value allowed
with userns=auto '𐀀'
```
See error msg here: https://github.com/containers/podman/issues/16795

userns: stop printing size as escaped string in error and instead use `%v`

---

drivers/counter.go
drivers/overlay/overlay.go
drivers/quota/projectquota.go

There are two leaks identified in https://issues.redhat.com/browse/OCPBUGS-3652 that affect long-running processes (CRI-O). Fix them here, with more details in commits.

Fix some leaks in maps

---

layers.go

There was a possibility to panic due to such behavior: attempted to update last-writer in lockfile without the write lock
Fixes: https://github.com/containers/storage/issues/1324
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2153883
Signed-off-by: Mikhail Khachayants <tyler92@inbox.ru>
(cherry picked from commit e35b061b8515b8f266ec0b0f6bafe7e1796a7d69)

[release-1.42] Fix accessing to layer without lock

---

drivers/btrfs/btrfs.go

same as kdave/btrfs-progs@0345143
similar fix as https://github.com/moby/moby/pull/44707
fixes #1454

fix: workaround field rename in btrfs-progs 6.1

---

idset.go
types/errors.go

Want to allow Podman to print helpful error message when users runs out of UIDs to use with podman run --userns=auto.

Define error type for ErrNoAvailableIDs

---

containers.go
images.go
layers.go
store.go
userns.go

**EDIT: See the description in https://github.com/containers/storage/pull/1346#issuecomment-1314316901 instead.**
To see what fixing #1332 would be like. This is on top of, and includes, #1345.
The goal is to protect in-process readers against concurrent writes to memory by `Load`. Let’s discuss the theory of that, and the performance, in #1332 , this is an attempt to draft what that could look like.
(Most of this PR could be merged, and might be useful, without actually changing the locking scheme — but without changing the locking scheme I don’t think we have a reason to do and review all of those code changes).
Right now, locking is open-coded all over the >3000 lines of `storage.store`:
```go
func (s *store) ListLayerBigData(id string) ([]string, error) {
lstore, err := s.LayerStore() …
```

In-process exclusion of readers and writers

---

docs/containers-storage.conf.5.md
drivers/driver.go
store.go
types/options.go

This fixes https://github.com/containers/storage/issues/1457
I have tested this locally by vendoring the specific PR into podman and then setting the following `~/.config/containers/storage.conf`:
```toml
[storage]
driver_priority = [
"zfs",
"btrfs",
"overlay"
]
```
podman then tried zfs (but failed as I don't have any zfs partitions) and picked btrfs as the next viable candidate.
Removing the setting causes podman to correctly pick up overlay as the driver.

Make the priority for picking the storage driver configurable

---

internal/opts/opts.go
internal/opts/opts_test.go
pkg/idtools/usergroupadd_linux.go
pkg/stringid/stringid.go

Every app is paying the price for these compilations on startup so make only the users of the functions pay the price.
ValidateDNSSearch is not used anywhere so remove it.

Compile regex on demand not in init

---

.cirrus.yml
pkg/idtools/usergroupadd_linux.go
pkg/regexp/regexp.go
pkg/regexp/regexp_dontprecompile.go
pkg/regexp/regexp_precompile.go
pkg/regexp/regexp_test.go
pkg/stringid/stringid.go

The new Reexp structure, will handle the initialization of regexp and then will do the MustCompile within a sync.Once field.

Create pkg/regexp to better handle init regex

---

types/options.go

This is an amend to https://github.com/containers/storage/pull/1460 That PR was not addressing the case when the system wide config had the driver_priority option configured and the user had no config file of their own. Then `getRootlessStorageOpts` would be called and it would override the graph driver to "vfs".
With this commit we only override the graph driver if driver priority is empty. Otherwise we propagate the driver priority into the storage options, so that the driver autodetection works as expected.

Only override the graphdriver to vfs if the priority is unset

---

userns.go

improve the heuristic to detect the user namespace size needed to run an image.  Hardcode the nobody user value to 65534, which is the value used by the kernel, and ignore this value when parsing /etc/passwd and /etc/group.
Closes: https://github.com/containers/storage/issues/1472

userns: skip the nobody user

---

.cirrus.yml
contrib/cirrus/build_and_test.sh
contrib/cirrus/lib.sh

Make a file and mount it over loopback to ensure that we can test btrfs, assuming we were built with the libraries and the kernel supports it.

Test btrfs in CI

---

Makefile

Remove targets that reference Vagrant-specific setups that were removed well over a year ago, and update `$(sources)` to include files in new packages.

Makefile: remove vestiges of VMs, update $(sources)

---

pkg/idmap/idmapped_utils_unsupported.go

we need it to build on freebsd.

pkg/idmap: add boilerplate for unsupported

---

.cirrus.yml

Try to avoid the need for PRs like #1489 by catching them ahead of time.

CI: check that cross-compilation works

---

.cirrus.yml
contrib/cirrus/build_and_test.sh
contrib/cirrus/setup.sh

Make a file, and then make a pool out of it to ensure that we can test zfs, assuming we have the binaries and the kernel supports it.

Test zfs in CI

---

Makefile
contrib/cirrus/lib.sh
docs/containers-storage-gc.md
drivers/driver.go
layers.go
pkg/regexp/regexp.go
store.go
types/options.go

Run codespell on codebase

---

types/options.go

make sure that the runroot and graphroot are not empty otherwise we will end up using an empty directory as path prefix and create files in the current directory.

options: reject empty runroot or graphroot

---

drivers/overlay/overlay.go

if a mountProgram is specified, let it deal with an unknown backing file system instead of failing early.  The error is kept when we use native overlay.
Closes: https://github.com/containers/storage/issues/1511

overlay: allow unknown backing fs with mountProgram

---

drivers/overlay/overlay.go

if a mountProgram is specified, let it deal with an unknown backing file system instead of failing early.  The error is kept when we use native overlay.
Closes: https://github.com/containers/storage/issues/1511
(cherry picked from commit b9f1697c1714f4ff2141ef3f308154f3968e6fda)
backport of: https://github.com/containers/storage/pull/1512

[1.45] overlay: allow unknown backing fs with mountProgram

---

pkg/chunked/storage_linux.go

report the correct size for a layer that was pulled using the chunked package.

chunked: report the correct size

---

pkg/chunked/storage_linux.go
pkg/idtools/idtools.go

Two error messages suggest that podman-system-migrate is a binary that can be run, when the command is "podman system migrate".

Fix typos in error messages

---

.cirrus.yml

Refactor Ubuntu and Fedora tests to depend on a common base that isn't a task, so that we don't run the Ubuntu test matrix-of-scenarios on top of the Fedora test matrix-of-scenarios, where they would multiply.

cirrus: refactor Ubuntu and Fedora test tasks

---

drivers/quota/projectquota_unsupported.go

Fixed building of the containers/storage for linux without usage of CGO (tags="linux exclude_disk_quota" & CGO_ENABLED=0): added missing method for the stub Controller implementation.
Refs https://github.com/containers/storage/commit/891593970ae79687f139871f2ae105582060a04b.

fix(quota): added missed ClearQuota method to fix go-builds without cgo

---

Makefile
cmd/containers-storage/name.go
containers.go
docs/containers-storage-add-names.md
docs/containers-storage-get-names.md
docs/containers-storage-remove-names.md
docs/containers-storage-set-names.md
images.go
images_test.go
layers.go
store.go
tests/names.bats
userns.go

When updateNames() copies an image's record from a read-only store into the read-write store, copy the accompanying data as well.
Add fields for setting data items at creation-time to LayerOptions, ImageOptions, and ContainerOptions to make this easier for us and our consumers.

Complete "pulling up" of images in updateNames()

---

drivers/overlay/overlay.go

The overlay driver previously raised an error when encountering an unsupported filesystem. This commit changes the error message to a debug log, allowing the overlay driver to continue its operation even with unsupported filesystems, without causing a failure.
[NO NEW TESTS NEEDED]
Introduced-by: https://github.com/containers/storage/pull/1374
Closes: https://github.com/containers/storage/issues/1546

overlay: change error to debug log for unsupported fs

---

drivers/graphtest/graphtest_unix.go

Convention for tests is that they `Put()` any layers they `Get()`.  Fix this omission in `DriverTestSetQuota()` and change the layer name from "zfsTest" to "quotaTest", because we have quota support on more than just zfs.

DriverTestSetQuota: Put() after Get()

---

containers.go
drivers/overlay/overlay.go
drivers/vfs/driver.go
images.go
utils.go

Replace the newer nameLooksLikeID() function with calls to stringid.Validate(), which does the same thing.

Drop nameLooksLikeID()

---

drivers/overlay/overlay.go

never create the native idmap mount when a mount program is used.

overlay: disable native idmap with mount-program

---

.cirrus.yml
contrib/cirrus/build_and_test.sh
contrib/cirrus/setup.sh

Ref: https://github.com/containers/automation_images/pull/267

Cirrus: Migrate Ubuntu to Debian CI VM Images

---

containers.go
images.go
layers.go
store.go
utils.go

We previously started "pulling up" images when we changed their names, and started denying the presence of images in read-only stores which shared their ID with an image in the read-write store, so that it would be possible to "remove" names from an image in read-only storage.
Do the same when we're asked to create an image, since denying the presence of images with the same ID in read-only stores would prevent us from finding the image by any of the names that it "had" just a moment before we created the new record.

"pull up" images when creating them, too

---

cmd/containers-storage/copy.go
cmd/containers-storage/create.go
cmd/containers-storage/layers.go
cmd/containers-storage/main.go
cmd/containers-storage/mount.go
cmd/containers-storage/unshare.go
docs/containers-storage-create-layer.md
docs/containers-storage-create-storage-layer.md
docs/containers-storage-unshare.md
docs/containers-storage.md

* Add "unshare", "create-storage-layer", and "storage-layers" commands to the test helper, along with a "-U" flag to have it unshare when handling a given command.
* Add "-o" as an alias for the "--owner" flag to "copy".
* Add "-r" as an alias for the "--ro" flag to "mount".
* Add a "-q" ~flat~ flag to "layers" so that we can list just the IDs.
* Drop mention of a couple of not-implemented options from docs/containers-storage-create-layer.md.

Test helper: add "unshare"/"create-storage-layer"/"storage-layers"

---

drivers/overlay/overlay.go
drivers/vfs/driver.go
tests/idmaps.bats

chown the root mount to root in the userns so that it can be used by the container.

drivers: chown root mount to root in the userns

---

Makefile
drivers/aufs/aufs.go
drivers/aufs/aufs_test.go
drivers/btrfs/btrfs.go
drivers/btrfs/btrfs_test.go
drivers/devmapper/deviceset.go
drivers/devmapper/devmapper_test.go
drivers/devmapper/driver.go
drivers/graphtest/graphbench_unix.go
drivers/graphtest/graphtest_unix.go
drivers/graphtest/testutil.go
drivers/graphtest/testutil_unix.go
drivers/overlay/overlay.go
drivers/overlay/overlay_test.go
drivers/quota/projectquota.go
drivers/template.go
drivers/vfs/driver.go
drivers/vfs/vfs_test.go
drivers/zfs/zfs.go
layers.go

* Implement ListLayers() for the aufs, btrfs, and devicemapper drivers, along with a unit test for them.
* Stop filtering out directories with names that aren't 64-hex chars the overlay and vfs ListLayers() implementations, which is more a convention than a hard rule.
* Close() a dangling ReadCloser in NaiveCreateFromTemplate.
* Have layerStore.Wipe() try to remove remaining listed layers after it removes the layers that the layerStore knew of.
* Switch from using plain defer to using t.Cleanup() to handle deleting layers that tests create, have the addManyLayers() test function do so as well.
* Remove vfs.CopyDir, which near as I can tell isn't referenced anywhere.

Extend driver.ListLayers()

---

layers.go
pkg/archive/archive.go

The documentation says
> The new Buffer takes ownership of buf, and the
> caller should not use buf after this call.
so use the more directly applicable, and simpler, bytes.Reader instead, to avoid this potentially risky use.

Don't use bytes.NewBuffer to read data

---

check.go
check_test.go
cmd/containers-storage/check.go
docs/containers-storage-check.md
docs/containers-storage.md
drivers/driver.go
store.go
tests/check.bats
tests/helpers.bash
tests/idmaps.bats
types/errors.go

Add initial Check() and Repair() methods to Stores.
Check() checks for inconsistencies between the layers which the lower-level storage driver claims to know about and the ones which we know we're managing.  It checks that layers referenced by layers, images, and containers are known to us and that images referenced by containers are known to us.  It checks that data which we store alongside layers, images, and containers is still present, and to the extent which we store other information about that data (frequenly just the size of the data), verifies that it matches recorded expectations. Lastly, it checks that layers which are part of images (and which we therefore know what they should have in them) have the expected content, and nothing else.
Repair() removes any containers, images, …

Initial implementation of consistency checks

---

types/options.go
types/options_darwin.go
types/options_freebsd.go
types/options_linux.go
types/options_test.go
types/options_windows.go

if there are no configuration files present, attempt to use overlay for rootless if fuse-overlayfs is installed or if the kernel is >= 5.13.
Closes: https://github.com/containers/storage/issues/1570

types: try harder to use overlay with rootless

---

cmd/containers-storage/main.go
docs/containers-storage.conf.5.md
drivers/driver.go
drivers/overlay/overlay.go
pkg/config/config.go
store.go
store_test.go
tests/split-store.bats
types/options.go

Allow storage users to split the filesystem of containers vs image store,  `imagestore` if configured will pull images in image storage instead of the `graphRoot` while keeping the other parts still in the originally configured `graphRoot`.

store: add support to split filesystem using `imagestore`

---

store.go
tests/split-store.bats

PR https://github.com/containers/storage/pull/1549 added support for split-filesystem using `--imagestore` and when `--imagestore` is used current `graphRoot` is mounted as an additional store.
In such case the `graphRoot` must be mounted as an `rw` additional image store so users can still `Delete` images from the `graphRoot` if they want to .

store,imagestore: treat `graphRoot` as `rwImageStore` to support `Delete`

---

.cirrus.yml
check.go
check_test.go
store.go

… avoiding quite a bit of the previously-required boilerplate.
This is probably easier to review as individual commits, and maybe with whitespace changes ignored.
@nalind PTAL

Use Go 1.18 generics in the store’s locking helpers

---

drivers/vfs/driver.go
tests/split-store.bats

When we added splitstore support via `--imagestore` the `graphRoot` was added as an `rw` additionalImageStore so lets do same for the `vfs` driver.
See PR for more details:
* https://github.com/containers/storage/pull/1549
* https://github.com/containers/storage/pull/1578

vfs,splitstore: add `graphRoot` as additionalStore

---

.cirrus.yml
pkg/system/rm.go

the mount.RecursiveUnmount() call can be expensive, since it needs to parse the mount table to reconstruct the mount tree.
Attempt the simple case first, and do the more expensive removal only if necessary.

pkg/rm: attempt os.RemoveAll() first

---

store.go

* We must lock store before doing any operation if its not the default imagestore.
* Refactor and address some comments from: https://github.com/containers/storage/pull/1578
How to verify ?
Tests from https://github.com/containers/storage/blob/main/tests/split-store.bats must pass as-is.

store: lock additional store before validating image

---

drivers/quota/projectquota.go

If `C.opendir()` fails, include `errno` along with the path of the directory that we failed to open.

drivers/quota.openDir() log errno if C.opendir() fails

---

drivers/overlay/check.go
drivers/overlay/overlay.go

When we convert the work directory's location to a relative path for passing to mount-in-a-subprocess, don't change the value that we'll subsequently use when removing the "work/incompat/volatile" subdirectory while still in the parent process.  Fixes https://github.com/containers/buildah/issues/4794.

drivers/overlay.get(): only use the relative workdir for mountOverlayFrom()

---

containers.go
images.go
layers.go

The lockfile's write record is now updated prior to the actual write operation.  This ensures that, in the event of an unexpected termination, other processes are correctly notified of an initiated write operation.

store: ensure lockfile is updated before writes

---

layers.go

Other `Unmarshal` calls have already been modified similarly.
This “should not matter” in practice, but we are seeing incorrect mount counts in https://github.com/containers/podman/issues/17216 .

Don't silently ignore errors decoding mountpoints.json

---

drivers/overlay/overlay.go

if `--imagestore` is used then set quota for `imagestore` along with the original `graphRoot`

overlay: set `quota` for imagestore if used

---

docs/containers-storage.conf.5.md
storage.conf

- remap-uids and remap-gids requires a string data type.
- "four keys" -> "three keys"
- "minimum" -> "maximum"

Fix typo in storage.conf

---

drivers/overlay/overlay.go

… instead of only logging a debug-level failure.
We are seeing layers being mounted while our metadata claims that they are unmounted, and this seems to be a way how that could happen without leaving a visible trace.
It's unclear to me why this silently succeeds; this behavior is very long-standing.
Motivated by https://github.com/containers/podman/issues/17216 , where we seem to be seeing mounted layers with zero count in `mount points.json`.
⚠️ I don’t really know what I’m doing, there might be a good reason for the current behavior. Alternatively, I’d like the `Debug` logs to be elevated to at least a `Warning`, possibly outright `Error`. @nalind @giuseppe PTAL.

Fail on unmount/rmdir in overlay.Driver.Put

---

.cirrus.yml

Cirrus CI emits a bunch of warnings like this one:
> task "success" depends on task "fedora-38 vfs", but their only_if conditions are different
~~To fix, use "skip" instead of "only_if". The difference between the two is described at
https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution~~
This was probably a copy-paste leftover from another repo, which uses CI:DOCS
magic to skip some tests. In this repo, it is not used, so remove the condition.

.cirrus.yml: fix a warning

---

docs/containers-storage.conf.5.md
storage.conf
types/options.go
types/options_test.go
types/storage_test.conf

`Remap-User/Group` setting is always override by
`Remap-UIDs/GIDs` setting and ignored.
This commit enables `Remap-User/Group` setting.

options: enable Remap-User/Group setting

---

drivers/driver.go
drivers/driver_darwin.go
drivers/driver_freebsd.go
drivers/driver_linux.go
drivers/driver_solaris.go
drivers/driver_unsupported.go
drivers/driver_windows.go
types/options.go

There is no need for `vfs` to be the default storage driver since kernel
`>= 5.13` supports `overlay` natively however there is use-case for users
who don't had any configs and they started using `vfs` in a default manner following check is a hack to keep `buildah` and `podman` working for such users.
See: https://github.com/containers/storage/pull/1571 for prior discussions.

options: keep using prior drivers if found

---

layers.go

This is a superset of #1612 / #1623 , also fixing an unlikely-to-hit race in use of `pkg/tarlog`.
See individual commit messages for details.

Audit data flow in applyDiffWithOptions

---

check.go
drivers/overlay/overlay.go
layers.go
store.go

Files hard linked in from an OSTree repository won't tend to have the right ownership, permissions, or timestamps on them, so we have to accept that they'll frequently not match what we have on record when we're using one to speed up pulling images.

check: suppress certain errors when pull_options might cause them

---

types/options.go

Honor `imagestore` option from config file for rootless setups.
Fixes issues in: https://github.com/containers/podman/pull/18224

options,rootless: honor `imagestore` from config file

---

drivers/btrfs/btrfs.go
drivers/driver.go
drivers/fsdiff.go
drivers/overlay/overlay.go
drivers/vfs/driver.go
layers.go
pkg/chunked/cache_linux.go
pkg/chunked/compression_linux.go
pkg/chunked/compressor/compressor.go
pkg/chunked/internal/compression.go
pkg/chunked/storage_linux.go
pkg/chunked/storage_unsupported.go
pkg/chunked/zstdchunked_test.go

change the file format to store the tar-split as part of the zstd:chunked image.  This will allow clients to rebuild the entire tarball without having to download it fully.
also store the uncompressed digest for the tarball, so that it can be stored into the storage database.
Needs: https://github.com/containers/image/pull/1976

chunked: generate tar-split as part of zstd:chunked

---

pkg/chunked/storage_unsupported.go

commit 7304a214105f9127f854787755e1eb5231f631db introduced this regression.

chunked: include missing package

---

drivers/driver_linux.go

Composefs use cases use on-disk EROFS for metadata.
I hope more people could be interested in EROFS development and make it better together, hopefully...

drivers: add EROFS filesystem magic

---

pkg/unshare/unshare_freebsd.go
pkg/unshare/unshare_linux.go

Hi all,  
I was reading the source to learn more about how unshare is used in podman. It seems error message that was on this line was copied from a few lines above by accident. 
Since the guidlines say "*No Pull Request (PR) is too small!*" here it is.

Fix error if continueWrite/continueRead pipe open fails

---

pkg/regexp/regexp.go
pkg/regexp/regexp_test.go

Making our exported Regexp type a pointer breaks code that expects to be able to take its address and call methods on the result.
Should fix vendor test error at https://cirrus-ci.com/task/6751444020232192?logs=main#L222.

pkg/regexp: make sure that &Regexp implements the interfaces

---

drivers/driver.go
drivers/overlay/composefs_notsupported.go
drivers/overlay/composefs_supported.go
drivers/overlay/overlay.go
pkg/chunked/cache_linux.go
pkg/chunked/cache_linux_test.go
pkg/chunked/storage_linux.go

ComposeFS has been integrated into the overlay driver.  The EROFS filesystem is now used to mount the file system metadata.  Each layer is mounted individually, but we can change this later and merge multiple layers into a single file system.
Filesystem-level integrity verification is now enabled through the implementation of fs-verity. This enhancement ensures the integrity of both the composefs blob and data files, providing an additional layer of security. Note that this implementation is currently considered a best-effort attempt since there is no control yet on how to configure it as well as there is no support from the overlay driver in the kernel (it is being worked on upstream).
It requires the `composefs-from-json` tool installed and accessible in the path from the …

composefs integration in the overlay driver

---

pkg/idmap/idmapped_utils.go

I noticed this will looking at the new mount api in podman. This is just a small cleanup to use the unix functions instead of calling the raw syscall directly.

pkg/idmap: use unix package for new mount syscalls

---

drivers/overlay/composefs_notsupported.go
drivers/overlay/composefs_supported.go
drivers/overlay/overlay.go

if there are no ACLs, then we mount the EROFS layer with the "noacl" mount option.

overlay: store if there are no ACLs in the layer

---

pkg/archive/changes_other.go
pkg/system/stat_unix.go
pkg/system/stat_windows.go

If we return SkipDir for file mounts, this can generate a diff that deletes all files after the mount point.

pkg/archive: Ignore file mounts when checking for mount points

---

pkg/chunked/storage_linux.go
pkg/chunked/storage_unsupported.go
pkg/chunked/toc/toc.go
pkg/chunked/toc/toc_test.go

The purpose of this move is to reduce dependencies for the new package.

chunked: move GetTOCDigest to a subpackage

---

drivers/btrfs/btrfs.go

We don't need to construct a path ourselves when we already have a method that does it.

btrfs: remove an unnecessary local variable

---

store.go

the flags specified in the layer options were not honored before.

store: propagate Flags from options

---

drivers/overlay/overlay.go

Computing the diff size for the rootful overlay storage driver used the naive diff.  The reasoning was that we have made use of rootful copy-up. The downside is a mind-blowing performance penalty in comparison to the rootless case.
Hence, drop the naive diff and only compute the size of the directory which is absolutely sufficient for the motivating use case of podman-system-df.  This drops the execution of system-df from 19.3s to 0.11s listing 5 containers and 1 image.
Fixes: github.com/containers/podman/issues/19467

overlay: Diffsize: avoid naive diff

---

drivers/overlay/overlay.go

When we're asked for our status, also let the caller know if we support the volatile flag and use of ID-mapped mounts.

overlay.Status(): report volatile/shifting support

---

contrib/cirrus/build_and_test.sh
drivers/overlay/overlay.go

If the specified parent is not ID's parent, use the naive diff.
@mtrmac @giuseppe PTAL

overlay: Diffsize: naive diff when not parent

---

docs/containers-storage.conf.5.md
storage.conf
storage.conf-freebsd
types/options.go

Fixes #1694 
During testing of imagestore in CRIO, I found this error.  Added some documentation and add an error if set to the same value.

add documentation on imagestore and add a warning if set

---

pkg/chunked/compression_linux.go
pkg/chunked/internal/compression.go
pkg/chunked/internal/compression_test.go
pkg/chunked/zstdchunked_test.go

commit 7bbf6ed44807eecfc1f9d3da9ff7da8cdb8e48b8 introduces an error where the generated footer is not correct.

chunked: fix generating footer

---

drivers/overlay/overlay.go

When `imagestore` is used as configuration to simulate `split-store` fs , keep `merged` with original `graphroot` and only keep `read-only` `lower` dir in `imagestore`.

overlay: with `imagestore` keep `merged` with `graphroot`

---

OWNERS

The OpenShift CI and merge bots expect an OWNERS file to be present to tell them who's allowed to tell them to do what.  If you're reviewing this and I forgot you, comment.

Add an OWNERS file for the merge bot to refer to

---

drivers/overlay/composefs_supported.go
pkg/loopback/attach_loopback.go

otherwise it fails when mounting a file that was protected with fs-verity.

overlay, composefs: mount loop device RO

---

store.go

serialize the call to containersStore.Delete(id) since it attempts to recursively remove the graphroot directory.
Doing so, it makes ineffective the other goroutine that attempts to remove safely the graphroot with EnsureRemoveAll.  Depending on what goroutine is faster, there can be a flake like:
2023-09-26T17:49:02.6708666Z   stderr: Error: cleaning up storage: removing container 6ebff2c6c6f5fe78c158956a88467ef7af6f6a7c3d40334d248c7b7409341230 root filesystem: 1 error occurred: * unlinkat /var/tmp/podman_test3482607530/root/overlay-containers/6ebff2c6c6f5fe78c158956a88467ef7af6f6a7c3d40334d248c7b7409341230/userdata/shm: device or resource busy
it is a difficult to trigger condition, but I am hitting it constantly in: https://github.com/containers/crun/pull/1312
Signed-off-by: Giuseppe …

store: serialize container deletion

---

pkg/system/rm.go

reduce the waiting time for attempting again the removal to 10ms instead of the current 100ms.
Currently, if we hit the timeout, we add an artificial 100ms delay to the container cleanup, while with this we will react faster when the removal is possible.

pkg/system: reduce retry timeout for EnsureRemoveAll

---

cmd/containers-storage/diff.go
docs/containers-storage-applydiff-using-staging-dir.md
docs/containers-storage.md
drivers/overlay/check.go
drivers/overlay/composefs_supported.go
drivers/overlay/mount.go
drivers/overlay/overlay.go
tests/apply-diff.bats

use the new overlay data-only feature to mount the composefs data directory so there is no need for upper layers to create whiteouts to hide payload files.
The feature was added to Linux 6.5.

overlay, composefs: use data-only lower layers

---

store.go

Move the execution of RecordWrite() before the graphDriver Cleanup(). This addresses a longstanding issue that occurs when the Podman cleanup process is forcely terminated and on some occasions the termination happens after the Cleanup() but before the change is recorded.  This causes that the next user is not notified about the change and will mount the container without the home directory below (the infamous /var/lib/containers/storage/overlay mount). Then when the next time the graphDriver is initialized, the home directory is mounted on top of the existing mounts causing some containers to fail with ENOENT since all files are hidden and some others cannot be cleaned up since their mount directory is covered by the home directory mount.
Closes: …

store: call RecordWrite() before graphDriver Cleanup()

---

drivers/overlay/overlay.go

If parentBase path is additional image store, select the image contained in parentBase.
Otherwise, the overlay storage driver may select another image store that does not contain
the desired image, causing a `no suche file or directory` error.
Fixes: https://github.com/containers/podman/issues/19748

overlay: select additional image store path when using image store

---

drivers/overlay/overlay.go

Let's not pre-create the composefs layers dir every time we mount a layer, but do it only when there is a composefs blob to use.
Closes: https://github.com/containers/storage/issues/1733

overlay: do not precreate the composefs layers dir

---

layers.go

Warning: I don’t really know what I’m doing.
AFAICS this call is intended to "remap" the parent layer's contents to the desired IDMappings; but when there is no parent layer, there is nothing to remap.
Motivation: I’m trying to get c/image tests of c/storage working completely unprivileged. 
On macOS that actually works out of the box (where some potentially relevant points are that after #811 , `pkg/chrootarchive` does not chroot on Darwin, and that `pkg/idtools.SafeChown` does not really chown on Darwin).
On Linux, the out-of-the-box setup starts initializing `vfs` by chowning to (0, 0), and that fails. There is some pre-existing code in https://github.com/containers/image/blob/6bf0d1f0ae6682a5dd9a9d07d41f78be160d4383/storage/storage_test.go#L69-L78 to avoid that by remapping …

Don't call UpdateLayerIDMap when creating a layer with no parent

---

pkg/archive/archive.go

if force_mask is in use, we need to store the root directory permission after we read it from the tar archive.  We were incorrectly reading it from the directory on the filesystem.

archive: fix mode for root dir with ForceMask

---

pkg/unshare/unshare_darwin.go
pkg/unshare/unshare_linux.go
pkg/unshare/unshare_unsupported.go

so that I can use it from https://github.com/containers/podman/pull/20601

unshare: export rootless GID

---

store.go

Store.Version() has long returned an empty slice of [2]string.  Change that to return "Version" and the text from the top-level VERSION file.

Embed text from VERSION for use in Store.Version()

---

store.go

We want to setup empty additonal stores which could potentially be stored on a read-only mount point (ostree).  Currently empty stores work fine as long as the directory is read/write, because when we attempt to lock them, the code wants to create a lock file directory. This returns an error on read-only directories.
This patch ignores read-only addiitonal stores with no content.

On Read/only additional stores, ignore Read/Only errors

---

pkg/archive/archive.go

A prerequisite for fixing https://github.com/containers/image/issues/1627 .

Don't expose account names when creating tar files with hard-coded account IDs

---

pkg/chunked/cache_linux.go
pkg/chunked/cache_linux_test.go

handle cases where there is unexpected data following the manifest in the JSON document.

chunked: reject unexpected data after TOC

---

cmd/containers-storage/diff.go
drivers/driver.go
drivers/overlay/overlay.go
layers.go
store.go

introduce the TOCDigest field for a layer. TOCDigest is designed to store the digest of the Table of Contents (TOC) of the blob.
It is useful when the UncompressedDigest cannot be validated during a partial image pull, but the TOC itself is validated

layers: add new TOCDigest attribute

---

pkg/chunked/compressor/compressor.go

Flush the entire input tarball to the output in the zstd:chunked stream writer.  This is needed to include any trailing zeros that affect the uncompressed digest.
Closes: https://github.com/containers/storage/issues/1771

chunked: flush the input tarball to the output

---

pkg/chunked/storage_linux.go

reject a layer if it contains both a zstd:chunked and an eStargz TOC since there are no guarantees that the two TOCs are consistent.

chunked: disallow both zstd:chunked and eStargz TOCs

---

pkg/archive/archive.go

Change the socket warning to info level as described [here](https://github.com/containers/podman/discussions/19920).

refactor: change socket warning to info

---

pkg/homedir/homedir_unix.go

do not check the mode for the config home directory, as it might not be writeable to the current user.
Closes: https://github.com/containers/storage/issues/1787

homedir: drop check for ConfigHome mode

---

cmd/containers-storage/diff.go
pkg/chunked/storage_linux.go
pkg/chunked/storage_unsupported.go

validate that the retrieved data for converted images matches the expected digest.
The related change in c/image:
```diff
diff --git a/storage/storage_dest.go b/storage/storage_dest.go
index 0cd4392a..56f16461 100644
--- a/storage/storage_dest.go
+++ b/storage/storage_dest.go
@@ -279,7 +279,7 @@ func (s *storageImageDestination) PutBlobPartial(ctx context.Context, chunkAcces
blobInfo:      srcInfo,
}
-       differ, err := chunked.GetDiffer(ctx, s.imageRef.transport.store, srcInfo.Size, srcInfo.Annotations, &fetcher)
+       differ, err := chunked.GetDiffer(ctx, s.imageRef.transport.store, &srcInfo.Digest, srcInfo.Size, srcInfo.Annotations, &fetcher)
if err != nil {
return private.UploadedBlob{}, err
}
```

chunked: validate converted images

---

layers.go

/kind bug
/assign kwilczynski
Manually cherry-pick changes from https://github.com/containers/storage/pull/1641 as these changes contain a fixe that needs to be backported to CRI-O release 1.27, part of OpenShift 4.14 release.
None
None
```release-note
None
```

[release-1.46] [crio-1.27] Cherry-pick changes from containers/storage/pull#1641

---

layers.go

/kind bug
/assign kwilczynski
Manually cherry-pick changes from https://github.com/containers/storage/pull/1641 as these changes contain a fixe that needs to be backported to CRI-O release 1.26, part of OpenShift 4.13 release.
None
None
```release-note
None
```

[release-1.46] [crio-1.26] Cherry-pick changes from containers/storage/pull#1641

---

layers.go

/kind bug
/assign kwilczynski
Manually cherry-pick changes from https://github.com/containers/storage/pull/1641 as these changes contain a fixe that needs to be backported to CRI-O release 1.25, part of OpenShift 4.12 release.
None
None
```release-note
None
```

[release-1.45] [crio-1.25] Cherry-pick changes from containers/storage/pull#1641

---

layers.go

/kind bug
/assign kwilczynski
Manually cherry-pick changes from https://github.com/containers/storage/pull/1641 as these changes contain a fixe that needs to be backported to CRI-O release 1.24, part of OpenShift 4.11 release.
None
None
```release-note
None
```

[release-1.37] [crio-1.24] Cherry-pick changes from containers/storage/pull#1641

---

drivers/driver.go
drivers/overlay/composefs.go
drivers/overlay/overlay.go
pkg/chunked/storage_linux.go
pkg/fsverity/fsverity_linux.go
pkg/fsverity/fsverity_unsupported.go

move the logic to calculate the fs-verity for the files payload to the chunked package, so it is calculated when the files are first created.

overlay: move the fs-verity measurement to the chunked package

---

cmd/containers-storage/image.go
docs/containers-storage-get-image-dir.md
docs/containers-storage-get-image-run-dir.md
store.go
tests/image-dirs.bats

Add ImageDirectory() and ImageRunDirectory(), which return the paths of directories which the caller can use to store image-specific data which will be cleaned up automatically when the image is removed or the system is restarted, respectively.

Store: add ImageDirectory() and ImageRunDirectory()

---

pkg/homedir/homedir_others.go
pkg/homedir/homedir_windows.go

Needed to un-break podman win main.
Needs to be vendored into common, then into podman.

Fix windows runtime dir

---

drivers/overlay/overlay_nocgo.go

Closes: https://github.com/containers/storage/issues/1816

overlay: fix build of composefs without cgo

---

layers.go
store.go

- If the caller does not provide digests (e.g. when reusing a layer found by `LayersByTOCDigest`), only digest uncompressed input once, not twice
- Let the caller provide a `CompressedSize` value to match `CompressedDigest`, so that we don't create layers with incorrect metadata.
Motivated by https://github.com/containers/image/pull/2288 .
Cc: @giuseppe (fairly low priority)

Extend PutLayer to optimize reusing data from existing layers

---

drivers/driver.go
drivers/overlay/overlay.go
layers.go
store.go
userns.go

Add a race-condition-free alternative to using CreateLayer and ApplyDiffFromStagingDirectory, ensuring the store is locked for the entire duration while the layer is being created and populated.
The relative patch for c/image is:
```diff
diff --git a/storage/storage_dest.go b/storage/storage_dest.go
index 88e492b7..51b30a64 100644
--- a/storage/storage_dest.go
+++ b/storage/storage_dest.go
@@ -149,7 +149,7 @@ func (s *storageImageDestination) Close() error {
}
for _, v := range s.diffOutputs {
if v.Target != "" {
-			_ = s.imageRef.transport.store.CleanupStagingDirectory(v.Target)
+			_ = s.imageRef.transport.store.CleanupStagedLayer(v)
}
}
return os.RemoveAll(s.directory)
@@ -669,11 +669,6 @@ func (s *storageImageDestination) …
```

store: new API ApplyStagedLayer 

---

docs/containers-storage.conf.5.md
pkg/chunked/storage_linux.go
storage.conf

by default enable pulling a partial image, it is still possible to disable the feature through the configuration file.
@rhatdan @mtrmac

storage: enable partial images by default

---

cmd/containers-storage/create.go

All the other commands add a newline after printing.

Fix missing newline from stdout of create-container command

---

drivers/overlay/.#overlay.go
drivers/overlay/overlay.go

it seems to honor user namespaces, so no need to treat it as a network file system.
Feedback got as part of the discussion on the issue.
Closes: https://github.com/containers/storage/issues/1839

overlay: drop FHGFSFs from network file systems

---

docs/containers-storage.conf.5.md
storage.conf

Synchronise documentation around the configuration file to accurately reflect new `convert_images` flag.

Synchronise documentation for convert_images flag

---

drivers/overlay/overlay.go

the store might be owned by another user.
Closes: https://github.com/containers/storage/issues/1827

overlay: ignore chown errors in additionalimagestore

---

pkg/chunked/storage_linux.go

the symlinks must preserve their original value without any alteration.

chunked: preserve the original value for symlinks

---

pkg/chunked/cache_linux.go
pkg/chunked/cache_linux_test.go

include the chunk length in the generated  file location format, This enhancement is designed to facilitate the use of the cache by external tools which may not have knowledge of the chunk size.

chunked: add chunk size to cache file

---

drivers/overlay/overlay.go

Revert "overlay: do not recreate "merged" dir"
This reverts commit https://github.com/containers/storage/commit/de38d80855503aac0c46de79b121588cb4d57966.
Podman upgrade tests are faiing because of this[1]. A start of container
created with a previous version is now failing because of the missing
merged dir.
A very simple reproducer is to run a container with a older versin then
update to one with this commit and try to start the container again:
podman run --name test quay.io/libpod/testimage:20240123 echo hi
<-- update podman to a storage version with the reverted commit
podman start -a test
<-- now failing while trying to mount the container
[1] https://api.cirrus-ci.com/v1/artifact/task/5918496639418368/html/upgrade_test-podman-fedora-39-root-host.log.html

Revert commit that breaks podman backwards compatibility

---

pkg/archive/archive.go

**EDIT its this known limitation of docker 25: https://docs.docker.com/engine/release-notes/25.0/#known-limitations**
To reprodce the bug caused by this attribute in docker rootless dind containers you can do
```
containerid="$(docker run -d --privileged --rm -it docker:dind-rootless)"
docker exec -it "$containerid" sh
DOCKER_HOST=unix:///var/run/user/1000/docker.sock docker run --rm -it  ghcr.io/catthehacker/ubuntu:act-latest-20240222
Unable to find image 'ghcr.io/catthehacker/ubuntu:act-latest-20240222' locally
act-latest-20240222: Pulling from catthehacker/ubuntu
6ddad66377a0: Already exists 
a8ffa4da65b6: Already exists 
6f031e49d16f: Already exists 
e8bedde87c3d: Already exists 
d1f12f89b682: Extracting  204.5MB/204.5MB
4ca545ee6d5d: Download complete 
docker: failed to register …
```

Stop putting `user.overlay.*` into container layer

---

drivers/overlay/overlay.go
drivers/vfs/driver.go
layers.go
store.go

simplify the imagestore implementation and use it as a first-class store.  It reduces the amount of code to deal with an image store in the driver (only overlay supports it at the moment).
Closes: https://github.com/containers/storage/issues/1779

store: simplify imagestore implementation

---

pkg/chunked/storage_linux.go

improve the function that combines neighbor chunks.  Instead of using the number of parts, which also includes local files, use only the number of chunks that must be retrieved from the network.
In addition, introduce a threshold limit to merge chunks so that we further reduce the number of requested ranges.

chunked: improve function to merge chunks

---

drivers/overlay/overlay.go
tests/overlay-recreate.bats

follow-up for ccb70a79a69a1a5137ff24720520534bfbcc2316
more information here: https://github.com/containers/storage/issues/1827#issuecomment-1988332922

overlay: create the merged path only if it does not exist

---

pkg/chunked/cache_linux.go
pkg/chunked/internal/compression.go
pkg/chunked/storage_linux.go

if the file is created using the object-store flat directory format, there is no need to set its inodes attributes, as anyway they are ignored when creating the composefs binary blob.
Similarly, we do not need to set file attributes when the deduplication happened through a hard link.

chunked: skip file metadata for composefs-like links

---

pkg/chunked/cache_linux.go
pkg/chunked/cache_linux_test.go

reduce memory usage for the process by not loading entirely in memory any cache file for the layers.
The memory mapped files can be shared among multiple instances of Podman, as well as not being fully loaded in memory.

chunked: use mmap to load cache files

---

store.go

improve the error message returned when MountImage() tries to use a layer from a read-only store.
Previously it returned a simple "layer not known".

store: improve error from MountImage()

---

pkg/chunked/cache_linux.go
pkg/chunked/cache_linux_test.go
pkg/chunked/internal/compression.go

The getString() function was used to extract string values, but it doesn't handle escaped characters.  Replace it with iter.ReadString() that is slower but handles escaped characters correctly.
Closes: https://github.com/containers/storage/issues/1878

chunked: fix unmarshaling of file names

---

pkg/unshare/unshare_linux.go

As I was working on https://github.com/cri-o/cri-o/pull/7990, I found that ReadMappingsProc was the only function that was missing from pkg/unshare.
@giuseppe mention that this would be a good candidate for c/storage.
This PR adds this function to pkg/unshare. Once this is released, we could drop this from podman.

bring read mappings proc into c/storage

---

drivers/aufs/aufs.go
drivers/btrfs/btrfs.go
drivers/devmapper/deviceset.go
drivers/devmapper/driver.go
drivers/driver.go
drivers/overlay/overlay.go
drivers/vfs/driver.go
drivers/windows/windows.go
pkg/archive/archive.go
pkg/archive/changes.go
pkg/archive/copy.go
pkg/archive/diff.go
pkg/chrootarchive/archive.go
pkg/fileutils/exists_test.go
pkg/fileutils/exists_unix.go
pkg/fileutils/exists_windows.go
pkg/fileutils/fileutils.go
pkg/idtools/idtools_unix.go
types/options.go
types/utils.go

On unix it uses the access syscall which is faster than stat for simply checking the existence of a file.
with a file in the cache I see on my machine:
$ go test -bench=.
goos: linux
goarch: amd64
pkg: github.com/containers/storage/pkg/fileutils
cpu: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
BenchmarkPathExists-12           1000000              1037 ns/op
BenchmarkStat-12                  897534              1330 ns/op
I'd expect even better results if the file is not already in the cache.

fileutils: new function to check for path existence

---

pkg/fileutils/exists_test.go
pkg/fileutils/exists_unix.go

wrap the returned error in a os.PathError so the error includes the file path.

fileutils: make (Le|E)xists return os.PathError

---

pkg/chunked/compression_linux.go
pkg/chunked/internal/compression.go
pkg/chunked/internal/compression_test.go
pkg/chunked/storage_linux.go
pkg/chunked/zstdchunked_test.go

Primarily, this ensures that the value in `ApplyDiff`’s `DriverWithDifferOutput.TOCDigest` is really exactly the value we used to validate the digest, by only reading it once and passing it around.
That’s to simplify auditing and make the relationship clear, but it should not change behavior.
Incidentally, this also should fix #1886 — but I still think the binary footer code path should be removed entirely.
Cc: @giuseppe

Refactor to make it clearer that we return the validated TOC value

---

pkg/chunked/bloom_filter.go
pkg/chunked/bloom_filter_test.go
pkg/chunked/cache_linux.go
pkg/chunked/cache_linux_test.go

The bloom filter itself is useful to reduce page faults with the mmap'ed cache files, as it reduces lookups.
Storing the file as a binary instead reduces the file size considerably, with the `quay.io/giuseppe/zstd-chunked:fedora-{38,39,40}{,-updated}` images I see:
before:
```
2575163
2547644
2476816
2462835
2533346
```
after:
```
1319206
1312332
1275803
1270629
1297565
```
so it is ~50% size reduction

chunked: store cache as binary and use a bloom filter

---

pkg/chunked/dump/dump.go
pkg/chunked/dump/dump_test.go

the code was copied from the composefs C version:
if (noescape_space)
hex_escape = !isprint(c);
else
hex_escape = !isgraph(c);
but unicode.IsGraphic() seems to behave differently and includes the space:
isgraph(' ') -> 0
unicode.IsGraphic(' ') -> true

chunked: fix escape of space

---

pkg/chunked/storage_linux.go

if the layer was converted from an existing one, store the original layer size.
Closes: https://github.com/containers/storage/issues/1892

chunked: store original tar size for converted layers

---

pkg/chunked/compression_linux.go
pkg/chunked/internal/compression.go
pkg/chunked/internal/compression_test.go
pkg/chunked/storage_linux.go
pkg/chunked/zstdchunked_test.go

… as discussed in #1886 .
Cc: @giuseppe

Make ZstdChunkedFooterData write-only

---

pkg/chunked/bloom_filter.go
pkg/chunked/bloom_filter_test.go

if the bloom filter size is zero, the "% size" operation fails with a divide by zero.
Closes: https://github.com/containers/storage/issues/1903

chunked: fix divide by zero in bloom filter

---

pkg/chunked/cache_linux.go

it can happen for any reason, like for example using a new cache file format, in this case the file is recreated with the last version. This is internal only and should not be displayed by default.
Closes: https://github.com/containers/storage/issues/1905

chunked: downgrade loading cache file msg to info

---

.cirrus.yml
go.mod
go.sum
idset.go
idset_test.go
pkg/archive/changes_test.go

We are already doing that for downstream consumers, so let’s do it here as well, so that we not surprised by a dependency requiring Go 1.21 suddenly forcing an upgrade.
This is a _very minimal_ update; the code could benefit from some of the new features, e.g. quite a few of the global `sync.Once` variables could be replaced by `sync.OnceValue`/`sync.OnceValues`.
Cc: @nalind @cevich

Update to Go 1.21

---

pkg/chunked/cache_linux.go

if the layer does not have a manifest TOC, just ignore it instead of raising a warning.  There is no need to create a cache file since there is no manifest file to parse.
Closes: https://github.com/containers/storage/issues/1909

chunked: skip cache file for non-partial layers

---

cmd/containers-storage/diff.go
deprecated.go
drivers/overlay/overlay.go
pkg/lockfile/lockfile.go
pkg/lockfile/lockfile_test.go
pkg/lockfile/lockfile_unix.go
pkg/lockfile/lockfile_windows.go
store.go

lock any staging directory while it is being used so that another process cannot delete it.
Now the Cleanup() function deletes only the staging directories that are not locked by any other user.
Closes: https://github.com/containers/storage/issues/1915

overlay: lock staging directories

---

pkg/unshare/unshare.c

[POSIX requires the prototype of the basename function to be declared in the libgen.h header file](https://pubs.opengroup.org/onlinepubs/007904975/functions/basename.html). Therefore, this header file needs to be included in order to make use of this function in a POSIX environment. The `unshare.c` source file uses this function here (without including `libgen.h`):
https://github.com/containers/storage/blob/b193f00d94a4540dc6bbdf73f409ab8f3f00004d/pkg/unshare/unshare.c#L235
Some implementations, e.g. glibc, also define this function in string.h. However, musl (for example) [only defines it in libgen.h](https://git.musl-libc.org/cgit/musl/commit/?id=725e17ed6dff4d0cd22487bb64470881e86a92e7) causing it be implicitly declared (with an `int` return type) which [is by no means cosmetic and can …

pkg/unshare: fix implicit declaration of basename function

---

pkg/config/config.go

Fixes: https://github.com/containers/podman/issues/22473

Ignore failure to ignore thinpool keys

---

drivers/driver.go
drivers/overlay/overlay.go
store.go

Needs: https://github.com/containers/image/pull/2416
This commit changes the store implementation to use TOCDigset as the ID of each layer. This ensures the runtime to pass TOCDigest to the FUSE backend everytime requiring a layer.
This commit modifies c/storage's `LookupAdditionalLayer` to receive a TOCDigest as one of the arguments. Then that TOCDigest is passed to Additional Layer Store as one of the path elements of the FUSE fs. For example, the extracted view of a layer diff contents is provided in the following path:
```
<mountpoint>/base64(imageref)/<TOCDigest>/diff
```
Additional Layer Store implementation attempts lazy pulling of the layer that has the specified TOCDigest in the image.
If that image doesn't contain the layer matching to the TOCDigest, accessing to the layer …

[Additional Layer Store] Use TOCDigest as ID of each layer (patch for c/storage)

---

pkg/chunked/cache_linux.go
pkg/chunked/compression_linux.go
pkg/chunked/internal/compression.go
pkg/chunked/storage_linux.go
pkg/chunked/zstdchunked_test.go

A minimal prototype for a fix of #1888 .
Note that this would immediately break pulling all currently-existing layers.
Also this probably increases memory requirements because the TOC exists as individual Go values longer.
Cc: @giuseppe

Move the tar-split digest into the TOC

---

drivers/quota/projectquota_supported.go

It appears that setting the FS_XFLAG_PROJINHERIT flag when assigning a quota to a directory overrides any requested project ID set (even in the same ioctl!) if a parent directory already has a project ID. And our parent directories always do, as we set the top-level directory to the base project ID for all volumes.
The result of this is that the inherit flag forces every subdirectory to share the same project ID, and thus every time we set a quota, it's set for everything using quotas - not just the single directory we wanted to set it on.
Lacking the inherit flag made me a bit worried about subdirectories, but I can confirm that the quotas themselves are still function (creating a subdirectory in a dir with a quota set and creating files in that directory still applies their size towards …

Fix assignment of quota IDs for XFS quotas

---

pkg/lockfile/lockfile.go
store.go

… and add some comments.
See individual commit messages for details.
Cc: @giuseppe

Fix locking bugs from #1916, and one more

---

pkg/chunked/dump/dump.go
pkg/chunked/dump/dump_test.go

it solves this error with mkcomposefs when the TOC doesn't specify the parent directory for an entry:
Error: committing the finished image: failed to put layer using a partial pull: failed to convert json to erofs: exit status 1: mkcomposefs: Parent directory missing for /usr/share/locale/ca/LC_MESSAGES/libc.mo

composefs: add parent directory if missing

---

pkg/chunked/compression_linux.go

if a digest was not specified in the TOC, ignore completely the tar-split data.
Otherwise the clients fail to pull images created before commit b5413c2bd64742a08384300f09616a66231b21d1.

chunked: ignore the tar-split data if digest is empty

---

pkg/chunked/storage_linux.go

Increase the threshold for auto-merging parts from 128 to 1024. This change aims to reduce the number of parts in an HTTP multi-range request, thus increasing the likelihood that the server will accept the request.
The previous threshold of 128 often resulted in a large number of small ranges, which could lead to HTTP multi-range requests being rejected by servers due to the excessive number of parts.
It partially addresses the reported issue.
Reported-by: https://github.com/containers/storage/issues/1928

chunked: change auto merge threshold to 1024

---

pkg/archive/archive.go

We used to override the root directory permission only when the record for the root directory exists in the archive. However, docker.io/ubuntu:jammy-20240427 lacks such a record and not overriding the root directory permission makes all other permission overrides invalid.

archive: always fix mode for root dir with ForceMask

---

pkg/chunked/dump/dump.go
pkg/chunked/dump/dump_test.go

otherwise if the root is stored as "./", it ends up adding the root node twice causing mkcomposefs to fail.
Closes: https://github.com/containers/storage/issues/1941

dump: use the sanitized path for root check

---

pkg/chunked/storage_linux.go

I was just reading the code and I have a mental checklist item for "invoking open without O_CLOEXEC" that triggered here. (See also e.g.
https://github.com/containers/composefs/pull/185#discussion_r1322925050 )
It has security-relevant properties for us, xref
CVE-2024-21626 for example.
This isn't the only missing variant of this in this codebase, just using this targeted PR to test the waters for more PRs.

chunked: Set O_CLOEXEC

---

drivers/driver.go
drivers/overlay/overlay.go

- Add comments that make clear these are internal values
- Rename "Enabled" to "IfAvailable" to clarify what it does
- Also note that `DifferFsVerityRequired` is not actually set by anything
in this codebase.
Signed-off-by: Colin Walters <walters@verbum.org>
---

graphdriver: Clarify name of fsverity const, tweak docs

---

pkg/chunked/dump/dump.go
pkg/chunked/dump/dump_test.go

Add validation for duplicate entries.  Duplicates are ignored, unless there is a mismatch in the values.  In that case, an error is returned.
Also refactor the tests to avoid duplication.

dump: handle duplicates

---

pkg/chunked/filesystem_linux.go
pkg/chunked/storage_linux.go

It's not hard to grep for /proc/self/fd, but this way is a bit cleaner and avoids typos, etc.

chunked: Add helpers for /proc/self/fd accesses

---

pkg/chunked/dump/dump.go

replace Fprintf(file, string) with Fprint(file, string) since the argument is a raw string and it should not be treated as a formatting directive.
Closes: https://github.com/containers/storage/issues/1955

chunked: use Fprint instead of Fprintf

---

pkg/chunked/internal/compression.go

- Address https://github.com/containers/storage/pull/1939#pullrequestreview-2104615910
- Also just go ahead and comment this out because it's not used, but I think it makes sense to retain as a historical reference

compression: Fix Deprecated: and actually comment out unused bits

---

pkg/chunked/cache_linux.go
pkg/chunked/filesystem_linux.go

My IDE runs a linter by default, and these two show up. For the file one, it's because `Fd()` returns `uintptr` which is unsigned and can't be negative.  IOW, a `File` object should always be a valid opened fd.

chunked: Fix two minor linter issues

---

drivers/overlay/overlay.go

extend the overlayFileGetter interface to correctly read files from a composefs layer.
The overlayFileGetter creates a temporary mount of the composefs blob, grab a directory to its root and immediately unmount it so the mount is visible (and could be leaked) only for a short period.
Alternative to #1944 
Marked as a Draft until Podman tests pass

overlay: extend overlayFileGetter to understand composefs

---

pkg/archive/changes_test.go
pkg/archive/changes_unix.go

When considering changes, don't ignore differences between directories when their mtimes are the only thing we check that's changed.  This creates a difference in behavior between the vfs and overlay drivers that shows up in build conformance tests, such as in https://github.com/containers/buildah/pull/5492.

pkg/archive.statDifferent(): care about mtime for directories

---

pkg/chunked/bloom_filter_linux.go
pkg/chunked/cache_linux.go
pkg/chunked/cache_linux_test.go
pkg/chunked/storage_linux.go

and fix some issues found with the new tests.

chunked: add fuzzing tests for the cache

---

pkg/archive/archive.go
pkg/archive/filter.go
pkg/archive/filter_test.go

use the command line tools when available as they are much faster than the Go libraries.
Especially for gzip, I've registered a 50% improvement
use zstd if available
the performance improvement is not as clear as with pigz, but it is
still measurable difference.

archive: use pigz|zstd if available

---

pkg/chunked/storage_linux.go

utilize the existing pre-allocated buffer instead of allocating a new one in io.Copy().

chunked: use existing buffer for io.Copy

---

pkg/chunked/storage_linux.go

honor the pull_options configuration set for the current store instead of using the default configuration.
Needed by Podman to override the pull options from the command line for a single command.

chunked: honor store configuration

---

pkg/archive/changes_unix.go

Make the logic match the comment for real this time: instead of comparing the datestamps a second time, check the ModeType bits.  h/t to @mtrmac for spotting it at https://github.com/containers/storage/pull/1962/files#r1636517199.

pkg/archive.statDifferent(): fix the previous change

---

pkg/chunked/compression_linux.go

Don't ignore the tar-split when the TOC requires one, otherwise we could deduplicate a layer without tar-split with a layer with tar-split.
Fixes a bug discovered during review in https://github.com/containers/storage/pull/1936#pullrequestreview-2094139878 .
Cc: @giuseppe

Decide on tar-split usage based on trusted data in TOC

---

drivers/copy/copy_linux.go
drivers/graphtest/graphbench_unix.go
lockfile_compat.go

This PR fixes warnings (SA9003, SA4023, SA1019) found by `golangci` when the `staticcheck` linter is enabled. 
- #1579

Fix warnings (SA9003, SA4023, SA1019)

---

drivers/overlay/overlay.go

This PR fixes warning deprecated use of `io/ioutil` (SA1019) found by `golangci` when the `staticcheck` linter is enabled. 
- #1579

Fix deprecated use of ` io/ioutil` (SA1019)

---

drivers/overlay/overlay.go
drivers/overlay/overlay_test.go

Using a mount_program is not a necessary requirement for users creating a shared store, as the store can be consumed by other users.
Stop enforcing this rule.

overlay: drop check for mount_program AND force_mask

---

pkg/chrootarchive/chroot_linux.go
pkg/unshare/unshare_linux.go

This PR fixes warning deprecated use of `capability.NewPid` (SA1019) found by `golangci` when the `staticcheck` linter is enabled. 
- #1579

Fix deprecated use of `capability.NewPid` (SA1019)

---

pkg/archive/archive.go
pkg/chunked/internal/compression.go

This PR fixes warning deprecated use of `tar.TypeRegA` (SA1019) found by `golangci` when the `staticcheck` linter is enabled. 
- #1579

Fix deprecated use of `tar.TypeRegA` (SA1019)

---

drivers/overlay/overlay.go

check that options != nil before deferencing it.

overlay: check for options != nil

---

drivers/overlay/overlay.go

This PR fixes `the surrounding loop is unconditionally terminated` warning (SA4004) found by `golangci` when the `staticcheck` linter is enabled. 
- #1579

Fix the surrounding loop is unconditionally terminated (SA4004)

---

pkg/chunked/filesystem_linux_test.go

This PR fixes the `TestSafeLink` test which fails on ARM64. 
The failing test: 
```
--- FAIL: TestSafeLink (0.00s)
filesystem_linux_test.go:176: 
Error Trace:	/root/projects/containers/storage/pkg/chunked/filesystem_linux_test.go:176
Error:      	Not equal: 
expected: uint32(0x2)
actual  : uint64(0x2)
Test:       	TestSafeLink 
```
This is because the [Stat_t](https://pkg.go.dev/syscall#Stat_t) structure has different data types, see [arm version](https://fuchsia.googlesource.com/third_party/go/+/main/src/syscall/ztypes_linux_arm64.go#105). The same problem is solved in the function [`getNlink()`](https://github.com/containers/storage/blob/main/pkg/archive/archive_unix_test.go#L156).

Fix `TestSafeLink` on ARM64

---

pkg/archive/archive.go
pkg/archive/archive_linux.go
pkg/archive/archive_unix_test.go
pkg/chunked/compressor/compressor.go

This PR fixes warning deprecated use of `hdr.Xattrs` (SA1019) found by `golangci` when the `staticcheck` linter is enabled. 
- #1579

Fix deprecated use of `hdr.Xattrs` (SA1019)

---

pkg/chunked/compressor/compressor.go

do not specify the timestamps fields in the TOC if they are empty.

chunked: skip setting time if empty

---

tests/apply-junk.bats

This PR moves `junkfile` to the `${TESTDIR}` directory. The `junkfile` is generated during `bats` tests in the `tests` directory. Moving the `junkfile` to the `${TESTDIR}` directory avoids unintended writing this file to the git history.

Move `junkfile` to `${TESTDIR}` directory

---

.golangci.yml

This PR enables `staticcheck` linter and fixes not-allowed properties of the `Golangci-lint` config. 
- #1579

Enable `staticcheck` linter

---

check.go

mount the image as read-only so it can work also for composefs images.

check: mount layer as read-only

---

drivers/aufs/aufs_test.go
drivers/btrfs/btrfs_test.go
drivers/graphtest/graphbench_unix.go
drivers/graphtest/graphtest_unix.go
drivers/graphtest/testutil.go
drivers/graphtest/testutil_unix.go
pkg/chunked/cache_linux.go

This PR is one of several fixes of warnings found by `golangci` when the `errcheck` linter is enabled. 
- #1579

Solve `errcheck` warnings (part 2)

---

drivers/aufs/aufs.go
drivers/overlay/overlay.go
pkg/chunked/bloom_filter_linux_test.go
pkg/chunked/filesystem_linux.go
pkg/chunked/storage_linux.go

This PR is one of several fixes of warnings found by `golangci` when the `errcheck` linter is enabled. 
- #1579

Solve `errcheck` warnings (part 4)

---

pkg/fileutils/exists_test.go
pkg/idmap/idmapped_utils.go
pkg/unshare/unshare_linux.go
types/utils.go

This PR is one of several fixes of warnings found by `golangci` when the `errcheck` linter is enabled. 
- #1579

Solve `errcheck` warnings (part 0)

---

drivers/aufs/aufs.go
drivers/aufs/aufs_test.go
pkg/chrootarchive/archive_unix.go

This PR is one of several fixes of warnings found by `golangci` when the `errcheck` linter is enabled. 
- #1579

Solve `errcheck` warnings (part 3)

---

drivers/driver.go
layers.go
pkg/chunked/storage_linux.go

if the compressed digest was validated, as it happens when 'pull_options = {convert_images = "true"}' is set, then store it as well so that reusing the blob by its compressed digest works.
Previously, when an image converted to zstd:chunked was pulled a second time, it would not be recognized by its compressed digest, resulting in the need to re-pull the image again.

chunked: store compressed digest if validated

---

store.go

Instead of making a copy with some fields, pass the ~deep copy of options we are already using with all of them.
Originally motivated by a linter pointing out that the copy of `options.BigData` has no readers.
In some cases it's not entirely clear that we intended the fields to be a public API; at least I can't see any external caller of any of these fields. But now that they _are_ a public API, we can either implement it, or mark the fields as deprecated ... and then we would need to introduce an internal option structure to carry the fields for the call paths where we do want these fields. That's possible but more work, so I'm doing the lazy thing.
@giuseppe @nalind PTAL

Don't discard fields of `LayerOptions`

---

check.go
pkg/chrootarchive/archive_darwin.go
pkg/chunked/filesystem_linux.go
pkg/chunked/filesystem_linux_test.go
pkg/chunked/storage_linux.go
pkg/fileutils/exists_test.go
types/options.go
types/options_bsd.go
types/options_darwin.go
types/options_linux.go
types/options_test.go
types/options_windows.go

from what `golangci-lint` and `gopls check` show. This is not comprehensive, primarily to minimize distractions when working on pkg/chunked.
Cc: @giuseppe primarily for a review of the `context.Context` removals.

Clean up some warnings

---

drivers/aufs/aufs.go
drivers/overlay/overlay.go

drop an expensive call to "modprobe" each time we initialize the storage.  The kernel already tries to automatically load the module if needed, and still the user has the possibility to load the module manually if required.
Alternative fix for: https://github.com/containers/storage/pull/2019

drivers: drop modprobe calls

---

pkg/archive/filter.go

if there is an error reading from the input stream, prefer to report it instead of the error from the filter program itself.
We have a test in the buildah CI that expects the "no space left on device" error that comes from the input stream, to avoid changing the test, just fix it here.
Reported here: https://github.com/containers/buildah/pull/5585

archive: report error from input stream

---

pkg/archive/filter.go

follow-up for https://github.com/containers/storage/pull/2012
report the error as seen by the input stream, instead of attempting another read.
Closes: https://github.com/containers/storage/issues/2022

archive: improve filter error reporting

---

pkg/chunked/dump/dump.go
pkg/chunked/dump/dump_test.go

the value of the xattrs is encoded in base64, so decode them before passing the value to the mkcomposefs tool.

chunked, composefs: fix decoding of xattrs

---

pkg/chunked/cache_linux.go

if the layer is R/O, do not write a cache file.

chunked: do not write cache file to RO store

---

drivers/overlay/overlay.go
store.go

use a private "merged" directory when mounting from an additional store.
Operations like "Diff()" and "Changes()" cause an implicit mount when the naive differ is used.
The issue was not observed earlier because native overlay can achieve these operations without using a mount.
Since these mounts are performed read-only, and overlay supports multiple mounts using the same lowerdirs, use a private location for the "merged" directory.  The location is owned by the current writeable store, that is locked for writing.
Closes: https://github.com/containers/storage/issues/2033

overlay: use private merged directory for AIS

---

pkg/loopback/attach_loopback.go
pkg/loopback/attach_test.go

the loopback device file could be already used/removed by another process.  Since the process is inherently racy, just grab the next available index and try again until it succeeds.
Closes: https://github.com/containers/storage/issues/2038

loopback: fix race condition opening loopback device

---

drivers/overlay/overlay.go
pkg/archive/changes_linux.go

Motivated by https://github.com/containers/storage/issues/2042 where we just get a bare `invalid argument` out of the entire storage stack.
My offhand guess skimming some of the code is by far the most likely thing here is the raw `lgetxattr` call. It'd be useful to know that for sure.

Add some error context in Changes codepaths

---

drivers/overlay/composefs.go

a couple of cleanups for the composefs backend

composefs: prefer std library functions

---

docs/containers-storage-composefs.md
docs/containers-storage-zstd-chunked.md

These aren't installed yet so they'll just live in the git repository but hopefully we can expand them and use them as a central reference point for "how do I do (zstd:chunked)|(composefs)". We have copies of that kind of instruction in other downstream places but I think here makes the most sense.

docs: Add (not installed) man pages for composefs and zstd:chunked

---

drivers/overlay/composefs.go

the main advantage in this case is that it splits the mount operation in multiple steps, so it is easier (hopefully) to find out what goes wrong.

composefs use new mount api

---

pkg/chrootarchive/archive.go
pkg/chrootarchive/archive_darwin.go
pkg/chrootarchive/archive_unix.go
pkg/chrootarchive/archive_windows.go

I'd like to support passing a file descriptor root for the container storage, and not an absolute path.
In the bootc codebase (partially a philosophy inherited from ostree) we've heavily invested in fd-relative accesses, primarily because it's common for us to operate in different namespaces/roots, and fd-relative access avoids a lot of possible footguns when dealing with absolute paths. It's also more efficient, avoiding the need for the kernel to traverse full paths a lot.
This is just one of a few preparatory changes necessary in making it work to do:
`podman --root=/proc/self/fd/3 --runroot=... pull busybox`
Note that as part of doing this, I refactored code here to move the "split root and dest" logic into the caller... there was some logically dead code here because

chrootarchive: Pass root via fd

---

docs/containers-storage-composefs.md
docs/containers-storage-zstd-chunked.md
storage.conf

The default storage.conf we ship is inconsistent in a few ways; there's a lot of fixes rolled up into this single commit.
First: we were using a toml "inline table" for the pull options, and then documenting each key in that table in one blob above. It simply looks much nicer to use a non-inline table - then we can move the docs next to each individual value. This is also more consistent with other sections of the config.
I also thinned out a bit the doc comments; I think instead of trying to have a longer explanation of zstd:chunked in the comments here we should refer to the man page, which is a better place to have details (and that we should fill out more).
Per another PR, I also stumbled across the fact that we have a lot of "string bool" values and cannot be native TOML booleans. …

storage.conf: Various cleanups

---

drivers/overlay/composefs.go
drivers/overlay/overlay.go
drivers/overlay/overlay_nocgo.go

some improvements for composefs, more details in each patch

composefs fixes

---

pkg/fileutils/exists_freebsd.go

The faccessat system call does not support AT_SYMLINK_NOFOLLOW on FreeBSD versions before 15.0. This works around the limitation by falling back to os.Lstat if faccessat returns an EINVAL error.
I tested this on FreeBSD 14.x hosts using 'go test ./pkg/fileutils' as well as on a 15.0 prerelease host to verify that faccessat behaves as expected in 15.0.

pkg/fileutils: fix Lexists on FreeBSD

---

pkg/fileutils/exists_freebsd.go

The previous attempt worked with 'podman image load' but not 'podman image save' since the error returned from Lexists for non-existent files was not recognized by os.IsNotExist. This version returns well-formed errors for non-existent files and works with both 'podman image load' and 'podman image save'.

pkg/fileutils: fix Lexists on FreeBSD (second attempt)

---

docs/containers-storage-composefs.md
docs/containers-storage-zstd-chunked.md

I've been reading more of the code and looking
at the filesystem in these modes.

docs: Fill in more about composefs and zstd:chunked

---

docs/containers-storage.conf.5.md
storage.conf

xref https://github.com/containers/storage/pull/2065#issuecomment-2313002081
This does the same for the man page that I did for the default storage.conf previously; instead of trying to squash all the `pull_options` into a single option that we document "ad-hoc", make it its own table just like the other sections.
- Add notes about "string bools" around relevant values.
- Avoid redundantly specifying the default; the default is the first thing we show after the `=`.
Synchronize the text between the man page and the default `storage.conf`.

Sync man page with storage.conf

---

drivers/overlay/overlay.go

ignore EINVAL for unmount in the cleanup function as it means the directory is not a mount point.  It can happen if the cleanup happens before the mount point is created.

overlay: ignore EINVAL for cleanup unmount

---

pkg/chunked/cache_linux.go

A follow-up to https://github.com/containers/storage/pull/2031 .

Be explicit about impact of not writing caches

---

pkg/directory/directory_unix.go
pkg/directory/directory_windows.go

As documented in (fs.DirEntry) Info() it can return ENOENT so we must ignore it there as well. Reported in
https://github.com/containers/podman/issues/23909
Given this is a race I don't think I can add a test here.

pkg/directory: correctly ignore ENOENT while walking

---

check.go
cmd/containers-storage/copy.go
drivers/overlay/mount.go
drivers/windows/windows.go
internal/opts/opts.go
internal/opts/parse.go
pkg/archive/archive_linux.go
pkg/archive/changes.go
pkg/archive/fflags_bsd.go
pkg/mflag/flag.go
pkg/mount/flags.go
pkg/mount/mounter_freebsd.go
pkg/mount/mounter_linux_test.go
pkg/parsers/kernel/kernel_darwin.go
pkg/parsers/operatingsystem/operatingsystem_linux.go
pkg/parsers/parsers.go
types/options.go

In some places, using `strings.Cut` (available since Go 1.18) instead of
`strings.SplitN` allows for simpler more readable code.
Similarly, using `strings.CutPrefix` and `strings.CutSuffix` (available since Go 1.20)
instead of their `strings.Has*` counterparts allows for simpler code.

Use strings.Cut{,Prefix,Suffix} where appropriate

---

userns.go
userns_test.go

the alpine image defines a "nogroup":
$ podman run --rm alpine grep nogroup /etc/group
nogroup:x:65533:
ignore it as we are already doing for the "nobody" user.

userns: skip "nogroup"

---

drivers/overlay/overlay.go

if the overlay data only layers feature is not available, then use a regular overlay lower layer.
The same functionality is already present in the mount helper for composefs.

overlay: fallback without data only layers

---

pkg/chunked/cache_linux.go

ignore the error if the layer is being deleted while we are processing it without a lock on the store.

chunked: ignore ErrLayerUnknown when creating cache

---

pkg/chunked/storage.go
pkg/chunked/storage_linux.go

define a new error type so that the caller can determine whether it is safe to ignore the error and retrieve the resource fully.
Closes: https://github.com/containers/storage/issues/2115
the relative patch for containers/image is something like:
```diff
diff --git a/copy/single.go b/copy/single.go
index 324785a8..b7921837 100644
--- a/copy/single.go
+++ b/copy/single.go
@@ -819,8 +819,13 @@ func (ic *imageCopier) copyLayer(ctx context.Context, srcInfo types.BlobInfo, to
logrus.Debugf("Retrieved partial blob %v", srcInfo.Digest)
return true, updatedBlobInfoFromUpload(srcInfo, uploadedBlob), nil
}
-			logrus.Debugf("Failed to retrieve partial blob: %v", err)
-			return false, types.BlobInfo{}, nil
+			// On a "partial content not available" error, ignore it and retrieve the whole layer.
+ …
```

chunked: define error for partial pulls not available

---

hack/git-validation.sh

This PR fixes `git-validation.sh`, failing in Cirrus CI. The problem was caused by the missing `main` branch. Cirrus CI performs a clone of a single branch with full Git history and no tags. 
Fixes: #2067

CI: Fix `git-validation.sh`

---

drivers/quota/projectquota_supported.go

This PR reverts #1921 which completely removed the PROJINHERIT flag from our quota support. That did not actually fix the problem, it just papered over a few of the cracks. The actual problem is that configuring quota support on the system using our recommended commands sets the PROJINHERIT flag on the top-level directory in some (but not all, for unclear reasons?) cases. We set a project ID on the base directory to give us a base value for subsequent ID assignments, but if the base directory has PROJINHERIT that base ID prevents us from setting new IDs on any subdirectories. Strip the flag from the top-level directory if present to resolve.
There is a second problem, in that Podman is choosing the wrong directory to assign quotas to, but that must be fixed in Podman after this merges. …

Fix assignment of quota project IDs

---

pkg/chunked/cache_linux.go

readCacheFileFromMemory() returns nil, nil when the version mismatches.  Do not attempt to use the cache if it was not loaded.  Ignoring the layer will ensure that the cache will be recreated with the correct version.

chunked: prevent using an empty cache

---

userns.go
userns_test.go
userns_unsupported.go

We need to read /etc/passwd and /etc/group in the container to get an idea of how many UIDs and GIDs we need to allocate for a user namespace when `--userns=auto` is specified. We were forming paths for these using filepath.Join, which is not safe for paths within a container, resulting in this CVE allowing crafted symlinks in the container to access paths on the host instead.
Addresses CVE-2024-9676

Use securejoin.SecureJoin when forming userns paths

---

.cirrus.yml
userns.go
userns_test.go
userns_unsupported.go

Also drags in a backport of #2105 to make the diff apply cleanly. I don't think there's harm in doing so.

[release-1.55] backport fix for CVE-2026-9676

---

drivers/driver.go
layers.go
pkg/chunked/compression_linux.go
pkg/chunked/compression_linux_test.go
pkg/chunked/storage_linux.go
store.go

The current value obtained by summing the sizes of regular file contents does not match the size of the uncompressed layer tarball.
We don't have a convenient source to compute the correct size for estargz without pulling the full layer and defeating the point.
For recent zstd:chunked images, we have the full tar-split, so we can compute the correct size; <s>for now, this doesn't do that. That might slow down image size computation.</s>
---
<s>Absolutely untested, and we probably do want the tar-split-based computation to happen.</s>

Correctly compute UncompressedSize on zstd:chunked pull, don’t set it on estargz

---

.cirrus.yml
.codespellrc
Makefile
pkg/chunked/cache_linux.go
pkg/idtools/idtools.go

1. Move codespell config out of Makefile, simplify (remove unused stuff).
2. Fix found issues (using `codespell -w`).
3. Add a codespell CI job.

ci: add codespell

---

drivers/overlay/composefs.go

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=fb176750266a3d7f42ebdcf28e8ba40350b27847 adds the possibility to mount a EROFS file system directly from its backing file instead of using a loopback device.

composefs: use mount from file where supported

---

drivers/fsdiff.go

there is no reason to mount the first layer as writeable.  If fixes mounting layers that are in a read-only location like an additional image store, or are backed by composefs.

fsdiff: mount both layers are read-only

---

.cirrus.yml
userns.go
userns_test.go
userns_unsupported.go

This backports #2134 to release-1.51 (with some bugfix patches from Giuseppe to make it apply cleanly). release-1.51 is used by Podman 4.9.x, which we are still supported on F39 for a couple more months.

[release-1.51] Backport CVE-2024-9676 fix

---

drivers/overlay/composefs.go
drivers/overlay/overlay.go

similarly to what we are doing for the merged directory we need to use private directories for the composefs temporary mounts.  Otherwise when the id is in an additional store, we attempt to perform the mount without holding an exclusive lock there.
Could help with https://github.com/containers/storage/issues/2042.  Can't confirm as I wasn't able to find a reproducer yet.
@cgwalters PTAL, another fix for composefs

overlay: use private directory for composefs mounts

---

drivers/copy/copy_linux.go
drivers/copy/copy_test.go

`copy.DirCopy` contains code to create named sockets matching those on the source; however, this operation closes the socket, removing it implicitly from the destination and causing later chown and chmod operations to fail.
This commit creates matching file system nodes directly without opening a socket or invoking the auto-removal semantics of a listener.
- Closes #2113

Update copy.DirCopy to leave sockets in the file system

---

cmd/containers-storage/config.go
docs/containers-storage-config.md
docs/containers-storage.conf.5.md
pkg/chunked/storage_linux.go
storage.conf
tests/apply-diff.bats

Disable partial pulls by default.
Add a helper command to print the library configuration after parsing everything which may be useful for diagnostic purposes.
Update the `apply-diff-from-staging-directory` integration test to call the test helper binary directly, so that the configuration file the test writes won't have its settings overridden by command line options that the `storage()` test helper function adds.
Resolves https://issues.redhat.com/browse/RUN-2335

Disable partial pulls (zstd:chunked) by default

---

drivers/copy/copy_linux.go
drivers/copy/copy_test.go

Backport pull request #2117 to release-1.55.
Update copy.DirCopy to leave sockets in the file system
(cherry picked from commit 960e8dd66ac7f5e1a5f8c3511ecd237128785a40)

Backport pull request #2117 to release-1.55

---

pkg/chunked/compression_linux.go
pkg/chunked/storage_linux.go
pkg/chunked/storage_linux_test.go

rewrite how the result from GetBlobAt is used, to make sure 1) that the streams are always closed, and 2) that any error is processed.
Closes: https://issues.redhat.com/browse/OCPBUGS-43968

chunked: rework GetBlobAt usage

---

.cirrus.yml
contrib/cirrus/setup.sh

replaces https://github.com/containers/storage/pull/2169 as manual changes are needed

cirrus: update CI image to f41

---

pkg/archive/archive.go
pkg/archive/xattr_freebsd.go
pkg/archive/xattr_unix.go
pkg/archive/xattr_unsupported.go
pkg/system/extattr_freebsd.go
pkg/system/extattr_unsupported.go

Closes #2168
This PR implements system call wrappers for `extattr` on FreeBSD, and adds support for unpacking layers with external attributes(`xattr`). The implementation mimics how FreeBSD's linux compatibility layer and BSD tar handles xattr using extattr system calls, while both has some limitations that only two of the namespaces `user` and `system` are supported among the four – the rest, `trusted` and `security` remain unsupported.

add support for unpacking layers with xattrs set on FreeBSD

---

pkg/system/stat_netbsd.go

Identical to openbsd's implementation, but is not included when compiling on netbsd due to using named files rather than build arguments.
This adds a file which is part of the patches (to the `vendor` directory) for the pkgsrc build.

pkg/system: add fromStatT for NetBSD

---

layers.go

In go one should never modify a slice while also iterating over it at the same time. This causes weird side effects as the underlying array elements are shifted around without the range loop index knowing. So if you delete a element the loop will then actually skip the next one and theoretically access out of bounds on the last element which does not panic but rather return the default zero type, nil here which then causes the panic on layer.Flags == nil.
Here is a simple example to show the behavior:
```
func main() {
slice := []int{1, 2, 3, 4, 5, 6, 7, 8, 9}
for _, num := range slice {
if num == 5 {
slice = slices.DeleteFunc(slice, func(n int) bool {
return n == 5
})
}
fmt.Println(num)
}
}
```
The loop will not print 6, but then as last number it prints 0 (the default zero type for an …

store: correctly remove incomplete layers on load.

---

check.go
drivers/overlay/overlay.go
pkg/archive/archive.go
pkg/chunked/storage_linux.go
pkg/chunked/storage_linux_test.go
pkg/idtools/idtools.go
pkg/idtools/idtools_test.go

Closes: https://github.com/containers/storage/issues/2174

archive: store the override xattr with the inode type

---

layers.go

In go one should never modify a slice while also iterating over it at the same time. This causes weird side effects as the underlying array elements are shifted around without the range loop index knowing. So if you delete a element the loop will then actually skip the next one and theoretically access out of bounds on the last element which does not panic but rather return the default zero type, nil here which then causes the panic on layer.Flags == nil.
Here is a simple example to show the behavior:
func main() {
slice := []int{1, 2, 3, 4, 5, 6, 7, 8, 9}
for _, num := range slice {
if num == 5 {
slice = slices.DeleteFunc(slice, func(n int) bool {
return n == 5
})
}
fmt.Println(num)
}
}
The loop will not print 6, but then as last number it prints 0 (the default zero type for an int). …

[release-1.56] store: correctly remove incomplete layers on load.

---

pkg/chunked/dump/dump.go
pkg/chunked/filesystem_linux.go
pkg/chunked/filesystem_linux_test.go
pkg/chunked/internal/path/path.go
pkg/chunked/internal/path/path_test.go
pkg/chunked/storage_linux.go

if the file name is the root directory, do not attempt to use the base component since it is the empty string.
Closes: https://github.com/containers/storage/issues/2191

chunked: handle creating root directory

---

pkg/chunked/cache_linux.go
pkg/chunked/compression.go
pkg/chunked/compression_linux.go
pkg/chunked/compressor/compressor.go
pkg/chunked/dump/dump.go
pkg/chunked/dump/dump_test.go
pkg/chunked/filesystem_linux.go
pkg/chunked/filesystem_linux_test.go
pkg/chunked/internal/minimal/compression.go
pkg/chunked/internal/minimal/compression_test.go
pkg/chunked/storage_linux.go
pkg/chunked/toc/toc.go
pkg/chunked/zstdchunked_test.go

We now have several `internal` subpackages of `pkg/chunked`, so delineate more explicitly the parts that should be kept as small as possible because the c/image compression package depends on them.
Should not change behavior.
---
Previously discussed in https://github.com/containers/storage/pull/2194#discussion_r1881081145 .
I don’t like the `internal/minimal` subpackage name much; I don’t know how to choose a name that both expresses “be careful not to add dependencies here” and that looks good at the call sites (which don’t all care about the minimizing dependencies). Suggestions for an alternative are very welcome.

Move pkg/chunked/internal to pkg/chunked/internal/minimal

---

pkg/archive/archive.go
pkg/archive/changes.go
pkg/archive/changes_linux.go
pkg/archive/changes_test.go

improve detection of changes in symlinks when both the size and the mtime were changed.
Previously, the detection relied on a difference in either size or atime/mtime to identify changes in a symlink.  This is not enough, as the atime/mtime and it size could be left unaltered while only its target changes.
Fixes: https://github.com/containers/buildah/issues/5861

archive: detect symlink target changes

---

drivers/overlay/composefs.go

Linux 6.12 was already released and it supports mounting EROFS through a file.

composefs: fix comment

---

docs/containers-storage.conf.5.md
drivers/driver.go
pkg/chunked/cache_linux.go
pkg/chunked/dump/dump.go
pkg/chunked/dump/dump_test.go
pkg/chunked/internal/path/path.go
pkg/chunked/internal/path/path_test.go
pkg/chunked/storage_linux.go
storage.conf

… to ensure we can always use traditional layer IDs and image IDs, and use the uncompressed digests to avoid zstd:chunked view ambiguity, in c/image.
<s>Absolutely untested.</s>

Compute an uncompressed digest for chunked layers

---

pkg/chunked/storage_unsupported.go

inform the caller to fallback to an ordinary copy when not running on Linux.

chunked: use fallback mechanism on non-linux platforms

---

pkg/chunked/compression_linux.go

We have seen an image with:
- total size 1.43 GB
- uncompressed zstd:chunked manifest size of 91.7 MB
- uncompressed tar-split size (not constrained by maxTocSize) 310 MB
Without more infrastructure, we are just guessing about what the system we are running on can support, so, for now, *shrug*, bump the number.
Eventually we should stream the data from/to disk, making this much less relevant; that makes building the infrastructure to estimate available memory unattractive.
---
Per previous conversation in #2230 . Cc: @giuseppe @TomSweeneyRedHat .

Bump maxTocSize to 150 MB

---

drivers/btrfs/btrfs_test.go
drivers/graphtest/graphbench_unix.go
drivers/graphtest/graphtest_unix.go
drivers/overlay/overlay_test.go
drivers/vfs/vfs_test.go

These are a couple of things I saw when perusing the test code.

Graphdriver test cleanups

---

pkg/archive/archive.go
pkg/archive/changes_test.go
pkg/archive/changes_unix_test.go
pkg/archive/changes_windows_test.go

Unixy systems have Lutimes(), and we should have stubbed it out for non-Unixy systems.

Fix compilation of pkg/archive tests on non-Linux

---

drivers/overlay/overlay.go

I'm hitting this error path in
https://github.com/containers/buildah/issues/5976
and it was not obvious to me which bit of code was failing. Add an error prefix so it's easy to find.

overlay: Add error prefixing for mount.MakePrivate

---

pkg/fileutils/reflink_linux.go
pkg/fileutils/reflink_unsupported.go

Add a function to copy via reflink if possible or fall back to the normal io.Copy().
c/image uses this function internally[1] however I like to export this and use it in podman and I think this package here in c/storage is the most logical location for it. Note compared to the c/image version I am calling unix.IoctlFileClone() directly instead of the raw syscall function.
[1] https://github.com/containers/image/tree/main/internal/reflink

pkg/fileutils: add LinkOrCopy()

---

layers.go
layers_test.go
tests/split-store.bats

when an imagestore is used, a R/O layer must be written to the layers.json under the imagestore, not graphroot.
The lock on the imagestore is already taken through the multipleLockFile{} mechanism in place.
Closes: https://github.com/containers/storage/issues/2257

layers: write read only layers to imagestore

---

pkg/archive/archive.go
pkg/archive/archive_test.go
pkg/archive/changes.go

Allows overriding of timestamps for entries within an archive.
TarOptions already includes a number of other overrides, it seemed like a good place to add this one as well.
(am keen to look at getting `buildah` to have the ability to emit identical tarballs for `oci-archive`, and this is the first step)

feat: add Timestamp to TarOptions

---

drivers/quota/projectquota_supported.go

We have previously relied on the PROJINHERIT flag for XFS quotas, which causes the ID of the parent directory to be recursively applied to subdirectories under the volume's parent directory. However, PROJINHERIT only applies to directories created after the project ID was first set. Pre-existing directories do not get the project ID if we only set it on the parent. This means that quota enforcement is not complete unless we recurse to subdirectories and apply the project ID to those as well.
Fixes https://github.com/containers/podman/issues/25368

Recursively set project ID for quota driver

---

pkg/idmap/idmapped_utils.go

do not leak idmapped mounts to other namespaces, since they are meant to be used privately by overlay.
This is already done with the default configuration, since we have a private mount on top of the graphdriver directory, but it is not the case when `skip_home_mount` is used.
Closes: https://issues.redhat.com/browse/OCPBUGS-49927

idmap: force PRIVATE propagation

---

pkg/loopback/loop_wrapper.go

follow-up for commit eebb044f5607269a434b07bdf4660118432374ac
remove the hardcoded constants and re-use the values defined in the unix package.
@mtrmac PTAL

loop: remove hardcoded constants

---

.cirrus.yml
go.mod

This is a very minimal change, just to handle the version bump.
I intend to let Renovate do the dependency updates.

Update to Go 1.23

---

hack/libsubid_tag.sh
pkg/idtools/idtools_supported.go

the new ABI has been around for more than 3 years now (shadow-utils v4.11).
Closes: https://github.com/containers/storage/issues/2260

subid: drop support for old version

---

CONTRIBUTING.md

This PR adds a link to the updated c/common contributor's guide to reduce the costs of updating the contribution guide and removes duplicate information. 
Question for reviewer: I don't know if the communication part is still valid? If it's deprecated and I can remove it.
Fixes: https://issues.redhat.com/browse/RUN-2321

Add link to c/common contributor's guide

---

pkg/fileutils/exists_unix.go

When the overlay driver (and some others) tries to access the directories for the relevant layers it uses faccessat syscall (in fileutils.Exists() fileutils.Lexists()).
The syscall is missing the AT_EACCESS flag and so permissions to access the files are determined solely on the uid.
This error happens when we run with a user that has the correct capabilities to access the file (e.g cap_dac_override) but the file permissions don't allow the specific user.
This PR adds the AT_EACCESS flag to the faccessat syscall in Exists() and Lexists() functions to ensure that they will be able to verify file existence based on the effective user.
**How to reproduce** (adding a binary to help demonstrate the issue)
Compile this `faccessast_test` program
```
#include <stdio.h>
#include <fcntl.h>
#include …
```

Fix: Overlay fails with a permission error when trying to create and access layers

---

cmd/containers-storage/mount.go
store.go
tests/idmaps.bats

Ensure that a mapped layer with the canonical mapping is created if one doesn't already exist.  Previously, any layer was used regardless of its mapping, which resulted in the mounted image having incorrect file ownership, depending on what mapping was found.

store: use canonical image mapping when mounting

---

.golangci.yml
Makefile
drivers/aufs/aufs.go
drivers/copy/copy_linux.go
drivers/copy/copy_unsupported.go
drivers/driver.go
drivers/overlay/composefs.go
drivers/overlay/overlay.go
internal/dedup/dedup.go
internal/dedup/dedup_linux.go
internal/dedup/dedup_linux_test.go
internal/dedup/dedup_unsupported.go
pkg/archive/archive.go
pkg/archive/changes.go
pkg/archive/changes_linux.go
pkg/archive/changes_test.go
pkg/archive/diff.go
pkg/chunked/storage_linux.go
pkg/idtools/idtools.go
pkg/loopback/attach_loopback.go
pkg/unshare/unshare_linux.go
store.go
types/options.go
types/utils.go

The new configuration file was initially generated by golangci-lint
migrate, when tweaked to minimize and simplify.
golangci-lint v2 switches to a new version of staticcheck which shows
much more warnings. Many of them are fixed here, and the rest
are suppressed. The suppressed ones are:
- -ST1003 # https://staticcheck.dev/docs/checks/#ST1003 Poorly chosen identifier (impractical to change public API)
- -QF1008 # https://staticcheck.dev/docs/checks/#QF1008 Omit embedded fields from selector expression (doesn't really improve code readability)

Switch to golangci-lint v2, fix new warnings

---

drivers/overlay/overlay.go

Seen in podman CI, a map by default in not concurrent safe. As the
driver can be used in parallel by callers we must guard against this
here.
Fixes #2297
--- 
drivers/overlay: use clear() for stagingDirsLocks
That should be more memory efficient as we do not have to allocate a new map.

driver/overlay: fix concurrent map write on stagingDirsLocks

---

pkg/idmap/idmapped_utils.go

0 is a valid file descriptor, to ignore the argument we need to use AT_FDCWD.

idmap: fix first argument to open_tree

---

.cirrus.yml
drivers/overlay/overlay.go
hack/libsubid_tag.sh
pkg/idtools/idtools_supported.go

driver/overlay: inline the mutex in driver
There is no need for the extra pointer indirection. With this Driver can
no longer be copied but that was never supported and now lint should
even catch a copy and warn as copying a Mutex is not allowed.
---
pkg/idtools: fix lint gofumpt error
CI doesn't seem to cover the libsubid build tag.
---
CI: add libsubid to lint task
This should ensure we run lint with the libsubid build tag.
Now this is not perfect either, as we do not cover the !libsubid but
that is only one single simple file.

fix minor review comment about the driver mutex and a minor lint issue

---

types/options.go

When running as non-root, the code previously checked if usePerUserStorage() before applying default paths for RunRoot and GraphRoot if they were missing from the configuration file. This check prevented defaults from being applied if the STORAGE_DRIVER environment variable was set.
Do not merge before https://github.com/containers/common/pull/2420

types: Always apply rootless path defaults

---

drivers/driver.go
layers.go
pkg/chunked/compression_linux.go
pkg/chunked/compression_linux_test.go
pkg/chunked/storage_linux.go
pkg/chunked/zstdchunked_test.go

Replace the in-memory buffer with a O_TMPFILE file.  This reduces the memory requirements for a partial pull since the tar-split data can be written to disk.
c/image needs the following patch:
```
diff --git a/storage/storage_dest.go b/storage/storage_dest.go
index d1c5acef..e66e0ccc 100644
--- a/storage/storage_dest.go
+++ b/storage/storage_dest.go
@@ -425,6 +425,7 @@ func (s *storageImageDestination) PutBlobPartial(ctx context.Context, chunkAcces
if err != nil {
return private.UploadedBlob{}, err
}
+	defer differ.Close()
out, err := s.imageRef.transport.store.PrepareStagedLayer(nil, differ)
if err != nil {
```

chunked: use temporary file for tar-split data

---

drivers/overlay/overlay.go

The `fsMagic` parameter was not used within the
`checkAndRecordOverlaySupport` and `supportsOverlay` functions.

overlay: drop unused fsMagic from support checks

---

drivers/aufs/aufs.go
drivers/chown.go
drivers/driver.go
drivers/overlay/overlay.go
drivers/overlay/overlay_test.go
drivers/vfs/driver.go
drivers/windows/windows.go
layers.go
store.go

move the check for a contiguous mapping to overlay when a mount program is specified, since this is required only for fuse-overlayfs, not native idmapped mounts.
Closes: https://issues.redhat.com/browse/RHEL-94967
Closes: https://github.com/containers/storage/issues/2345

scope contiguity checks for idmap to mountProgram presence

---

pkg/archive/archive.go
pkg/archive/archive_unix_test.go

When examining a file that we're adding to an archive to see if it's hard linked to another file that's already been written, or to one that might be written later, only set an entry in the inode->name map that points to the entry we're writing for the first file.  This keeps us from writing tar headers with Typeflag==TypeLink and a Linkname that points to another entry with Typeflag==TypeLink in cases where the inode has more than two names.
Fixes https://github.com/containers/buildah/issues/6297.

pkg/archive.tarWriter.addFile(): don't change hardlink targets

---

.github/workflows/auto-close-prs.yml
README.md
go.mod

This commit:
- mentions the monorepo in the README.MD.
- deprecates the module in favor of go.podman.io/storage.
- adds github workflow to auto-close newly created PRs.

Move the repository to monorepo.
