containers/storage

.tool/lint
Makefile

This gives us a starting point to fix the lint errors.
@nalind @runcom @rhatdan PTAL
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

Add support for lint

---

storage/store.go

Comments in https://github.com/kubernetes-incubator/cri-o/pull/189 suggest renaming these.

Revise based on cri-o review comments

---

Makefile
storage/layers.go
storage/store.go

- Fix the .gitvalidation makefile target for cases where Travis is running for a pull request.
- Fix some lint errors.

Travis fixups

---

.travis.yml

Have Travis build the "cross" target, too.

Add cross target to Travis config

---

layers.go

We don't do anything with these variables, and they break additionalstores

Remove parentlayers lookup.

---

store.go

Lots of cut and pasted code that ends up doing nothing, but takes time
to process.

Remove layer,image, container code that is not used

---

docs/storage.conf.5.md
storage.conf
store.go
vendor.conf
vendor/github.com/BurntSushi/toml/COPYING
vendor/github.com/BurntSushi/toml/README.md
vendor/github.com/BurntSushi/toml/decode.go
vendor/github.com/BurntSushi/toml/decode_meta.go
vendor/github.com/BurntSushi/toml/doc.go
vendor/github.com/BurntSushi/toml/encode.go
vendor/github.com/BurntSushi/toml/encoding_types.go
vendor/github.com/BurntSushi/toml/encoding_types_1.1.go
vendor/github.com/BurntSushi/toml/lex.go
vendor/github.com/BurntSushi/toml/parse.go
vendor/github.com/BurntSushi/toml/type_check.go
vendor/github.com/BurntSushi/toml/type_fields.go

Container Storage is going to be shared by multiple tools.  Therefore
we don't want each one of these tools setting up its own container
storage.  This storage config can be shared between multiple users.

Add support for a toml config file

---

store.go

So don't use it and take locks out on it.

We are not using rlstore in SetBigImageStore

---

store.go
vendor.conf
vendor/github.com/pkg/errors/LICENSE
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/stack.go

We need to inform user what object is using a layer when returning and
error.

Add better error reporting when layers are in use

---

store.go

In order to get ROLayers to merge, we need to break
some functions into smaller subsets to not hold the locks long.

Add new function to return ContainerLayerID

---

drivers/overlay/overlay.go
store.go

We are now allowing users to specify additional container storage directories in the
configuration.  We need to create a roLayer and roImage object for each additional
storage driver.  These stores are treated as reaonly.

Support for additional roLayers and roImages

---

containers.go
images.go
layers.go

We don't need these Touch calls, since the Save function will handle it.

Uneccessary Touch functions.

---

pkg/loopback/attach_loopback.go

After attaching a loopback device to a backing file, compare the loopback driver's idea of the backing file's device and inode numbers against the numbers we get back from stat().  If they differ, log an
error, but continue.
This should help diagnose some problems that can pop up, for example, when we try to resume use of a thin pool built on top of loopback files which live on a union filesystem that returns synthesized values in
stat() results.

Check for loopback device/inode mismatches

---

drivers/overlay/overlay.go

Accept "overlay2.imagestore" as a synonym for the "overlay.imagestore" option, and be a bit more consistent about using the driver name we were invoked by in error messages.

Accept "overlay2.imagestore" as a synonym for the "overlay.imagestore" option

---

cmd/containers-storage/create.go
cmd/containers-storage/layer.go
cmd/containers-storage/main.go
cmd/containers-storage/status.go
docs/containers-storage-container.md
docs/containers-storage-image.md
docs/containers-storage-layer.md

Add a CLI command for displaying information about a layer, and clean up some weird formatting in other parts of the CLI output.

Add a "layer" command to the CLI

---

cmd/containers-storage/container.go
cmd/containers-storage/image.go
cmd/containers-storage/main.go
containers.go
docs/containers-storage-get-container-data-digest.md
docs/containers-storage-get-container-data-size.md
docs/containers-storage-get-container-data.md
docs/containers-storage-get-image-data-digest.md
docs/containers-storage-get-image-data-size.md
docs/containers-storage-get-image-data.md
docs/containers-storage-list-container-data.md
docs/containers-storage-list-image-data.md
docs/containers-storage-set-container-data.md
docs/containers-storage-set-image-data.md
errors.go
images.go
store.go

Teach image and container store types to also track the digests of "big data" items that we have them store.

Track the digests of big data items

---

store.go

When we try to Store.Put() a new layer, also check read-only layer stores as part of verifying that the new layer's parent is known.

Check read-only stores when Putting new layers

---

Makefile
drivers/vfs/driver.go
tests/apply-diff.bats
tests/bigdata.bats
tests/changes.bats
tests/container-dirs.bats
tests/container.bats
tests/create-container.bats
tests/create-image.bats
tests/create-layer.bats
tests/delete-container.bats
tests/delete-image.bats
tests/delete-layer.bats
tests/delete.bats
tests/diff.bats
tests/diffsize.bats
tests/helpers.bash
tests/image.bats
tests/import-layer.bats
tests/metadata.bats
tests/names.bats
tests/status.bats
tests/stores.bats
tests/test_drivers.bash
tests/test_runner.bash

This adds some integration tests for exercising the higher-level APIs by way of using the CLI helper.  We add read-only store support to the "vfs" driver to let us always test that option, too.

Add some integration tests

---

drivers/overlay/overlay.go

overlay: fix typo in debug message

---

drivers/overlay/overlay.go

When an overlay layer has no parent, "mounting" it is just a no-op, since we're using its "diff" directory directly, and we didn't bother to create a "merged" directory for the layer.  Check for this case when we
go to unmount the layer's "merged" directory, to avoid a spurious "not mounted" error.

overlay: avoid bogus error unmounting base layers

---

vendor.conf
vendor/github.com/vbatts/tar-split/tar/asm/disassemble.go

Fixes: CVE-2017-1499
reference https://github.com/vbatts/tar-split/pull/42

vendor: update tar-split to v1.0.2 release

---

pkg/truncindex/truncindex.go
pkg/truncindex/truncindex_test.go

Update to match latest code in moby

---

drivers/overlay/overlay.go

Always mount an overlay filesystem, even when there's no parent layer, so that we can set an SELinux context for the mountpoints.  We create an "empty" directory to use as the lower directory for the overlay mount to satisfy the kernel, but as it's not a real layer, we don't track it in the lists of lower directories.

overlay: always mount, even if we have no parent layer

---

docs/containers-storage.conf.5.md
storage.conf

Need to document the devicemapper changes.

Fix up containers-storage.conf man page for devicemapper options

---

drivers/chown.go
drivers/chown_unix.go
drivers/chown_windows.go
drivers/chroot_windows.go

drivers: cross-platform chown

---

README.md

Potential contributors need to find the CONTRIBUTOR information.

---

drivers/chown_unix.go

When we chown we not only loose the setuid flags but we also loose
the file capabilties.  This means in a user namespace when we chown
ping, it looses its filecap, which means it will not longer work.
This fix will check for the security capabilies and retain them if they
exist when chowning.

Need to preserve the Xattr security.capability when chowning.

---

drivers/windows/windows.go

Fix handling of mountlabel for windows driver

---

drivers/overlay/overlay.go

Closes: https://github.com/containers/storage/issues/221

overlay: don't check backing fs when using a mount program

---

drivers/overlay/overlay.go

overlay: force naiveDiff when using a mount program

---

hack/spc_ci_test.sh

ci: run apt-get update

---

drivers/aufs/aufs.go
store.go

Add missing parameters to errors.Wrapf

---

layers.go

Unused since 1f7a56c869614f632d22e750857293de5153f7b2
Signed-off-by: Šimon Lukašík <isimluk@fedoraproject.org>

Remove unused variable: compressionFlag

---

pkg/archive/archive.go

old kernels, such as 4.9 used by Debian 9 do not support extended
attributes in a user namespace.  In this case, ignore the error and
print a warning.  This should be fine, as we are already doing it for
file systems that do not support xattrs.
Closes: https://github.com/containers/libpod/issues/1941

archive: ignore setxattr EPERM in a user namespace

---

drivers/overlay/overlay.go

when detecting if the overlay driver can be used a temporary file is
created.  if the system is ENOSPC, that fails but the error message
response was misleading.  this patch makes the error message in that
case more obvious.
Signed-off-by: baude <bbaude@redhat.com>

handle ENOSPC for overlay driver

---

drivers/overlay/check.go
drivers/overlay/overlay.go

In the overlay driver, check if metacopy is enabled, and report it along with other status information.

overlay: check if metacopy is happening

---

drivers/overlay/overlay.go

Signed-off-by: Giuseppe Scrivano <giuseppe@scrivano.org>

overlay: do not attempt metacopyup when using a mount program

---

vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go

vndr opencontainers/selinux

---

lockfile_test.go
lockfile_unix.go
pkg/testutil/pkg.go

These aren't exhaustive, but they're something.

lockfile: add some unit tests, don't return ENOSPC from Modified()

---

docs/containers-storage.conf.5.md

Add documentation about SELinux labeling

---

lockfile.go
lockfile_unix.go
lockfile_windows.go

See the individual commit messages for details.

Lock file cleanups, notably getLockfile vs. getLockFile naming

---

pkg/idtools/parser.go

This commit fixes a possible integer overflow during U/GID map parsing.
Casting a 32bit unsigned integer to the resulting IDMap will now be
guarded by a simple overflow check. This check does apply to all
target architectures.
Closes #316

Fix possible integer overflow on 32bit builds

---

store.go
tests/stores.bats

When you build an image with a parent layer in read-only stores
and the new image in read/write stores, the first time you try
to create a container based on the image, it fails, since it
cannot find the image in the same store.
This patch looks not only in the same store, but all of the stores
available.

Fix handling of additional stores

---

drivers/overlay/overlay.go
drivers/vfs/driver.go

Add a couple of quick compilation fixes.

Compilation fixes

---

cmd/containers-storage/container.go
drivers/aufs/aufs.go
drivers/btrfs/btrfs.go
drivers/devmapper/driver.go
drivers/driver.go
drivers/overlay/overlay.go
drivers/vfs/driver.go
drivers/zfs/zfs.go
store.go

This reverts commit e9695564db67450523b96e2ac2fb591e74df223f.

Revert "Add MountTempFromSource and RemoveTemp interfaces"

---

docs/containers-storage.conf.5.md

Small fixes in the manpage for `containers-storage.conf`.
Signed-off-by: Silvano Cirujano Cuesta <silvano.cirujano-cuesta@siemens.com>

docs: fix manpage for containers-storage.conf

---

.cirrus.yml
contrib/cirrus/build.sh
contrib/cirrus/integration.sh
contrib/cirrus/lib.sh
contrib/cirrus/lib.sh.t
contrib/cirrus/setup.sh
contrib/cirrus/timestamp.awk
contrib/cirrus/unit.sh

Cirrus: Add initial support for Cirrus-CI

---

contrib/cirrus/lib.sh
contrib/cirrus/setup.sh

cirrus: Add retry/timeout function for apt-get

---

.gitignore
hack/get_ci_vm.sh

Cirrus: Script to manually prov. CI-like VMs

---

.cirrus.yml
contrib/cirrus/build.sh
contrib/cirrus/lib.sh
contrib/cirrus/ooe.sh
contrib/cirrus/setup.sh
contrib/cirrus/unit.sh
drivers/aufs/aufs.go

Hook up regular tests to run on fedora/ubuntu natively.

Start implementing testing in cirrus

---

contrib/cirrus/build.sh
contrib/cirrus/lib.sh

Add test for fuse-overlay without mknod

---

Makefile
contrib/cirrus/build_and_test.sh
pkg/chrootarchive/chroot_unix.go

cirrus: check cross-compilation

---

.cirrus.yml

This should add a vendoring check to cirrus CI.

Add cirrus vendor check

---

Makefile

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

allow custom Go binary

---

pkg/idtools/idtools.go

Don't chown on safechown if directory exists and has correct ownership 

---

drivers/overlay/overlay.go

Don't report IsNotExists errors, when unmounting

---

pkg/system/stat_linux.go

Fix suggesed by Dmitry Smirnov @onlyjob

Need this fix to allow builds on mipsel

---

pkg/loopback/attach_loopback.go
pkg/loopback/loopback.go

Fixes: https://github.com/containers/storage/issues/475

Fix compile on mipsel

---

pkg/tarlog/tarlogger.go

detect when the read pipe got closed by using the Write error code.
It solves a race, where the pipe could be closed between the check and
the actual write.

tarlogger: drop state mutex

---

store.go

This solves a race condition where a mountpoint is created without the
home mount being present.
The cause is that another process could be calling the graph driver
cleanup as part of store.Shutdown() causing the unmount of the
driver home directory.
The unmount could happen between the time the rlstore is retrieved and
the actual mount, causing the driver mount to be done without a home
mount below it.
A third process then would re-create again the home mount, shadowing
the previous mount.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1757845

store: keep graph lock during Mount

---

layers.go

There are cases where the storage database gets out of whack with
whether or not the storage is actually mounted.  We need to check
before returning the mount point.
1 A user could go in and umount the storage.
2 If the storage was mounted in a different mount namespace and then
the mount namespace goes away the counter will never get decremented
even though the mount point was removed.
3. If storage runtime is on non tmpfs storage a system reboot could be
done that will not clear the mount count.
This patch will fix the problem with the layer not being mounted, but
we still have a problem in that we can't figure out when to umount the
image. Not sure that is a solveable problem.

Check if the layer is actually mounted.

---

store.go

Fixes https://github.com/containers/storage/issues/544

Fix handling of graphdriver options.

---

store.go

the operations have no dependency on each other so they can be
performed in parallel.

store: make DeleteContainer parallel

---

pkg/fileutils/fileutils_test.go
pkg/mount/mount_unix_test.go
pkg/mount/sharedsubtree_linux_test.go
pkg/reexec/reexec_test.go
pkg/system/chtimes_test.go
pkg/system/chtimes_unix_test.go
pkg/system/process_unix.go
pkg/system/rm.go
pkg/system/stat_unix_test.go

Check lots of potential error situations.

Make linters happy

---

utils.go

when running as rootless, do not write the default storage.conf file.
Follow the same pattern used for libpod.conf.
Closes: https://github.com/containers/libpod/issues/5500

utils: do not write default storage.conf

---

tests/tools/Makefile

Update the linter to the latest version

Update golangci lint to v1.24.0

---

drivers/zfs/zfs.go

fixes #602
Signed-off-by: Steven Armstrong <steven.armstrong@id.ethz.ch>

only chown when mounting read write on zfs

---

pkg/ioutils/fswriters.go

permit users of AtomicFileWriter to disable the fdatasync call that is
performed after the file is written.  CRI-O in particular, completely
wipes out the storage on an not clean system restart, so there is no
gain in syncing files.

ioutils/writer: allow to disable fsync

---

userns.go

Coverity found an issue with copy and pasted code

---

pkg/lockfile/lockfile_unix.go

This will make them easier to consule for additional stores

Make lock files world readable

---

drivers/devmapper/device_setup.go

LVM allows creating a PV on top of an LV, but resolving symlinks
before checking the output of lvmdiskscan erroneously reports that an
LV is not an available device. It will resolve an LV's name into
/dev/dm-NN, which won't show up in lvmdiskscan.
Instead this patch looks for both names in lvmdiskscan.
The motivation for this was to allow using an LV instead of a whole PV as the backing device for the devicemapper driver.

devmapper: allow devmapper devices as directlvm device

---

pkg/archive/archive.go

We have been asked to also record the security.ima attributes into
the container images.
Fixes: https://github.com/containers/buildah/issues/2127

Record security.ima in container images

---

cmd/containers-storage/create.go
cmd/containers-storage/delete.go
cmd/containers-storage/mount.go
hack/git-validation.sh
store.go
utils.go

Interface added to mount image rootfs without any container.
image can be mounted only in ReadOnly mode.
Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>

new interface for MountImage added

---

internal/opts/opts.go

We want to remove insensitive terms from the codebase.

Remove whitelist and replace with allowed

---

pkg/archive/changes_unix.go
pkg/unshare/unshare.c

Fix leaked fd

---

userns.go
userns_test.go

issue found while testing: https://github.com/cri-o/cri-o/pull/3944

userns: fix host id calculation when ranges overlap

---

drivers/copy/copy_linux.go

Coverity found this dead code.

Remove dead code

---

store.go

Related to: #693
Signed-off-by: Jeff Zvier <zvier20@gmail.com>

recover use graphLock when mount a layer

---

.cirrus.yml
go.mod
vendor/modules.txt

We now use the latest golang release images for the CI.

Switch to golang 1.15

---

drivers/counter.go

As the title says - we need this in the stable branch used by Podman v2.0

Cherry-pick #698 into v1.20-stable

---

utils.go

Since this is late in the game, it is too risky to add all system options.
We know that this is supposed to work for HPC customers, so we can just
grab this setting if set in system wide settings.
We can put the full fix into the master branch, and continue to test it
going forward.

For podman v2.0 we need to use use ignore_chown_errors field if set

---

utils_test.go

Signed-off-by: Reinhard Tartler <siretart@gmail.com>

utils_test.go: make test show mismatching items

---

contrib/cirrus/lib.sh
docs/containers-storage.conf.5.md
drivers/btrfs/btrfs.go
drivers/overlay/overlay.go
hack/get_ci_vm.sh
internal/opts/opts_test.go
internal/opts/opts_windows.go
pkg/devicemapper/devmapper_log.go
pkg/fileutils/fileutils.go
pkg/mflag/example/example.go
pkg/mount/mount.go
pkg/stringutils/stringutils_test.go
storage.conf
tests/test_runner.bash

Fix problems found by codespell

---

docs/containers-storage.conf.5.md
storage.conf

Add more information on force_mask

---

.cirrus.yml
contrib/cirrus/build_and_test.sh
contrib/cirrus/lib.sh
contrib/cirrus/setup.sh

Also adjust task-names for improved readability.

Cirrus: Update VM Images

---

contrib/cirrus/lib.sh

Fix errors about undefined storage driver in vms

---

.cirrus.yml
contrib/cirrus/lib.sh
contrib/cirrus/setup.sh

These images include all packages needed for c/storage testing

Cirrus: Do not update/install packages at runtime

---

drivers/overlay/overlay.go

Add warning about possible storage corruption

---

store.go

(*store).Diff: add missing unlock in error case

---

drivers/copy/copy_linux.go
drivers/copy/copy_test.go
drivers/copy/copy_unsupported.go
pkg/archive/archive.go
pkg/archive/archive_ffjson.go
pkg/archive/archive_linux.go
pkg/archive/archive_other.go
pkg/ioutils/fswriters.go

move some patches from #775 to a new PR to simplify the review process.

support patches to prepare #775

---

drivers/overlay/overlay.go

Linux 5.11 introduced overlay for unprivileged users but it fails when
a SELinux label is specified to the mount.
Add a check in overlay to fallback to fuse-overlayfs when the system
is using SELinux but overlay doesn't support it.

overlay: check selinux label support

---

drivers/overlay/overlay.go

Make sure rootless mounts support the userxattr flag

---

go.mod
go.sum
vendor/github.com/opencontainers/selinux/go-selinux/doc.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
vendor/modules.txt

Update vendor opencontainers/selinux v1.8.1

---

containers.go
images.go
layers.go
store.go

add a new method to reload the store information from the hard disk if
has changed.
Cherry-picked-by: Peter Hunt <pehunt@redhat.com>

[1.24] store: replace Modified+Load with ReloadIfChanged

---

drivers/overlay/check.go

if lgetxattr(..., "user.overlay.metacopy") fails with EOPNOTSUPP, it
means metacopy is not supported for the current user.
Prefer this runtime check instead of testing unshare.IsRootless(), so
that metacopy support will be detected in case it will be enabled in a
user namespace in future.

overlay: check for unix.ENOTSUP

---

containers.go
images.go
layers.go
store.go

add a new method to reload the store information from the hard disk if
has changed.
pick of https://github.com/containers/storage/pull/905
Signed-off-by: Giuseppe Scrivano gscrivan@redhat.com
Cherry-picked-by: Peter Hunt pehunt@redhat.com

[1.20] store: replace Modified+Load with ReloadIfChanged

---

.cirrus.yml
CODE-OF-CONDUCT.md
SECURITY.md
contrib/cirrus/lib.sh

Ref: https://github.com/containers/common/issues/549

[CI:DOCS] Fix docs links due to branch rename

---

layers.go

This helps long running processes like CRI-O to determine changes to the
local storage, while handling corrupted images automatically.
The corresponding fix in [Podman][0] handles corrupt layers by reloading
the image. This does not work for CRI-O, because it will not reload the
storage on subsequent calls of pullImage if no storage modification has
been done.
[0]: https://github.com/containers/podman/pull/10637/commits/b4bd886fcc01c99b1c8aa5800710b1c31bae8ae5
Refers to https://github.com/cri-o/cri-o/pull/5005

Reload layer storage if layers.json got externally modified

---

pkg/chrootarchive/diff_unix.go

Need to check for userns before entering the chroot.

Fix handling of user namespace

---

types/options_test.go
types/storage_broken.conf

Add test for bad entries in storage.conf

---

pkg/archive/archive.go
pkg/archive/archive_unix.go

Creating fifo files while non root should be supported

---

.cirrus.yml

Cirrus: Use fresh VM & Container images

---

types/options_test.go
types/utils.go

Fixes: https://github.com/containers/podman/issues/10187

Follow symlinks if they exists

---

drivers/overlay/overlay.go
layers.go

Add codespell fixes

---

drivers/aufs/aufs.go
drivers/fsdiff.go
drivers/overlay/overlay.go
drivers/overlay/randomid.go
drivers/template.go
layers.go
pkg/archive/archive.go
pkg/fileutils/fileutils_unix.go
pkg/lockfile/lockfile_test.go
pkg/loopback/attach_loopback.go
pkg/loopback/loopback.go
pkg/parsers/kernel/kernel_unix.go
pkg/tarlog/tarlogger.go
pkg/unshare/unshare_linux.go
pkg/unshare/unshare_test.go
types/utils.go
userns.go

Standardize on capatalized logrus messages, and remove stutters

---

.cirrus.yml

.cirrus.yml: bump Fedora version

---

store.go

Backport the fix for https://github.com/containers/storage/pull/1037 to
the release-1.37 branch so that it can then be backported to Podman's
v3.4.2-rhel branch for RHEL 8.5.0.2
Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

Backport store: lock graphLock during to 1.37

---

Makefile
pkg/chunked/compression.go

Add flate back in, codespell was too agressive

---

drivers/overlay/overlay.go

- Add missing error handling so that if one `Remove` keeps failing, we don’t loop forever
- As a failsafe (if the filesystem were somehow completely broken), terminate the loop after 10 iterations. (There probably shouldn’t even _need_ to be a loop, but that would be a more invasive and risky change.)
See the individual commit messages for details.
WARNING: Completely untested.

Ensure overlay.Driver.recreateSymlinks does not loop endlessly

---

images.go
store.go

… found by go-staticcheck. Also avoid one other warning.

Fix error handling of a failure to create an image

---

pkg/unshare/unshare_linux.go

Fix codespell errors

---

pkg/system/meminfo_unsupported.go

Fix ReadMemInfo build for FreeBSD + nocgo

---

docs/containers-storage-delete-image.md
docs/containers-storage-get-container-dir.md
docs/containers-storage-get-container-run-dir.md
docs/containers-storage-layer.md
docs/containers-storage-list-layer-data.md
docs/containers-storage.conf.5.md
storage.conf
store.go

Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

fix typos and spelling

---

docs/containers-storage.conf.5.md

Closes https://github.com/containers/storage/issues/1317

docs/containers-storage.conf.5.md: reformat

---

docs/containers-storage.conf.5.md
storage.conf

A recent typo fix introduced a typo.

Revert incorrect "heeded" -> "needed" typo fix

---

pkg/homedir/homedir_unix.go

Partial Fix for containers#14606

Eval symlinks on XDG_RUNTIME_DIR

---

layers.go
store.go

… just to reduce the size of my branches a bit.
See individual commit messages for details. I’d be happy to split this into two PRs if desired.

Two misc. cleanups

---

docs/containers-storage.conf.5.md

While reading the manpage I found this minor typo at the bottom :-)

Fix minor typo on  containers-storage.conf.5.md

---

drivers/overlay/idmapped_utils.go

the two arguments to clone are swapped on s390x. This patch fixes the call when running on s390x.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2108887
Cherry-picked from https://github.com/containers/storage/pull/1418.

[release-1.43] overlay: fix call to clone on s390x

---

pkg/lockfile/lockfile.go

docs: fix fcn name ref for `AssertLockedForWriting`

---

cmd/containers-storage/gc.go
containers.go
docs/containers-storage-gc.md
images.go
layers.go
store.go

Add a GarbageCollect() method to image stores, and call it from the main Store.GarbageCollect().

imageStore: add a GarbageCollect() method

---

drivers/overlay/check.go
drivers/overlay/overlay.go
pkg/idmap/idmapped_utils.go

move the idmap utils from the overlay driver to a separate package.

idmap: new package

---

cmd/containers-storage/container.go
cmd/containers-storage/containers.go
cmd/containers-storage/copy.go
cmd/containers-storage/create.go
cmd/containers-storage/delete.go
cmd/containers-storage/exists.go
cmd/containers-storage/image.go
cmd/containers-storage/images.go
cmd/containers-storage/layer.go
cmd/containers-storage/layers.go
cmd/containers-storage/main.go
cmd/containers-storage/metadata.go
cmd/containers-storage/mount.go
cmd/containers-storage/name.go
cmd/containers-storage/shutdown.go
cmd/containers-storage/status.go
cmd/containers-storage/version.go
cmd/containers-storage/wipe.go

We do have commands that don't take any arguments, and quietly ignoring arguments when they get them is not a good idea.

test helper: maxArgs = 0 is actually a meaningful value

---

.cirrus.yml
drivers/overlay/overlay.go
tests/helpers.bash
tests/idmaps.bats

Cirrus: Update CI VM Images to F37

---

drivers/overlay/overlay.go

In newer kernel versions, the kernel overlay driver will attempt to atomically create whiteout when items are removed from merged directories.
We need to be able to detect when the underlying filesystem isn't able to do that at startup-time (in this case, zfs before its 2.2 release), so that we don't end up thinking we're fine, but mounting writeable layers which reject attempts to delete things.

supportsOverlay: ensure that whiteout creation works

---

store.go

When deleting a container, delete the layer first, as a distinct step, so that if we fail to do so, we don't just go ahead and remove the container record, which will prevent the caller from being able to try again.

Split up DeleteContainer

---

.cirrus.yml

Ref: https://github.com/containers/storage/pull/1588

Cirrus: Update fedora name

---

.cirrus.yml
go.mod

Fixes: https://github.com/containers/storage/issues/1597

Move to golang 1.19 for minimum

---

.golangci.yml
drivers/overlay/overlay.go
pkg/devicemapper/devmapper.go
pkg/devicemapper/devmapper_wrapper.go
pkg/ioutils/readers_test.go
pkg/regexp/regexp.go

Found/fixed 3 issues with govet and 3 issues with gosimple.

ci: enable govet and gosimple linters, fix found bugs

---

pkg/stringid/stringid.go

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

Document stringid.GenerateRandomID()

---

pkg/regexp/regexp.go

A follow-up on https://github.com/containers/storage/pull/1621/files#r1206860402 ; see individual commit messages for details.

Actually correctly fix problems caused by copying `pkg/regexp.Regexp` values

---

drivers/quota/projectquota.go

Change `drivers/quota.Quota.quotas` from being a `map[string]uint32` to a `*sync.Map`, since people may be accessing it via the the store's `GraphDriver()`, which provides no locking of its own which would prevent concurrent accesses.

Replace drivers/quota.Quota.quotas with a sync.Map

---

pkg/chunked/storage_unsupported.go

commit 423c0dc20746a3d297a7bb1bd4b52507d86b9542 introduced this issue.

chunked: drop unused import

---

docs/containers-storage.conf.5.md

Closes: https://github.com/containers/storage/issues/1749

docs: document convert_images

---

pkg/chunked/dump/dump.go
pkg/chunked/storage_linux.go

composefs: some fixes

---

pkg/homedir/homedir_windows.go

follow-up to https://github.com/containers/storage/pull/1810

homedir: use containers/storage on Windows

---

layers.go
pkg/chunked/compression_linux.go
pkg/chunked/toc/toc.go

Fixes / cleans up some outstanding items from https://github.com/containers/storage/pull/1627 .
@giuseppe PTAL.

Chunked cleanups

---

store.go

we need to lock the stores for read before checking if a layer exists.
follow up for 466ee04ed72429867df1fea80d992722ab571415
addressing the comment here: https://github.com/containers/storage/pull/1873#discussion_r1553620140

store: lock stores before calling Exists

---

pkg/chunked/internal/compression.go

I'm digging in more to zstd:chunked and I hope these comments are useful.

compression: Add some doc comments

---

pkg/chunked/compression_linux.go

always consume the tar-split data when present to avoid blocking the producer. Previously, the tar-split data was only read when the digest was specified.
commit 6875c9fbcf1cb6e06ee5e363982a059adec9693b introduced the regression.
follow-up for: https://github.com/containers/storage/pull/1936#discussion_r1624617123

chunked: fix deadlock by always consuming tar-split

---

pkg/chunked/filesystem_linux.go
pkg/chunked/filesystem_linux_test.go
pkg/chunked/storage_linux.go

follow-up for https://github.com/containers/storage/pull/1952
@mtrmac PTAL

chunked: improve error messages for file system operations

---

drivers/vfs/driver.go

partially revert 2d959dd4bf9050a85e3b91c11083fc005577c2ed
follow-up for https://github.com/containers/storage/pull/1976#discussion_r1651267923

vfs: honor the specified mappings

---

pkg/idmap/idmapped_utils.go

add more context to errors returned by unix.* functions

idmap: improve error messages

---

drivers/overlay/overlay.go
pkg/chunked/filesystem_linux.go
pkg/chunked/filesystem_linux_test.go

Just some more missing `O_CLOEXEC` I noticed while reading the code for unrelated reasons.

overlay,chunked: Add some more O_CLOEXEC

---

pkg/loopback/attach_loopback.go

simplify the error handling for openNextAvailableLoopback and avoid named return values

loopback: always return error if no loopback device

---

store.go
store_test.go

This PR implements a method for listing layers, images and containers. Method `Store.List` requires parameter type `ListOptions` that specifies the content of the return value. The return value is the structure `ListResult` that contains slices of layers, images or containers according to given options. The `List` method uses a locking mechanism so that the result is the current snapshot of the items listed. 
Fixes: 
- https://github.com/containers/podman/issues/23331

Create `Store.List` method for listing layers, images, containers

---

drivers/overlay/overlay.go
layers.go
store.go

... as modified by https://github.com/containers/storage/pull/2036 .
Also document a LOCKING BUG I don't now care to fix.

Be clearer about the layer store locking rules

---

drivers/overlay/overlay.go
pkg/chunked/cache_linux.go

Improve comments based on after-merge review comments

---

drivers/overlay/overlay.go

simplify the implementation of getStagingDir() to just create a new staging directory and drop the check whether the correct staging base directory as anyway the rename operation would fail later.
Closes: https://github.com/containers/storage/issues/2092

overlay: refactor getStagingDir helper

---

pkg/lockfile/lockfile.go
pkg/unshare/unshare_test.go

See individual commits for details.

Assorted nits reported by revive linter

---

OWNERS

Just performing an audit and cleanup of the OWNERS file.  Cleaned out duplicate reviewer entries as well.  Made judgement calls on the names based on the last 24 months of contributions, etc.

Audit and update OWNERS file

---

layers.go
pkg/chunked/storage_linux.go

Thanks to @kolyshkin for pointing these out in https://github.com/containers/storage/pull/2130#pullrequestreview-2370780475 .

Follow-ups to #2130

---

pkg/idtools/idtools.go

This happens e.g. in `idtools.MkdirAllAndChownNew` .
@giuseppe PTAL, this is necessary for c/image tests on macOS.

Fix `SafeChown` when `ContainersOverrideXattr` is unset

---

pkg/archive/archive_test.go

Some random cleanups I spotted when reading over the code.

Archive tests

---

pkg/archive/archive.go
pkg/archive/archive_test.go
pkg/archive/changes.go
pkg/archive/diff.go

* tarAppender did not append to tar files
* createTarFile did not create tar files
* addTarFile did not add tar files

archive: regularize some naming

---

pkg/chrootarchive/archive_test.go
pkg/chunked/compressor/compressor.go
pkg/chunked/storage_linux.go
pkg/ioutils/bytespipe.go
userns.go

Should not change functionality.

Use min/max to simplify the code

---

containers.go
drivers/copy/copy_test.go
drivers/graphtest/graphtest_unix.go
layers.go
layers_test.go
pkg/archive/archive_test.go
pkg/archive/changes_linux.go
pkg/archive/changes_posix_test.go
pkg/archive/changes_test.go
pkg/chrootarchive/archive_test.go
pkg/chunked/compressor/compressor.go
pkg/chunked/compressor/rollsum_test.go
pkg/ioutils/bytespipe_test.go
pkg/lockfile/lockfile_test.go
pkg/stringutils/stringutils.go

This form is available since Go 1.22 (see https://tip.golang.org/ref/spec#For_range) and will probably be seen more and more in the new code.

Use for range over integers

---

cmd/containers-storage/main.go
internal/opts/opts.go
layers.go
store.go

Please see individual commits for details.

Use `slices` and `maps` more where appropriate

---

.golangci.yml
cmd/containers-storage/layers.go
drivers/chown_unix.go
drivers/copy/copy_linux.go
drivers/overlay/check.go
drivers/overlay/overlay.go
internal/dedup/dedup_linux.go
internal/opts/opts.go
pkg/archive/archive.go
pkg/archive/archive_linux.go
pkg/archive/archive_unix_test.go
pkg/chunked/bloom_filter_linux.go
pkg/chunked/cache_linux_test.go
pkg/chunked/compression_linux.go
pkg/chunked/dump/dump.go
pkg/chunked/filesystem_linux_test.go
pkg/chunked/internal/minimal/compression.go
pkg/chunked/storage_linux.go
pkg/directory/directory_unix.go
pkg/ioutils/fswriters_test.go
pkg/loopback/attach_loopback.go
pkg/loopback/loopback.go
pkg/reexec/reexec.go
pkg/system/chtimes_linux_test.go
pkg/system/stat_linux.go
pkg/unshare/unshare_linux.go

Please review commit by commit. See individual commits for details.

ci: add nolintlint and unconvert linters, fix found issues

---

cmd/containers-storage/diff.go
deprecated.go
drivers/driver.go
pkg/chunked/compression_linux.go
pkg/chunked/storage_linux.go
pkg/chunked/storage_unsupported.go
store.go

follow-up for https://github.com/containers/storage/pull/2312

fix tarsplit file leak

---

layers.go
pkg/archive/archive.go
pkg/chunked/compression_linux.go
pkg/chunked/storage_linux.go

Addresses most of https://github.com/containers/storage/pull/2312#pullrequestreview-2819433654 . See individual commit messages for details.

Fix nits from #2312
