containers/storage

storage/lockfile.go

Migrate the `syscall` to `golang.org/x/sys/unix` (see: https://golang.org/pkg/syscall).
Also use `Mtimespec` instead of `Mtim` so this library compile on darwin.

Use Mtimespec instead of Mtim to compile on darwin

---

pkg/devicemapper/devmapper_log.go
pkg/devicemapper/devmapper_wrapper.go

Rename the "DevmapperLogCallback" exported-to-C function to "StorageDevmapperLogCallback", to avoid tripping up anyone who vendors the library but already has a copy of the "pkg/devicemapper" pkg which defines the callback with its previous name.

Rename "DevmapperLogCallback" to avoid conflicts

---

.travis.yml
Makefile
hack/make/test-unit

Add an initial Travis configuration file, and whatever fixups and tweaks we need to build in it.  This doesn't enable every test (`make lint` would fail, and integration tests are missing), but it's a start.

Add initial Travis configuration

---

drivers/aufs/aufs.go
drivers/aufs/aufs_test.go
drivers/devmapper/deviceset.go
drivers/graphtest/graphtest_unix.go
drivers/overlay2/mount.go
drivers/windows/windows.go
pkg/archive/archive.go
pkg/archive/diff.go
pkg/archive/example_changes.go
pkg/chrootarchive/archive_unix.go
pkg/chrootarchive/diff_unix.go
pkg/chrootarchive/diff_windows.go
pkg/chrootarchive/init_unix.go

We want to make sure that content created out of container storage
does not refer to docker.

Remove "docker" strings from container storage

---

storage/containers.go
storage/images.go
storage/layers.go

Ensure that the containing directories are there before we call `AtomicWriteFile` to save the lists of containers, images, or layers, each time we go to do so.  Samuel Ortiz noticed that we weren't making sure of this everywhere, and that this can trip up long-running processes.

Ensure directories are there before saving stores

---

storage/store.go

Also modify work directory to /var/run/containers/storage to be consistent.
/var/lib/containers/atomic is currently being used by other tools including the
atomic cli for storing OSTree based containers.  Running tools like CRI-O
ends up dropping lots of files in /var/lib/containers directory causing an
admin to get perhaps confused.  Since this tool is containers/storage, I think
it is best we store it in this subdir, and cleaner for administrators.

Modify default directories for storage to /var/lib/containers/storage

---

drivers/aufs/aufs.go
drivers/btrfs/btrfs.go
drivers/devmapper/deviceset.go
drivers/overlay/overlay.go
drivers/overlay2/overlay.go
drivers/vfs/driver.go
drivers/zfs/zfs.go
vendor.conf
vendor/github.com/opencontainers/selinux/LICENSE
vendor/github.com/opencontainers/selinux/README.md
vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go

We have moved runc/libcontainers selinux support out of libcontainer
into opencontainers/selinux.  Switching containers/storage to use
new interfaces.

Switch to using opencontainers/selinux

---

storage/store.go

Make it possible to create a container without using an underlying image.

Unbreak containers without images

---

cmd/oci-storage/container.go
cmd/oci-storage/image.go
pkg/truncindex/truncindex.go
pkg/truncindex/truncindex_test.go
storage/containers.go
storage/images.go
storage/layers.go
storage/store.go
vendor.conf
vendor/github.com/tchap/go-patricia/LICENSE
vendor/github.com/tchap/go-patricia/patricia/children.go
vendor/github.com/tchap/go-patricia/patricia/patricia.go

Add a truncindex to the layer, image, and container stores, so that layers, images, and containers can also be referred to by truncated versions of their IDs in any place where we previously accepted names.
For containers, we don't add a truncated index for referring to containers by layer ID, because there doesn't appear to be a minimum length in truncindex, and we don't want to mistakenly treat a truncated but not sufficiently-unique container ID as a layer ID, which would likely resolve to some other different container.

Add truncindex to stores, to allow use of truncated IDs

---

storage/layers.go

Fix canonicalization of layer IDs when computing layer differences, which we also broke in #6.

Fix canonicalization of layer IDs

---

storage/containers.go
storage/images.go

Fix the Lookup methods in container and image stores, which broke due to a bug in #6.

Fix {container,image}Store.Lookup()

---

hack/make/cross
storage/lockfile.go
storage/stat_mtim.go
storage/stat_mtimespec.go

Revendor "golang.org/x/sys" to pick up "golang.org/x/sys/unix", which we now use instead of syscall.  Handle Linux and BSD using different names for the mtime part of a Stat_t.  Add "darwin/amd64" to the list of OS/arch combinations that we preserve dependencies for when we're stripping out unused things in hack/vendor.sh.

Revendor golang.org/x/sys

---

drivers/overlay/mount.go
drivers/overlay/overlay.go
drivers/overlay/overlay_test.go
drivers/overlay/overlay_unsupported.go
drivers/overlay/randomid.go
drivers/register/register_overlay.go

Finish the overlay->overlay2 changeover by:
* renaming overlay2 to overlay
* teaching the driver to accept the overlay.override_kernel_check and
overlay2.override_kernel_check options as having the same meaning
* registering the driver init function using both names

Rename 'overlay2' to 'overlay'

---

drivers/aufs/aufs.go
drivers/btrfs/btrfs.go
drivers/devmapper/driver.go
drivers/driver.go
drivers/overlay/overlay.go
drivers/vfs/driver.go
drivers/zfs/zfs.go

We want to support additional read/only image stores available on
file systems.  Usually these images stores would be on network shares.
Currently the only driver that will support additional images is the
overlay file system.

Fix container storage to support additional image stores

---

containers.go
images.go
layers.go

Fix consistency errors we'd hit after creating or deleting a layer, image, or container, by replacing the slice of items in their respective stores with a slice of pointers to items, so that pointers in name- and ID-based indexes don't become invalid when the slice is resized.

Fix consistency errors after adding/removing items

---

store.go

Use the lockfile to mark that a store's contents need to be reloaded by other consumers whenever we call SetNames() to update a by-name index.

Mark stores as modified by SetNames()

---

lockfile.go

SELinux is complaining about the leaked file descriptors.

Lockfile is leaking file descriptors,  Needs to closexec

---

store.go

Changes from ErrImageUnknown to  ErrIsNotImage is breaking protocol and has changed the
behaviour of buildah, Breaking previous behaviour.

Some error return codes were accidently changed

---

containers.go
images.go
layers.go
lockfile.go
store.go

Building off of #50 and subsuming the changes from #52, this patch set refactors the existing LayerStore and ImageStore interfaces and introduces subsets of them that aren't expected to modify the underlying data.  It also implements versions of the implementations that take read-only locks instead of read-write locks, and uses those to handle additional storage locations.

Implement read-only layer and image stores

---

containers.go
images.go
layers.go

Add a Created field to Layer, Image, and Container structures that we intialize when creating one of them.

Track creation dates for layers/images/containers

---

containers.go
images.go
layers.go

Was playing around with CRI-O profiler (https://github.com/kubernetes-incubator/cri-o/pull/612) and ran into this:
When Delete:ing a layer or a container the code was always allocating a
new slice just to remove an element from the original slice.
Profiling cri-o with c/storage showed that doing it at every delete is
pretty expensive:
```
.          .    309:   newContainers := []Container{}
.          .    310:   for _, candidate := range r.containers
{
.          .    311:           if candidate.ID != id {
528.17kB   528.17kB    312:                   newContainers =
append(newContainers, candidate)
.          .    313:           }
.          .    314:   }
.          .    552:           newLayers := []Layer{}
.          .    553:           for _, candidate := range
r.layers {
. …
```

layers|containers: do not allocate slices at every delete

---

cmd/containers-storage/diff.go
docs/containers-storage-diff.md
layers.go
store.go

Add an optional *DiffOptions parameter to Diff() methods (which can be nil), to allow overriding of default behaviors.
At this time, that's just what type of compression is applied, if we want something other than what was recorded when the diff was applied, but we can add more later if needed.

Make Diff() methods take an optional *DiffOptions

---

layers.go
store.go
vendor.conf
vendor/github.com/opencontainers/go-digest/algorithm.go
vendor/github.com/opencontainers/go-digest/digest.go
vendor/github.com/opencontainers/go-digest/digester.go
vendor/github.com/opencontainers/go-digest/doc.go
vendor/github.com/opencontainers/go-digest/verifiers.go

This change adds fields to `Layer` structures that track compressed and uncompressed digests and diff sizes on behalf of callers, and populates them when a layer has `ApplyDiff()` called against it, or is created with `Put()`.

Remember digests

---

images.go
store.go

Add a field to ImageOptions that allows a caller to specify a date of creation when calling CreateImage(), if there's a value in the image metadata that would be more useful than the default (which is "now" at
the time CreateImage() is called).

Allow setting the creation-date on images

---

store.go

Since ImageOptions are optional when calling a store's CreateImage() method, we can't assume that there's a value there.

When creating images, options are optional

---

drivers/aufs/aufs.go
drivers/aufs/aufs_test.go
drivers/aufs/mount_unsupported.go
drivers/btrfs/btrfs.go
drivers/devmapper/deviceset.go
drivers/driver.go
drivers/driver_solaris.go
drivers/graphtest/graphtest_unix.go
drivers/overlay/overlay.go
drivers/proxy.go
drivers/zfs/zfs.go
drivers/zfs/zfs_freebsd.go
drivers/zfs/zfs_linux.go
drivers/zfs/zfs_solaris.go

Wrap `graphdriver.{ErrNotSupported,ErrPrerequisites,ErrIncompatibleFS}` errors in contexts using `github.com/pkg/errors`, and dig them out for comparison using `errors.Cause()`.

Wrap some driver-level errors

---

layers.go

The `Diff()` method didn't handle recompression correctly when generating a diff between a layer and its parent when there was no tar-split data present.

Fix compression handling for Diff() methods

---

drivers/driver_linux.go

When selecting overlay as a possible use-by-default driver, use it under the name "overlay".

Default to overlay as "overlay"

---

drivers/devmapper/deviceset.go

An AUFS filesystem doesn't give us the "real" device and inode numbers of an underlying file when we stat() it, so we'll hit errors trying to resume use of a pool when that pool is built on loopback devices using
files that live on an AUFS filesystem.  Refuse to let ourselves be put into that situation.

Refuse to start loopback devicemapper on AUFS

---

store.go

We should default to "" and then allow the library to pick the
best driver for the particular distribution.  Picking overlay is
currently breaking cri-o on Centos and RHEL, since they don't
support overlay driver until 7.4 release.

Do not default to overlay

---

pkg/mount/sharedsubtree_notlinux.go
store.go

We are leaking files into other mount namespaces, making the
runroot private might also improve performance.

RunRoot directory should be mounted private

---

.travis.yml
storage.conf

This is causing cri-o to break in RHEL7.3 environments.
Changing to "" allows the containers/storage to pick a storage
driver that will work on a particular platform.  It will still
default to overlay by default, if the platform supports it.

We should not force a default storage driver

---

pkg/mount/mount.go

Do not umount when exiting, because you are not sure if you mounted
in the first place and you could accidently umount other peoples mounts.

Make sure you get the realpath when checking Mounted

---

containers.go
errors.go
images.go
layers.go
lockfile.go
store.go

Use the standard library's "errors" package to create errors so that backtraces in wrapped errors terminate at the point where the error was first wrapped, and not at the line where we created the error, which isn't as useful for troubleshooting.

Create errors using "errors"

---

store.go

Remove methods that fetch the underlying layer, image, and container store objects from the public Store interface.  They're still accessible via type assertions, but ideally that's never going to be necessary.

Remove direct access to substores from Store()

---

pkg/mount/sharedsubtree_notlinux.go
store.go

We instead need to move the shm content into a different directory.
This patch basically reverts 05e45e0b084152a4eff88db0d4ea308fd326a3d4.
The reason we need this patch is to allow oci-umount to remove leaked
mount points into the container.  We are going to attempt to move the
shm mount point to a different directory.

     Revert "RunRoot directory should be mounted private"

---

store.go

@umohnani8 noticed that `Store.Names()` was hitting a deadlock - when attempting to iterate through the concatenated list of read-write and read-only image stores, the method was actually walking the list of read-write and read-only layer stores a second time, so when it attempted to obtain a lock on the first layer store, it would deadlock.
This PR also teaches `Store.Lookup()` about read-only locations, and updates sections of the code that scan read-only layer and image stores to be more consistent in variable naming in an effort to avoid bugs like this one.

Fix a locking error in Store.Names()

---

pkg/archive/archive.go

Add back in these interfaces since containers/image is using.
archive.UntartPath
archive.IsArchive
Also add back this constant for containers/image.
archive.HeaderSize

Add interfaces that were removed from upstream but containers/image uses

---

cmd/containers-storage/name.go
containers.go
docs/containers-storage-add-names.md
docs/containers-storage-get-names.md
docs/containers-storage-set-names.md
images.go
layers.go
store.go

We already deduplicated names in Store.SetNames(), but we weren't also doing that when creating layers, images, and containers, or in the individual store SetNames() methods.

Be more thorough about deduplicating names

---

cmd/containers-storage/create.go
images.go
store.go

We need to be able to create images which consist of just a list of manifests, and those don't contain layers, so relax CreateImage()'s requirement that a layer be specified.

Stop rejecting creation of images with no layers

---

docs/containers-storage.conf.5.md
drivers/overlay/overlay.go

Move lack of DTYpe on Overlay from Error down to Warning, temporarily until infrastructure CI has updated VMs with correct support.
Moby currently  has the same compromise.

Move no Dtype on Overlay from Error to warning.

---

docs/containers-storage.conf.5.md
storage.conf
store.go

Allow users to specify the maximum size of a containers in the
/etc/containers/storage.conf file.  This will enable quota checking
in the drivers that support it.
Allowe users to OverrideKernelCheck to tell drivers to ignore kernel
version checks that indicate whether the driver is supported on that
kernel.  These checks do not make sense on older RHEL kernels, since
the driver support was back ported.

Specify OverrideKernelCheck and Size in /etc/containers/storage.conf

---

.travis.yml
drivers/fsdiff.go

The skopeo package builds on Darwin use Go 1.7, so make sure we can build on it, by replacing a call to `time.Until(t)` with `t.Sub(time.Now())`, as suggested in the standard library documentation.
This should get https://github.com/projectatomic/skopeo/pull/427 to pass its tests.

Fix builds with go 1.7

---

containers.go
errors.go
images.go
layers.go
store.go

When we read itms from disk, if maps in the structures are empty, they won't be allocated as part of the decoding process.  When we subsequently go to read or write something from such a map, make sure
it's been initialized.
Add some validation of names that we convert to file names, and of digest values, so that we can be more precise about the error code we return when there's a problem with the values.

Initialize Flags and BigDataSizes maps

---

cmd/containers-storage/main.go

Make the CLI use all of the default settings if none of them are overridden on the command line, or none of them, if any are overridden.  Any other behavior is hard to use in integration tests, and confusing.

Make the CLI use either all defaults, or none

---

.travis.yml

tip seems to be broken right now.

Change tip to 1.9 in travis

---

tests/stores.bats

* After we're done initializing a read-only store for a test, shut it down so that we'll be able to delete it when cleaning up later.
* When mounting a layer that inherits from read-only layers, don't forget to pass the read-only store's location to the CLI helper.

Fixups for read-only store tests

---

CONTRIBUTING.md

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
Change IRC channel to container-projects from cri-o in the CONTRIBUTING.md file.

Change cri-o IRC channel to container-projects in CONTRIBUTING.md

---

store.go

`LayersByCompressedDigest` and `LayersByUncompressedDigest` shouldn't fail if one of the stores being consulted doesn't have any layers that match the specified digest, since that's an expected possibility.

Fix LayersBy*Digest with multiple layer stores

---

drivers/overlay/overlay.go
drivers/vfs/driver.go

In the overlay and vfs drivers, accept option names which we'd recognize, if they had the driver name as a prefix, as aliases for their proper names.

overlay, vfs: Accept options without the driver name prefix

---

cmd/containers-storage/images.go
images.go
images_ffjson.go
store.go
tests/image-by-digest.bats

Add a "digest" of an image that is equal to the digest of its big data item named "manifest", if it has one, that we can index and use for locating images.  We'll be able to use this in the image library to help it locate images using canonical (digest-based) references.

Add a notion of image "digests" based on their "manifest" data

---

drivers/overlay/overlay.go

When checking if we can use the overlay driver at initialization time, actually try a mount using temporary directories instead of assuming that the kernel listing it as a known filesystem is enough, since it
might not be listed if we're in a container, and we can't load the module from inside of a container.

overlay: when checking for support, actually try a mount

---

drivers/overlay/overlay.go

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
Reverting #106 to error on DType rather than just warn as support should have been added to the CI for this.

Turn DType testing back on

---

drivers/overlay/overlay.go

The supports-dtype check tries to create a subdirectory of the driver's home directory to use for its checks, so it needs to be called after that directory has been created.
If it fails, go ahead and try to rmdir() the directories that we've created to avoid creating a false positive indicator that this driver works, but let the attempt to remove them fail in case we've had previous successful startups and there's actually data here.

overlay: perform the support check after creating homedir

---

store.go

And how they are detected. A bit of these environment variable is a bit
magic and may need to change a bit, such that if the caller only
provides a driver name, but not a path, etc. that the right thing is
done.
But for now, at least document that the DefaultOptions will be used, and
there is another way to influence what driver is chosen.

storage: add comments on the defaults

---

store.go

Acquire the big storage lock before the lock on the layer store, because they should always be acquired in that order if we're picking up both.

Fix a lock ordering error in Shutdown()

---

drivers/btrfs/btrfs_test.go
drivers/devmapper/devmapper_test.go
drivers/graphtest/graphtest_unix.go
drivers/overlay/overlay.go
drivers/overlay/overlay_test.go
drivers/vfs/vfs_test.go
drivers/zfs/zfs_test.go
pkg/archive/archive.go
pkg/archive/archive_linux.go
pkg/archive/archive_linux_test.go
pkg/archive/archive_other.go
pkg/archive/archive_unix_test.go
pkg/archive/changes.go
pkg/archive/changes_linux.go
pkg/archive/changes_test.go
tests/helpers.bash
tests/test_drivers.bash

Check if the overlay filesystem implements an optimization that landed in 97c684cc911060ba7f97c0925eaf842f159a39e8, and in the mainline kernel in 4.10:  directories created in merged directories are marked as opaque to let the kernel know that it needn't bother looking at lower layers when reading the contents of that directory.
This means that, when generating a layer diff for an upper directory, we can't treat the presence of an opaque whiteout entry as an indication that a layer diff needs to include whiteout for a directory of the same name from a lower layer.  If we do, when that diff is later applied, the directory gets created, and then removed, and then only recreated (possibly with different permissions) if the diff also places contents in the directory.

Check for overlay merging optimization

---

drivers/overlay/overlay.go
drivers/overlayutils/overlayutils.go

Revert the mistaken change to wrap graphdriver.ErrNotSupported instead of the error returned by supportsOverlay(), when it returns an error, so that text describing exactly why overlay isn't supported will be returned to our caller.

Restore details to "overlay not supported" errors

---

.travis.yml
hack/run_ci_tests.sh
hack/spc_ci_test.sh

* Added the few small changes needed to support these other distros.
* Enable building GO_VERSION "stable" on all distros, but ignore the
result.  The failures are seemingly similar, but beyond my ability to
debug.  For now, ignore the result to provide exposure and runtime
without any requirement to pass.

Enable Stable + build/test on Fedora and CentOS

---

store.go

Add a note about needing to call `reexec.Init()` to the doc for the `GetStore()` function.  Also correct incorrect usage elsewhere.

GetStore: add a note about needing to reexec.Init()

---

cmd/containers-storage/container.go
cmd/containers-storage/layer.go

Provide the information that was actually requested when we produce JSON output for the layer-parent-owners and container-parent-owners commands.  Carried over from #156.

CLI: fix JSON output for layer/container-parent-owners

---

.travis.yml
pkg/chrootarchive/chroot_linux.go
vendor.conf
vendor/github.com/syndtr/gocapability/LICENSE
vendor/github.com/syndtr/gocapability/capability/capability.go
vendor/github.com/syndtr/gocapability/capability/capability_linux.go
vendor/github.com/syndtr/gocapability/capability/capability_noop.go
vendor/github.com/syndtr/gocapability/capability/enum.go
vendor/github.com/syndtr/gocapability/capability/enum_gen.go
vendor/github.com/syndtr/gocapability/capability/syscall_linux.go

When deciding whether to `pivot_root` or `chroot` in `pkg/chrootarchive`, check if we have `CAP_SYS_CHROOT` and `CAP_SYS_ADMIN`, instead of checking if we have non-default UID mappings, which don't directly affect whether or not we'll be able to do one or the other of those things.

Decide how to chroot based on capabilities, not uid_map contents

---

drivers/windows/windows.go

maybe a copy-paste error? seems like some simple test or compile check
would've caught this.

driver/windows: duplicated code?

---

pkg/system/stat_windows.go

Windows does not have a concept of UID/GID, but rather ACLs and SIDs
which do not map cleanly at all.
Since we've exposed `UID()` and `GID()` for this `StatT`, then we need
something equivalent.

pkg/system: exposed functions need a windows equivalent

---

pkg/directory/directory_unix.go

Without this build fails on macOS with
> ./store.go:1561:12: undefined: directory.Size
> ./store.go:1566:11: undefined: directory.Size
because `directory.Size` has no implementation.

Fix build on macOS

---

docs/containers-storage.conf.5.md
drivers/overlay/overlay.go

When specified the mount of the overlay file system is delegated to
the specified command instead of mounting it directly.
This patch enables the usage of helpers programs for mounting overlay using a FUSE program.

containers-storage: add new option .fuse_program

---

drivers/fsdiff.go

without
```
Writing manifest to image destination
Storing signatures
DEBU[0004] Start untar layer
Failed
ERRO[0004] error pulling image "docker.io/library/busybox": unable to pull docker.io/library/busybox: unable to find image in the registries defined in "/etc/containers/registries.conf"
```
with
```
Writing manifest to image destination
Storing signatures
DEBU[0005] Start untar layer
ERRO[0005] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: lchown /home: invalid argument
Failed
ERRO[0005] error pulling image "docker.io/library/busybox": unable to pull docker.io/library/busybox: unable to find image in the registries defined in "/etc/containers/registries.conf"
```
Related: https://github.com/projectatomic/libpod/issues/1087

log errors from ApplyUncompressedLayer

---

docs/containers-storage.conf.5.md
drivers/overlay/overlay.go
storage.conf
store.go

Move the configuration file parsing to a new function `ReloadConfigurationFile` so that it is possible to load a differentconfiguration file and override the current settings.  This is useful with rootless containers so a configuration file specific to the user can be loaded.

storage: allow to use a different configuration file

---

docs/containers-storage.conf.5.md
drivers/aufs/aufs.go
drivers/btrfs/btrfs.go
drivers/devmapper/deviceset.go
drivers/overlay/overlay.go
drivers/vfs/driver.go
drivers/windows/windows.go
drivers/zfs/zfs.go
storage.conf
store.go

I believe we should be running container images mounted with nodev by default.
This would eliminate the disk of a device sneaking into the container without
being on the approved list.  This would give us the same or potentially additional
security over the device cgroup.
It would be nice if this could be passed in on an image by image basis.  So users
could also specify if they want nosuid images.

Add default mount options to pass to drivers

---

drivers/overlay/overlay.go
pkg/mount/flags.go
pkg/mount/mount.go
pkg/mount/mount_unix_test.go

We need to translate the mount options into flags or
data, so this PR makes the parse code public so we can
use it in containers/storage.

Fix overlay to handle mountopt properly

---

pkg/idtools/idtools.go

Need to tell users about the files that the mappings are missing in.
No subuid ranges found for user "dwalsh" in /etc/subuid

Add more information in errors about missing uidimappings or gidmappings

---

containers.go
images.go
layers.go
lockfile.go
lockfile_unix.go

I have experienced "layer not known" corruption triggered by concurrent
buildah/skopeo processes, and hopefully lock sanity checks will help to
prevent this kind of problem.
Signed-off-by: Zac Medico <zmedico@gmail.com>

Add lock sanity checks to Save() methods

---

lockfile_windows.go

The Locked() method must be implemented so that Save() will work on
windows.
Fixes: c7ba5749d44a ("Add lock sanity checks to Save() methods")
See: https://github.com/containers/storage/pull/210#issuecomment-416671810
Reported-by: Miloslav Trmač <mitr@redhat.com>
Signed-off-by: Zac Medico <zmedico@gmail.com>

Implement Locker.Locked() for windows

---

store.go

In CreateContainer(), don't use ROLayerStores() to get a list of the read-only layer stores after we've acquired the lock on the writeable layer store.  ROLayerStores() acquires the graph lock, which we should never try to acquire while we're holding the layer store lock.

Fix a lock inversion

---

store.go

While generating a Diff, hold the lock on the layer store until after we've completely finished building the diff.
There's an internal Mount/Unmount being done so that we can read the layer's contents, and we don't update the mount counts properly if we're not still holding the lock when the layer store's Unmount() method is called, and that doesn't happen until the ReadCloser that Diff() returns gets closed.
This should fix https://github.com/projectatomic/buildah/issues/981.

Hold the layer store lock while diffing

---

drivers/chown_unix.go

be sure the SUID and SGID bits are not lost when we do
a chown.
Closes: https://github.com/containers/libpod/issues/1526

chown: restore SUID and SGID bits

---

drivers/aufs/aufs.go
drivers/aufs/aufs_test.go
drivers/btrfs/btrfs.go
drivers/btrfs/btrfs_test.go
drivers/chown.go
drivers/devmapper/driver.go
drivers/driver.go
drivers/fsdiff.go
drivers/graphtest/graphbench_unix.go
drivers/graphtest/graphtest_unix.go
drivers/graphtest/testutil.go
drivers/graphtest/testutil_unix.go
drivers/overlay/overlay.go
drivers/vfs/driver.go
drivers/windows/windows.go
drivers/zfs/zfs.go
layers.go
store.go

This patch adds a MountOpts field to the drivers so we can simplify
the interface to Get and allow additional options to be passed in the future.

 Add MountOpts to stop adding fields to Get Interface 

---

drivers/overlay/check.go
drivers/overlay/overlay.go
drivers/overlay/overlay_test.go

If in storage.conf I set the mount options to:
mountopt = "nodev,metacopy=on,redirect_dir=on"
This will turn on redirect_dir but the useNaiveDiff does not currently check
this option.  This will cause container images on commit to not be saved
correctly.

Setting storage options could break overlay commit.

---

Makefile
README.md

Make the list of .PHONY targets consistent with the actual Makefile
targets. Update The README with the correct make target for the
CLI wrapper.
Signed-off-by: Marco Vedovati <mvedovati@suse.com>

make: clean up .PHONY targets list

---

layers.go

We've seen a panic on Azure with CRI-O/OCP:
```
Nov 08 17:52:58 master-000002 crio[5779]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 08 17:52:58 master-000002 crio[5779]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x55cec3a16669]
Nov 08 17:52:58 master-000002 crio[5779]: goroutine 127 [running]:
Nov 08 17:52:58 master-000002 crio[5779]: panic(0x55cec467fda0, 0x55cec52cba20)
Nov 08 17:52:58 master-000002 crio[5779]: /opt/rh/go-toolset-7/root/usr/lib/go-toolset-7-golang/src/runtime/panic.go:551 +0x3c5 fp=0xc4206e17f0 sp=0xc4206e1750 pc=0x55cec2f47685
Nov 08 17:52:58 master-000002 crio[5779]: runtime.panicmem()
Nov 08 17:52:58 master-000002 crio[5779]: /opt/rh/go-toolset-7/root/usr/lib/go-toolset-7-golang/src/runtime/panic.go:63 +0x60 …
```

layers: return the in-use layer on ErrDuplicateID

---

drivers/overlay/overlay.go
hack/spc_ci_test.sh

an unprivileged user doesn't have the permission to use mknod (except
in file systems owned by the user itself, e.g. tmpfs), so the unpack
would always fail with EPERM.  Use the AUFS whiteout format that
doesn't require CAP_MKNOD.
Closes: https://github.com/containers/buildah/issues/1160

overlay: use AUFS whiteout format when using mount_program

---

layers.go

This check has been wrongly removed with #198 
The check must stay as it's now part of the Stop/Delete API so reintroduce it back
This fixes #233 and the associated CRI-O issues
This PR + https://github.com/kubernetes-sigs/cri-o/pull/1910 fully fix the issue
@rhatdan @nalind @sboeuf @chavafg PTAL 
I'm going to revendor c/storage in CRI-O to full fix crio after this is merged
Signed-off-by: Antonio Murdaca <runcom@linux.com>

layers: do not try to unmount if not mounted at all on delete

---

cmd/containers-storage/create.go
pkg/idtools/parser.go
store.go

I found that other projects, tend to parse multiple maps at once. So, we may want to allow the base library to do so in order to decrease complexity in the upper layers. (For comparison please see: https://github.com/kubernetes-sigs/cri-o/blob/4cd5a7c60349be0678d9f1b0657683324c1a2726/server/server.go#L248 https://github.com/containers/libpod/blob/e8e16fcc789df6a705fbbf5c5597f16a4255d690/pkg/util/utils.go#L172 https://github.com/containers/buildah/blob/c116133dd5d62e3791ff792468c9a11b1bdffafd/util/util.go#L421 )
This is follow-up on previous refactoring in 7b209d36fd98ff0a969, I didn't got it right on first try, sry.
Signed-off-by: Šimon Lukašík <isimluk@fedoraproject.org>

Refactor ParseIDMap, allow parsing multiple maps at once

---

store.go

We have seen situations in buildah where a container is being
built and user hits ^c, then he ends up in a situation where
he can not delete container, since layer does not exist.

Should still delete container if layer does not exist.

---

drivers/fsdiff.go
drivers/overlay/overlay.go
pkg/archive/archive.go
pkg/chrootarchive/archive.go

we cannot check if we are running in an user namespace after the
chroot, as /proc is not accessible.  So let's pass this option down
before re-execing and doing a chroot.
Closes: https://github.com/containers/libpod/issues/1775

archive: propagate InUserNS option to storage-untar

---

docs/containers-storage.conf.5.md

People looking to modify storage.conf might be confused as to what the valid graph drivers and their names are. List all supported drivers in the manpage to assist them.
Shouldn't be necessary elsewhere, most of the other fields are just paths.

Add list of supported graph drivers to manpage

---

drivers/devmapper/deviceset.go
drivers/graphtest/testutil.go

When we test for change detection on top of filesystems with low timestamp granularity, we can end up updating a file without forcing a change to its modification timestamp.  Check for that when we attempt to
modify the files, and just keep rewriting it until the timestamp changes.

graphtest: insulate against filesystems with low timestamp granularity

---

docs/containers-storage-mount.md
docs/containers-storage-mounted.md
docs/containers-storage-unmount.md
docs/containers-storage.md

Add a man-page of subcommand mounted that is added by commit 1075a73cac.
Add new lines to prevent the section SUB-COMMANDS of containers-storage.md from crushing when previews as markdown.
Signed-off-by: ERAMOTO Masaya <eramoto.masaya@jp.fujitsu.com>

[docs] Add man-page of subcommand mounted

---

layers.go

based on some comments got on the related PR for containers/image.

layers: use the package name pgzip instead of gzip

---

store.go

We need to expose this file path in podman info
to make it easier for users to discover where
the configuration file is.

Expose path to default config file

---

drivers/overlay/overlay.go

If we set metacopyup flag in storage.conf, we need to use
this field, when creating the intermediate storage layer.

Use mount options when mounting the chown layer.

---

drivers/zfs/zfs.go

This was originally put in to prevent potential leaks of mount points to
different mount namespaces.  Lets remove it and fix the issue with
zfs, and see if we experience leaked mounts.  oci-umount should also
clean up any leaks, if installed.

Remove mounts private from zfs, it is causing issues on reboot with zfs

---

hack/btrfs_tag.sh
hack/libdm_tag.sh
hack/ostree_tag.sh

Before checking for btrfs/libdm/ostree availability, check which OS we're on, and if it isn't Linux, disable them.  This should simplify cross-compiling at least a bit.

Check for the OS when setting btrfs/libdm/ostree tags

---

pkg/mount/mounter_linux_test.go

On SELinux-enabled kernels, the kernel will helpfully add a "seclabel" option to mounted filesystems to indicate that labeling is supported.  Don't let that break our tests.

Don't fail the mounter test because the kernel added options

---

pkg/archive/archive.go
pkg/chrootarchive/archive.go
pkg/chrootarchive/archive_test.go

We want to use these functions in both podman and buildah
So move them out of buidlah into storage.

Move copytar functions from buildah to storage

---

pkg/config/config.go
store.go

Need to access the storage structs in the machine-config
operator code for container runtime configuration but
with it being in store.go, it is pullng in way too many
dependencies. Moving it out to a separate package cuts down
the dependencies by a huge amount.

Move structs for storage.conf to pkg/config

---

store.go

Check for errors returned by various `Load()` methods.

Don't ignore errors reloading layer/image/container lists

---

drivers/overlay/overlay.go
store.go

When we removed all traces of override_kernel_check in #269, we created a situation where older configuration files would suddenly start causing us to emit an error at startup.  Soften that to a warning, for now at least.

Make use of overlay.override_kernel_check a warning instead of an error

---

lockfile.go
store.go
tests/abs.bats

Resolve passed-in locations to absolute paths at startup.  This should fix https://github.com/containers/buildah/issues/1345.

GetStore(): resolve passed-in paths to absolute paths

---

cmd/containers-storage/container.go
cmd/containers-storage/containers.go
cmd/containers-storage/copy.go
cmd/containers-storage/create.go
cmd/containers-storage/diff.go
cmd/containers-storage/image.go
cmd/containers-storage/images.go
cmd/containers-storage/layer.go
cmd/containers-storage/layers.go
cmd/containers-storage/main.go
cmd/containers-storage/metadata.go
cmd/containers-storage/name.go
cmd/containers-storage/shutdown.go
cmd/containers-storage/status.go
cmd/containers-storage/version.go
cmd/containers-storage/wipe.go
hack/git-validation.sh
images.go
layers.go
lockfile.go
lockfile_unix.go
store.go
tests/abs.bats
tests/stores.bats

Clarify that our `Locker.Locked()` checks if the calling process is holding a write lock, since that's what we care about in the places where we call it.  Change a number of places where `Store` takes a lock but doesn't expect to be modifying on-disk data to have it take a read-only lock instead.

Clarify Locker.Locked(), and switch some locks to read-only

---

pkg/reexec/command_linux.go
pkg/reexec/command_unix.go
pkg/reexec/command_unsupported.go
pkg/reexec/command_windows.go
pkg/reexec/reexec_test.go

Add `CommandContext()`, which is like `Command()`, but which also takes a context, very much in keeping with `os/exec.CommandContext()`.

reexec: add CommandContext()

---

drivers/copy/copy.go
pkg/archive/archive.go
pkg/archive/archive_linux.go
pkg/idtools/idtools.go
pkg/idtools/idtools_unix.go

if os.[Lc,C]hown are failing with EINVAL, it might be related to an
UID/GID not mapped in the user namespace we are currently using.
It could be possible to detect this issue by inspecting
/proc/self/uid_map or /proc/self/gid_map, but that won't be possible
when we are pulling a new image and extracting it from a chroot where
/proc is not mounted.

storage: make [l]chown errors clearer

---

.travis.yml
cmd/containers-storage/main.go
store.go
utils.go

In an effort to remove cross vendoring, trying to fix buildah from importing from
libpod.  I believe these libraries make more sense in containers/storage then in libpod.

Move Storage features in pkg/util from libpod to containers/storage

---

utils.go

When trying to vendor into containers/image we found issues
with cross platform compilation.

Fix cross compilation code for other platforms

---

docs/Makefile
docs/containers-storage.conf.5.md

This helps users figure out where the configuration files are located
and understand how to override them.

Add FILES section to containers-storage.5 man page

---

drivers/copy/copy_linux.go
drivers/copy/copy_unsupported.go

The vfs driver already has logic that avoids use of the copy package when we're not on Linux, so provide the same fallback in the copy package for non-cgo cases.

drivers/copy: add a non-cgo fallback

---

cmd/containers-storage/main.go
utils.go

do not expect the caller to know what rootless user is used, but
detect it internally.

storage: move the logic to detect rootless into utils.go

---

drivers/copy/copy_linux.go

We failed to detect char devices as those were not covered by the
`ModeDevice` check.  Fix this by using the entire FileMode mask as
suggested by the standard library.
Also change the "unknown file type" error to include the mode to
ease debugging potential regressions in the future.

drivers.DirCopy: fix filemode detection

---

utils.go

We have not been checking the permissions on the rootless directory
this causes issues in tools trying to access the login directory
if XDG_RUNTIME_DIR is not set correctly.

Correctly check permissions on rootless directory

---

drivers/devmapper/device_setup.go

We have a bug report where a user specified a symbolic link to storage
driver.  The issue is the physical device is not predictable but the link
is, so evaluating sym links makes the symlink path supportable.

Evaluate device path for lvm

---

lockfile_test.go

This is based on https://github.com/containers/storage/pull/310 and adds one commit on top to fix some test flakes.

lockfile: make tests deterministic

---

utils.go

If the root user created a new user namespace, it still has to use the
system configuration and storage.
Previously if root created a user namespace when missing
CAP_SYS_ADMIN, we would use the configuration file under
/root/.config/containers instead of /etc/containers.

utils: root in a userns uses global conf file

---

drivers/overlay/overlay.go

If the synlinks under /var/lib/containers/storage/overlay/l are lost
during a sudden reboot, we go through all the layers under the overlay
directory and create symlinks point to their respective diff directories
with the same name as they were created before. We get this name from
the "link" file under each layer dir.

Recreate symlink when not found

---

drivers/overlay/overlay.go

Somehow, the multiple-lowers test in the overlay driver succeeded even when we didn't pass in an upper or work directory, but the single-lower test definitely needs us to do that.
This should fix #327.

overlay: fix single-lower test

---

Makefile
docs/Makefile

Manpage for storage.conf is being built as 'container-storage.conf.5'
(notice the missing 's' after 'container'), but it should be
'containers-storage.conf.5' for consistency with the whole project
naming.
Closes #329
Signed-off-by: Silvano Cirujano Cuesta <silvano.cirujano-cuesta@siemens.com>

docs: fix manpage for configuration file

---

drivers/overlay/overlay.go

Noticed that the link directory may be lost also with the symlinks,
so this fix creates it if not found and then restores all the links.
Also fix up logic to check wether a dir is found or not instead of
a regular file.

Fix up recreateSymlink

---

drivers/driver.go
drivers/overlay/overlay.go
drivers/vfs/driver.go
layers.go

prefer the custom idmapping specified for the layer instead of using the global one configured for the driver.
Closes: https://github.com/containers/libpod/issues/2960

layers: use the correct idmapping when creating a layer

---

docs/containers-storage.conf.5.md
storage.conf

We were not documenting remap-uid and gid, need this documented in the man
pages.

Add missing options to man page for containers-storage

---

docs/containers-storage-import-layer.md
docs/containers-storage.md

These commits address points 1 and 3 of https://github.com/containers/storage/issues/323:
* Document in the manpage of containers-storage that a read-only layers are needed to get OSTree deduplication.
* Add a manpage for import-layer.

Document OSTree deduplication and add manpage for import-layer

---

cmd/containers-storage/create.go
store.go
tests/create-container.bats
tests/create-image.bats

When creating a container, don't worry about whether or not the base image's top layer has the right ID mappings in cases where the base image doesn't have a top layer.

CreateContainer: don't worry about mapping layers unless necessary

---

drivers/chown.go
tests/idmaps.bats

fix a regression introduced with d1554f0dcd6a74eaade2181239f8df7df975f7b1 and 7c6d502e9bd4e485eeb291ed3c8f7b44dcecb34d that broke some tests.
Also, skip some tests that are not valid when using fuse-overlayfs as it supports ID shifting.
With this patch for fuse-overlayfs: https://github.com/containers/fuse-overlayfs/pull/76
I was able to run the tests suite as:
```
```

tests: fix regression when using idmapping

---

pkg/chrootarchive/archive.go
pkg/chrootarchive/archive_unix.go
pkg/chrootarchive/archive_unix_test.go
pkg/chrootarchive/archive_windows.go
pkg/chrootarchive/init_unix.go

As the title says. We'll probably need a new release of c/storage once this lands.
I think `CopyFileWithTarAndChown` and `CopyWithTarAndChown` (and probably `UntarPathAndChown`) need double-checking to make sure they're also fixed, they're not included in the scope of the cherry pick.

Cherry-pick moby/moby #39292 for CVE-2018-15664 fixes

---

store.go

We have a bug in podman that uses the defaultGraphDriver options
for returning the MountOptions rather then the driver overrides
from the user.
This PR adds a new interface GetMountOptions which parses the callers
graphdriveroptions and return the mountoptions

Add function to parse out mount options from graphdriver

---

utils.go

We are currently ignoring XDG_RUNTIME_DIR if it is set, while
we should be using it.

Return XDG_RUNTIME_DIR as RootlessRuntimeDir if set

---

drivers/aufs/aufs.go
drivers/aufs/aufs_test.go
drivers/btrfs/btrfs.go
drivers/devmapper/devmapper_test.go
drivers/devmapper/driver.go
drivers/driver.go
drivers/graphtest/graphtest_unix.go
drivers/overlay/overlay.go
drivers/vfs/driver.go
drivers/windows/windows.go
drivers/zfs/zfs.go
store.go

Instead of passing the driver-specific directory and assorted fields from a `Config` struct to lower-level drivers when we initialize them, pass them the directory and the `Config` struct.  Add the `runroot` to the `Config` struct.  Have the overlay driver use cache files under the runroot to track whether or not overlay is supported, whether or not metacopy is on (for a specific set of mount options), and whether or not we can use native diff (again, for a specific set of mount options).  This attempts to fix #368.

overlay: cache the results of feature tests

---

utils.go

the previous error condition was causing an early failure when the
configuration file existed.  It prevented some additional checks and
to correctly set the RunRoot and GraphRoot to their default values
when they are not overriden in the configuration file.
We have not noticed it earlier as Podman would still use the
configuration from the DB in this case, so the issue is visible with
Podman only when the RunRoot is not specified in the configuration
file and in the libpod DB as well.
Closes: https://github.com/containers/libpod/issues/3274

utils: fix check for missing conf file

---

drivers/quota/projectquota.go
drivers/quota/projectquota_unsupported.go

quota: add build tag to disable it

---

pkg/idtools/idtools.go

Administrators can add records to /etc/subuid and /etc/subgid based
on username or UID.  Currently we only support lookup based on username.
This patch will lookup based on UID, if it is available in the /etc/passwd
file on the host.

Add support for UID Matching in /etc/subuid and /etc/subgid

---

docs/containers-storage.conf.5.md

On the relabeling instructions, it's quite confusing to use a variable
on the first command, and then a literal location on the second one.
Signed-off-by: Cleber Rosa <crosa@redhat.com>

Use same variable name on both commands

---

drivers/vfs/driver.go

Current implementation of VFS driver performs the copy of the parent layer during the creation of new (child) layer, but does not clean the destination if the copy process fails.
From the consuming application perspective, this make storage leaks possible, e.g. an attempt to create new container with `podman`, if failed in the middle of the copy due to disk overflow, leaves unfinished container layer stray.
To avoid obliging the application (or the end user) to take care of such possible leaks, cleanup is added.
The exact scenario of reproducing the leak with current implementation is simple (and in my case the leak was fast, as my disk is almost always close to full):
1. Fill almost all disk (e.g. with `dd`).
2. Try to start new container using the image whose size larger than the …

Remove unfinished VFS layer if its creation fails.

---

layers.go
layers_ffjson.go
pkg/tarlog/tarlogger.go
pkg/tarlog/tarlogger_test.go

Add a field to the `Layer` structure that lets us make note of the set of UIDs and GIDs which own files in the layer, populated by scanning the diff that we used to populate the layer, if there was one.  This could eventually be used to decide how many UIDs and GIDs we need to map into a container in order to start a container based on a given image.

Keep track of the UIDs and GIDs used in applied layers

---

drivers/overlay/overlay.go

This should cause the kernel to clear any leaked mount points into other
containers.
Also create the merged directory every time you attempt to create it.

Remove merged directory when it is unmounted

---

Makefile
docs/Makefile

We want to create a containers-storage package which can install the man pages.
This package will be pulled in via containers-common.

Add support for installing man pages

---

drivers/overlay/overlay.go

we compute d.dir(id) twice, but store the value the first time. use the cached value instead.
Signed-off-by: Peter Hunt <pehunt@redhat.com>

overlay: fix small piece of repeated work

---

Makefile
go.mod

Go 1.13.x isn't sensitive to the GO111MODULE environment variable
causing builds to not use the vendored sources in ./vendor. Force builds
of module-supporting go versions to use the vendored sources by setting
-mod=vendor.
Verified in a fedora:rawhide container.

go build: use `-mod=vendor` for go >= 1.11.x

---

drivers/overlay/overlay.go

Vivek Goyal says that we should not be touching the internal WorkDir/work directory.
This is internal to the kernel and should not be modified.  I believe this was done
to make sure that the "/" of the container is writable by the root user of the user
namespace that is running the container.  Changing the ownership of the diffDir
should give us the same behavior and is safe to do.

We should not be touching internal work dir

---

layers.go

Before applying mount counts that we've just loaded, reset all of the
counts.
If a layer that we thought was mounted was unmounted by another process,
there won't be a record of it in the mounts list any more, so we
wouldn't reset the mount count on our record for that layer.
Signed-off-by: Nalin Dahyabhai <nalin@redhat.com>
pick of: https://github.com/containers/storage/pull/399
per: https://github.com/containers/storage/pull/399#issuecomment-516153182

[CRI-O 1.14] loadMounts(): reset counts before merging just-loaded data

---

drivers/overlay/overlay.go
drivers/vfs/driver.go

This pull request allows a user to not have to specify the storage driver for the ignore_chown_errors option.
Signed-off-by: Kevin Pelzel <kevinpelzel22@gmail.com>

Nonspecific storage driver for ignore_chown_errors option

---

drivers/fsdiff.go
drivers/overlay/overlay.go
drivers/vfs/driver.go

When running with readonly additional stores, containers/storage is trying to
create directories that already exists with the correct UIDs. This causes
buildah/podman to throw an error when committing an image.
This fix will allow buildah/podman to work with readonly additional image stores.

Don't chown unless you have to

---

drivers/btrfs/btrfs.go
drivers/windows/windows.go

Since now we always set the "ro" mount option, we need to ignore
these options on drivers that do not support them.

Ignore ro mount options in btrfs and windows drivers

---

images.go
store.go

Wrap the ID or the digest to ErrImageUnknown errors to avoid ambiguity
which image is unknown.  Consumers of the storage library may have
multiple subsequent calls to the storage API where it can be unclear
which image is unknown.  Wrapping the ID and digest attempts to avoid
this ambiguity.
Related-to:    github.com/containers/libpod/issues/2979
@giuseppe @nalind @rhatdan PTAL

wrap ID or digest to ErrImageUnkown errors

---

cmd/containers-storage/create.go
store.go
tests/image.bats

Images don't have to have layers, so they don't have to have top layers, and we shouldn't return an error when attempting to determine the size of such an image.

ImageSize: don't get tripped up by images with no layers

---

pkg/tarlog/tarlogger.go

Commit d85da31 enabled raw accounting which is not needed for the
purpose of the tarlogger.  Disable the raw accounting to reduce the
memory footprint considerably (factor of 10 in some cases).
Fixes: #433
Inital-report: github.com/cri-o/cri-o/issues/2847

tarlogger: disable raw accouting

---

pkg/lockfile/lockfile_unix.go

We're seeing some panics with Podman on Ubuntu 19 in this code, and debugging without knowing what's going wrong is very difficult.

Do not discard errors when panicing on lockfile open

---

.travis.yml
contrib/cirrus/lib.sh
docs/containers-storage.conf.5.md
go.mod
pkg/config/config.go
pkg/config/config_test.go
pkg/parsers/kernel/kernel_windows.go
storage.conf
store.go

Storage options are really driver specific and it is when distributions set defaults, they
should not effect the user if he changes the default driver.  By moving the storage options
to be driver specific, we can make sure all drivers only document and support their options.

Move storage options to driver specific entries

---

pkg/archive/archive.go
pkg/fileutils/fileutils.go
pkg/fileutils/fileutils_test.go

The `pure` indicator for a match now returns `true` if it's the only
one. This additional information will be used by consumers to decide
more fine-granular if a match can be excluded completely or not.
Needed by https://github.com/containers/buildah/pull/1914

Add pure file matches indicator

---

pkg/archive/archive.go
pkg/fileutils/fileutils.go
pkg/fileutils/fileutils_test.go

This is a follow up of https://github.com/containers/storage/pull/443, because the information of how many matches we have is not sufficient enough to fix the issue in https://github.com/containers/buildah/pull/1914. :innocent: 
We now add the information if an match has been excluded or not, which is
needed for more fine-granular filepath matching.

Add excluded information to matches

---

drivers/driver_linux.go
drivers/overlay/overlay.go

if a mountProgram is specified, check that the file system is already
mounted using the FUSE magic number instead of overlay.  It enables
using fuse-overlayfs on top of overlay.
Closes: https://github.com/containers/storage/issues/447

overlay: check for FUSE when using mountProgram

---

drivers/overlay/overlay.go

when a mountProgram is used, attempt to unmount the file system using
fusermount or fusermount3.
If the FUSE writeback cache is used (fuse-overlayfs uses it by default
since version 0.5), some changes might not be flushed from the kernel
to the FUSE file system.
Using umount we could lose these changes as the file system is
terminated before these changes are visible to the FUSE file system.
Going through fusermount|fusermount3 instead makes sure FUSE flushes
all the pending requests before the file system is unmounted.
If the fusermount attempts fail, make sure the file system is flushed
before being unmounted.

overlay: use fusermount to unmount FUSE file systems

---

drivers/copy/copy_linux.go
pkg/archive/archive_linux.go
pkg/archive/changes_linux.go

Some platforms store s.Rdev as unit32, translate to unit64 so it
will compile.
Also add function to make it clear that the object is a whiteout object.

Fix to be able to build on  FTBFS on mipsel

---

pkg/fileutils/fileutils.go
pkg/fileutils/fileutils_test.go

*We all know that every good improvement has to split-up
into three PRs, right?* :innocent: 
This information is needed as well if we want to match
in a way that the last match has the highest priority.
@vrothberg PTAL, I think we're now somewhat fine with
the API, see https://github.com/containers/buildah/pull/1914

Add indicator for last matched result

---

images.go
images_ffjson.go
images_test.go

This commit adds a new `NamesHistory` field to the `images.json`, which
is basically a deduped list of names the image had in the past. The
first entry of the list is the latest history entry.
The main use case for this feature is to tell the end-user which
names/tags an image had in the past if it does not contain any `names`
any more.
Detailed use case:
1. Pulling `image:v1` into the local registry: `names: [ "image:v1" ]`
2. Pushing a new image as `image:v1` into the remote registry
3. Pulling `image:v1` again into the local registry:
- first image: `names: [ "image:v1" ]`
- previous v1 image: `names: [], names-history: [ "image:v1" ]`
4. An consumer of the storage API can now process the image name and
still display `image` as REPOSITORY, like:
Before:
```
> podman images
REPOSITORY …
```

Add names-history support

---

utils.go

Currently we are throwing lots of files/directories into the
top level of /run/user/UID/  And this makes it difficult to cleanup.
Switching to using /run/user/UID/containers, makes it easier and cleaner.

Move runroot containers storage into containers directory

---

drivers/copy/copy_linux.go
drivers/vfs/copy_linux.go
pkg/archive/archive.go
pkg/archive/changes.go
pkg/archive/changes_linux.go
pkg/system/xattrs_linux.go
pkg/system/xattrs_unsupported.go

Preservation of user.* xattrs is supported by most (if not all) other
drivers, and it's especially useful for containers that run under a
PaX kernel where "user.pax.flags" is used to store PaX flags.
Signed-off-by: Zac Medico <zmedico@gmail.com>

VFS support for user.* xattrs

---

pkg/archive/archive.go
pkg/archive/changes_linux.go
pkg/system/xattrs_linux.go
pkg/system/xattrs_unsupported.go

This should avoid the following panic in Lgetxattr:
panic: runtime error: makeslice: len out of range
Fixes: 0da4bc60b3ba ("pkg/archive: strictly handle errors reading xattrs")
See: https://travis-ci.org/containers/buildah/jobs/617652963
Signed-off-by: Zac Medico <zmedico@gmail.com>

pkg/archive: limit user xattr value size to math.MaxUint16 bytes

---

docs/containers-storage.conf.5.md
pkg/config/config.go
pkg/config/config_test.go
storage.conf

Remove all references to the option in man pages in default configuration.

Overlayfs has dropped support for skip_mount_home options

---

pkg/system/xattrs_linux.go

Implementation references:
- Moby: https://github.com/moby/moby/blob/master/pkg/system/xattrs_linux.go
If [lgetxattr(2)](https://linux.die.net/man/2/lgetxattr) always returns `-1` on any failure, then we cause a runtime panic in L15:  `dest = make([]byte, sz)`
- runc: https://github.com/opencontainers/runc/blob/master/libcontainer/system/xattrs_linux.go
Looks more correct to me.
Relates to: https://github.com/containers/buildah/pull/1998, https://github.com/containers/storage/pull/470, https://github.com/moby/moby/pull/40283

Fix possible runtime panic in Lgetxattr

---

pkg/chrootarchive/archive_unix.go

Make sure that the created pipe is closed on all return paths.

chrootarchive: invokeUnpack: close pipe on all return paths

---

drivers/overlay/overlay.go

Note that such images can now be stored but they cannot be
pushed yet.  Supporting both use cases would be ideal for
source-container images that are known to have a large number
of layers, likely exceeding the current limit of 127 layers.
This limit is inherited from Docker to proactively restrict the
amount and size of arguments passed when mounting.  All (lower)
layers must be specified at mount-time but we only have one page
to pass them.

overlay: allow storing images with more than 127 layers

---

layers.go
store.go

The layer store gets memoized in any case so we can skip the initial
setup on store load.

Lazy initialize the layer store

---

tests/layers.bats

As a follow-up of #489 we now add an integration test which adds an
image with a decent amount of layers.

Add integration tests for images with a lot of layers

---

Makefile

The unit tests should not download dependencies ad-hoc but use the local
vendored sources for sake of reproducibility.

Use -mod=vendor for running unit tests

---

pkg/system/rm.go

In terms of overlay, we see a lot of flakes in CRI-O CI because there is
no mount available any more, but the directory to be removed is still busy.
To avoid such failure cases we now give the system more time/retries.
---
I saw during debugging no wrong behavior, it was just about a timing
issue during unmount because I think that the disk pressure is pretty
high when running the CRI-O integration tests in parallel.

Give devices more time/retries to remove mounts

---

docs/containers-storage.conf.5.md
drivers/overlay/overlay.go

Currently users get an error message saying overlay is not supported on specific
drivers, but their is no information about the mount_program in the error
messages.  This PR adds a mention of this so that users can investigate the use
of the mount_program.
Also add information to the containers-storage.conf man page to document when
the mount_program is required to be used for an overlay driver.

Add better documentation for the mount_program in overlay driver

---

drivers/btrfs/btrfs.go

rootless podman does not work correctly with btrfs backend since unprivileged subvolume deletion fails: https://github.com/containers/libpod/issues/3963 https://github.com/containers/libpod/issues/4764
This commit fallbacks to rm/rmdir syscalls if subvolume deletion ioctls fails
so that unprivileged user can delete their owned subvolumes.

drivers: btrfs: Allow unprivileged user to delete subvolumes

---

pkg/config/config.go

Overlay and overlay2 drivers are the same, but we
were not procesessing mount options correctly for overlay2.

Handle mount options for overlay2 driver.

---

drivers/overlay/overlay.go

now fuse-overlayfs supports running without an upper dir so it doesn't
need to be treated specially.

overlay: drop fuse-overlayfs exception

---

drivers/driver.go
drivers/overlay/overlay.go
layers.go
pkg/mount/mounter_linux.go
store.go

A follow-up of https://github.com/containers/storage/pull/522, especially reverting the API break.

Revert API break due to lint fixes

---

layers.go
store.go

The `layerstore.Load()` on `new[RO]LayerStore` required a held lock on
store initialization. Since the consumers of the layer storage already
call `Load()`, it should not be necessary to lock on initialization of
the layer store.

Remove locking from layer store creation

---

pkg/reexec/command_linux.go

it can lead to a race condition where the process is killed even if
the parent process is still running.
It can happen as the parent in the prctl(PR_SET_PDEATHSIG) case is
considered the *thread* that created the process.  In the case of the
Go runtime the thread could be freed by the runtime at any time
causing the re-execed process to receive the SIGTERM.

reexec: drop Pdeathsig

---

pkg/homedir/homedir_linux.go
pkg/homedir/homedir_others.go
pkg/homedir/homedir_test.go
pkg/homedir/homedir_unix.go
pkg/homedir/homedir_windows.go
store.go
utils.go

pkg/homedir is a fork from docker/docker and part of un-dockering the  
direct dependencies of the containers projects.  There is nothing wrong
at all with the Docker packages but there is an increasing risk of     
non-deterministic behavior as Docker does not provide a go module and  
it's release related only to the binary but not to the go libraries.   
Enforcing control over that will prevent us from regressions in the    
future.                                                                
c/storage seems like the best place for this package since it's at the 
very end of the containers/ dependency chain.                          
Note that all forked files have a copyright note to correctly attribute
the original authors. …

add pkg/homedir

---

storage.conf

The extra period was introduced in 939bd74869 (#177).

storage.conf: Fix "the base. device." typo

---

docs/containers-storage.conf.5.md
storage.conf
store.go
utils.go

This allows rootless admins to setup alternative
paths to content in the homedir.
Rootless users on NFS homedirs will not be allowed to run
podman, if an admin wants to setup alternative directory say
in /var/tmp on local storage, they could configure the storage.conf
file and then all users would automatically get storage in /var/tmp.
Signed-off-by: Qi Wang <qiwan@redhat.com>

Add `rootless_storage_path` directive to storage.conf

---

utils.go
utils_test.go

move the assignment of rootless_storage_path out of `else` block to make the config work even the graphroot is empty.
fix the path match error
Signed-off-by: Qi Wang <qiwan@redhat.com>

fix else case for rootless storage path and path match

---

pkg/ioutils/fswriters.go
pkg/ioutils/fswriters_linux.go
pkg/ioutils/fswriters_unsupported.go

since we don't care of other inode attributes, but only those required
to retrieve the data, use the slightly faster fdatasync.

ioutils: use Fdatasync instead of Sync

---

pkg/system/xattrs_linux.go

`lgetxattr(2)` man page says:
> If size is specified as zero, these calls return the  current  size  of
> the  named extended attribute (and leave value unchanged).  This can be
> used to determine the size of the buffer that should be supplied  in  a
> subsequent  call.   (But, bear in mind that there is a possibility that
> the attribute value may change between the two calls,  so  that  it  is
> still necessary to check the return status from the second call.)
The current code does not handle the "bear in mind" case, i.e. when
the size changes between the two calls, and the new size is larger.
Fix the above problem, and slightly simplify the code.
The current code
* is hard to read (at least for me, that is);
* is suboptimal (always calls `unix.Llistxattr()` twice);
* doesn't handle …

pkg/system: fix/improve xattr functions

---

pkg/lockfile/lockfile_unix.go

do not flush the modified metadata to disk each time the store is
modified.
It is not needed for other processes stat'ing the lock file to see the
updated mtime.
introduced with commit 9b0633295b55d9b52d909a4fb8e3b6e84265c2cf

lockfile: drop call to unix.Fsync

---

pkg/mount/flags_linux.go
pkg/mount/mount.go
pkg/mount/mount_unix_test.go
pkg/mount/mounter_freebsd.go
pkg/mount/mounter_linux.go
pkg/mount/mounter_linux_test.go
pkg/mount/mounter_solaris.go
pkg/mount/mounter_unsupported.go
pkg/mount/mountinfo.go
pkg/mount/mountinfo_linux.go
pkg/mount/mountinfo_linux_test.go
pkg/mount/sharedsubtree_linux.go
pkg/mount/sharedsubtree_linux_test.go
pkg/mount/unmount_unix.go
pkg/mount/unmount_unsupported.go

This tries to bring `pkg/mount` package to a better shape, mostly reshuffling things here and there, removing redundant and excessive calls to parse `/proc/self/mountinfo`, etc.
Please see individual commits for detailed descriptions.
:warning: **This needs a very thorough review**
PS In fact, this might fix some bugs, too, since reading `/proc/self/mountinfo` from the kernel proved to be unreliable/racy. In case there are multiple mounts and unmounts happening while reading /proc/self/mountinfo, the kernel can only give you half the mounts (if you're curious, see https://github.com/kolyshkin/procfs-test for more details and repro).
PPS Once this lands, I want to optimize the mountinfo parser which is still used for at least `Mount()`. Probably makes sense to also drop Solaris support.

pkg/mount: optimize/cleanup

---

pkg/mount/mountinfo_linux.go
pkg/mount/mountinfo_linux_test.go

The mountinfo parser implemented via `fmt.Sscanf()` is slower than the one
using `strings.Split()` and `strconv.Atoi()`. This rewrite helps to speed it
up to a factor of 8x, here is a result from go bench:
> BenchmarkParsingScanf-4            300          22294112 ns/op
> BenchmarkParsingSplit-4           3000           2780703 ns/op
I also tried other approaches, such as using `fmt.Sscanf()` for the first
three (integer) fields and `strings.Split()` for the rest, but it slows
things down considerably:
> BenchmarkParsingMixed-4           1000           8827058 ns/op
Note the old code uses `fmt.Sscanf`, when a linear search for '-' field,
when a split for the last 3 fields. The new code relies on one single
split.
I have also added more comments to aid in future development.
Finally, the …

pkg/mount: mountinfo parser speed up

---

drivers/chown.go
drivers/chown_unix.go
go.mod
go.sum
vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
vendor/github.com/opencontainers/selinux/pkg/pwalk/README.md
vendor/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go
vendor/modules.txt

This makes use of `pwalk.Walk()` (introduced in https://github.com/opencontainers/selinux/pull/89)
for recursive `Chown`, and also optimizes `drivers/platformLChown()` a bit, following the discussion at https://github.com/containers/storage/pull/216/commits/2df72f37c652520d994c4aa42d1ec583ef6ceaaa#r387867583
TODO:
@rhatdan @giuseppe PTAL

Faster Chown

---

pkg/mount/mount.go

The function `fileutils.ReadSymlinkedDirectory` makes `mount.Mounted()`
fail if the mount is a file. We now only check that if the mount is a
directory to allow handling files in `mount.Mounted()`.

Make mount.Mounted() capable of handling files

---

docs/containers-storage.conf.5.md
store.go

when the env variable is set, use its value for locating the user
configuration file.

config: honor XDG_CONFIG_HOME

---

pkg/fileutils/fileutils.go
pkg/mount/mount.go

Commit 90513cbb96a7 introduced a regression as specified mountpoints
must be normalized (e.g., "" -> "/") before we can deal with them.
Instead of working around the fileutils package and special casing
files, add a new `fileutils.ReadSymlinkedPath` which can work with
directories and files.

mount.Mounted: normalize mountpoints

---

store.go
utils.go

avoid reloading the same configuration multiple times if the file was
not modified.

store: memoize ReloadConfigurationFile

---

go.mod
go.sum
store.go
vendor/github.com/hashicorp/errwrap/LICENSE
vendor/github.com/hashicorp/errwrap/README.md
vendor/github.com/hashicorp/errwrap/errwrap.go
vendor/github.com/hashicorp/errwrap/go.mod
vendor/github.com/hashicorp/go-multierror/.travis.yml
vendor/github.com/hashicorp/go-multierror/LICENSE
vendor/github.com/hashicorp/go-multierror/Makefile
vendor/github.com/hashicorp/go-multierror/README.md
vendor/github.com/hashicorp/go-multierror/append.go
vendor/github.com/hashicorp/go-multierror/flatten.go
vendor/github.com/hashicorp/go-multierror/format.go
vendor/github.com/hashicorp/go-multierror/go.mod
vendor/github.com/hashicorp/go-multierror/go.sum
vendor/github.com/hashicorp/go-multierror/multierror.go
vendor/github.com/hashicorp/go-multierror/prefix.go
vendor/github.com/hashicorp/go-multierror/sort.go
vendor/modules.txt

DeleteContainer() does most of its heavy lifting in a number of goroutines.  Previously, if any of them returned an error result, that result was returned to the caller immediately, and DeleteContainer()
would release any locks that it had acquired as part of that.  This could all happen while other goroutines were still running, and some of those goroutines depended on having those locks held until they finished their work, and would panic() when they detected that the locks had been released out from under them.
Fixes https://github.com/containers/storage/issues/575.

DeleteContainer(): wait for all goroutines

---

pkg/unshare/unshare.c
pkg/unshare/unshare_unsupported_cgo.go

Go refuses to compile a subpackage with `CGO_ENABLED=1` if there is a `*.c` file but no `import "C"`.  OTOH if we did have an `import "C"`, the Linux-only code would fail to compile.
So, satisfy the Go compiler by using `import "C"` but `#ifdef`-ing out all of the code.

Fix CGo builds on non-Linux

---

contrib/cirrus/lib.sh
contrib/cirrus/setup.sh
tests/test_runner.bash

We now run the bats jobs in parallel to have a faster test output.

Run bats jobs in parallel

---

pkg/lockfile/lockfile.go

This partially fixes a CRI-O panic on container restore if the sandbox
could not restored successfully and CRI-O tries to remove the sandbox
afterwards. To not have the need to recover the panic in CRI-O (or
possible other consumers of this library) we should avoid panic'ing here
and stick to error handling.
Reproduce the panic with the latest CRI-O master:
```json
{
"metadata": {
"name": "nginx-sandbox",
"namespace": "default",
"attempt": 1,
"uid": "hdishd83djaidwnduwk28bcsb"
},
"log_directory": "/tmp",
"linux": {}
}
```
```
> sudo ./bin/crio
> sudo crictl runp sandbox.json
panic: attempted to update last-writer in lockfile without the write lock
goroutine 86 [running]:
github.com/containers/storage/pkg/lockfile.(*lockfile).Touch(0xc0007149b0, 0xc0006e4000, 0x0) …
```

Add docs about when locks can panic

---

go.mod
go.sum
store.go
vendor/github.com/hashicorp/errwrap/LICENSE
vendor/github.com/hashicorp/errwrap/README.md
vendor/github.com/hashicorp/errwrap/errwrap.go
vendor/github.com/hashicorp/errwrap/go.mod
vendor/github.com/hashicorp/go-multierror/.travis.yml
vendor/github.com/hashicorp/go-multierror/LICENSE
vendor/github.com/hashicorp/go-multierror/Makefile
vendor/github.com/hashicorp/go-multierror/README.md
vendor/github.com/hashicorp/go-multierror/append.go
vendor/github.com/hashicorp/go-multierror/flatten.go
vendor/github.com/hashicorp/go-multierror/format.go
vendor/github.com/hashicorp/go-multierror/go.mod
vendor/github.com/hashicorp/go-multierror/go.sum
vendor/github.com/hashicorp/go-multierror/multierror.go
vendor/github.com/hashicorp/go-multierror/prefix.go
vendor/github.com/hashicorp/go-multierror/sort.go
vendor/modules.txt

DeleteContainer() does most of its heavy lifting in a number of
goroutines.  Previously, if any of them returned an error result, that
result was returned to the caller immediately, and DeleteContainer()
would release any locks that it had acquired as part of that.  This
could all happen while other goroutines were still running, and some of
those goroutines depended on having those locks held until they finished
their work, and would panic() when they detected that the locks had been
released out from under them.
Signed-off-by: Nalin Dahyabhai <nalin@redhat.com>

[crio-release-1.17] DeleteContainer(): wait for all goroutines

---

drivers/overlay/overlay.go

make sure the work dir is also recreated with the diff dir.
When using index=on, overlay records a reference to the upperdir inode
into work/index, and raises an error if on a successive mount there is
a mismatch between what is stored in the work/index xattr and the
upper dir inode.
Closes: https://github.com/containers/libpod/issues/5816

overlay: recreate workdir on UpdateLayerIDMap

---

store.go

Add an interface to sets the default storage configuration to the specified path
In some scenarios, the default configuration path of the storage needs to be changed.
Therefore, provided an interface to specify the configuration file path.
Signed-off-by: leizhongkai <leizhongkai@huawei.com>

storage:provided an interface to specify the configuration file path

---

layers.go

r.lookup references r.byid, r.byname, and r.idindex to lookup a layer. The resulting Delete() function call misses the `delete(r.byname, name)` causing crio to say a layer is in use, when it actually is not.

internalDelete needs the r.byname id deletion

---

containers.go

The type of container flag is map[string]interface{}.
json unmarshal from container.json will convert []string to []interface{}, thus MountOpts will be lost.
We should assert it in case lost MountOpts data
Signed-off-by: blade <blade.shen@ucloud.cn>

lost mountopts when read json from file

---

pkg/unshare/unshare.c

if unshare is creating a new mount space, attempt first to create a
read only bind mount from /proc/self/exe instead of copying it to a
memfd.
The code was copied from runc/libcontainer.
It has two advantages:
- it requires less memory since we don't need a copy of the executable
in memory.
- it is much faster ("buildah unshare" is twice faster).

unshare: try a bind mount before copy /proc/self/exe

---

drivers/overlay/overlay.go

if "ro" is specified when mounting overlay, configure overlay without
any upper layer and workdir so the file system doesn't attempt to
write any file.
Closes: https://github.com/containers/buildah/issues/2359
Signed-off-by: Giuseppe Scrivano <giuseppe@scrivano.org>

overlay: honor ro option

---

drivers/overlay/check.go

Fuse-overlay now has an option fsync=0, which kernel overlay does
not support, when I changed from fuse-overlay, to regular with
the fsync=0 flag set, I had a hard time diagnosing what was going
wrong. This information would have helped.

Add mountoptions to help figure out why mount failed

---

drivers/devmapper/deviceset.go
drivers/devmapper/driver.go
drivers/overlay/overlay.go
pkg/idtools/idtools_unix.go
pkg/idtools/idtools_windows.go
store.go

A couple of fixes; similar to https://github.com/moby/moby/pull/35618
`os.MkdirAll()` function returns "not a directory" error in case a
directory to be created already exists but is not a directory
(e.g. a file). MkdirAllNewAs function do not replicate the behavior.
This is a bug since it is expected to ensure the required directory
exists and is indeed a directory, and return an error otherwise.
This subtle bug keeps lurking in because error checking for `Mkdir()`
and `MkdirAll()` is slightly different wrt `EEXIST`/`IsExist`:
- for `Mkdir()`, `IsExist` error should (usually) be ignored
(unless you want to make sure directory was not there before)
as it means "the destination directory was already there";
- for `MkdirAll()`, `IsExist` error should NEVER be ignored.
This commit removes …

Fix MkdirAll* and its usage

---

drivers/overlay/overlay.go
drivers/vfs/driver.go

if the DiffGetter interface is provided, the layer store doesn't need
to mount the layer to access the files for tar-split.

overlay: implement DiffGetter

---

drivers/devmapper/deviceset.go

Stat_t on MIPS uses 32-bit fields for Dev and Rdev, so we need to cast these to uint64
Inpiration from https://github.com/moby/moby/pull/37490
Example build failure log: https://buildd.debian.org/status/fetch.php?pkg=golang-github-containers-storage&arch=mips64el&ver=1.15.8%2Bdfsg1-1&stamp=1580872314&raw=0

unbreak build on mipsen

---

docs/containers-storage.conf.5.md
drivers/overlay/overlay.go
hack/git-validation.sh
pkg/config/config.go
pkg/config/config_test.go
storage.conf
store.go

Certain workloads, we would like to eliminate the mounting of containers-storage as private.
Running containers within containers for example.
This looks like it was accidently removed in the past, since there was still partial
implementation.

Add back skip_mount_home

---

pkg/lockfile/lockfile_unix.go

We are getting reports of SELinux failures on leaked file descriptors.

Lock files should be CLOEXEC

---

.cirrus.yml

Stop using golang 1.12

---

utils.go
utils_test.go

[`XDG_*` directories](https://github.com/moby/moby/issues/40708) will be a big question. But please do not use `/run/user` as fallback directory, use something like `/tmp/storage-user` instead.

Use temp instead of run as fallback directory for rootless mode

---

storage.conf

toml/json requires quotes around string objects.

Just uncommenting this line blew up on me

---

cmd/containers-storage/main.go
store.go
store_test.go

New interface for deleting already-created Store object
When the store is not needed, it is neccessary to remove
it and release the memory
Signed-off-by: yangfeiyu <yangfeiyu20102011@163.com>

new interface Free for deleting Store object

---

docs/containers-storage.conf.5.md
drivers/devmapper/device_setup.go
drivers/devmapper/deviceset.go
pkg/config/config.go
storage.conf

As the number of devices increase the size of the metadata
needs to be modified.

Store the pvcreate --metadatasize option in storage.conf

---

layers.go

We want to block the mounting of additional stores, for
read/write, since they will not have any containers associated
with them.  But if a user is mounting an image for read/only
access then their is no reason to block the mount.

Allow mounting of Non Read Write images read/only

---

drivers/overlay/overlay.go

Currenty overlay is mounting in the case where there are no lowers
on a read/only mount iff their is no mount_program. i
This situation might make sense for containers but in the case of images
the image should still be mounted. Having an empty layer makes little sense
if it is read/only.

When mounting images we have no lowers, but still need to mount

---

layers.go

Fix the logic in an anon-func looking for the `ro` option to allow for
mounting images that are set as read-only.

layer mount: fix RO logic

---

userns.go
userns_test.go

when an explicit idmapping is specified, the host id must be taken
from the available range of IDs.

userns: fix available range with explicit idmapping

---

layers.go

Fix ISSUE #664 
In some special case, residual resources in layerStore when remove an image may cause image export failed. These residual resources  also lead memory leak. So, it is nessary to clean all resources with the image remove.
Signed-off-by: zvier <zvier20@gmail.com>

clean residual resources in layerStore when remove an image

---

pkg/unshare/unshare.go

do the potentially expensive user lookup function just once.

unshare: memoize HomeDir()

---

drivers/devmapper/deviceset.go

Stat_t on MIPS uses 32-bit fields for Dev and Rdev, so we need to cast these to uint64
Turns out the change in 07171909b06e27a6c6b7f918aa981bec0c724f20
is incomplete and an additional line needs a cast.
Inpiration from moby/moby#37490
Example build failure log: https://buildd.debian.org/status/fetch.php?pkg=golang-github-containers-storage&arch=mips64el&ver=1.20.2-1&stamp=1594477648&raw=0Signed-off-by: Reinhard Tartler <siretart@tauware.de>
Signed-off-by: Reinhard Tartler <siretart@tauware.de>

unbreak build on mipsen harder

---

pkg/archive/archive.go

archive: fix the bug of ReadSecurityXattrToTarHeader
The xattr of hdr will lose when the security.ima
and security.capability both have value.
Signed-off-by: yangfeiyu <yangfeiyu20102011@163.com>

archive: fix the bug of ReadSecurityXattrToTarHeader

---

.cirrus.yml

An errant behavior change in Cirrus-CI between Jul. 28th and Aug. 3rd caused nested variable references to not resolve properly in `only_if` matrix  filters.  An attempt to correct the behavior made things worse, and so the old (pre-July 28) behavior was re-established.  In other words, nested variables in `only_if` will **NOT** be dereferenced, so they must match the nested variable name, not it's value.  I've updated the nearby comment to reflect the current situation.
Also I added a `success` task, which can be marked as `required` in Github's branch protection.  This will help guarantee that specific tests pass, before allowing PRs to merge.

Cirrus: Fix matrix filter

---

images.go
pkg/stringutils/stringutils.go
store.go
tests/delete-layer.bats

currently it is not possible to delete a mapped layer as it is always
referenced by the image.
Change it allow deleting the mapping if it is not used by any
container or other layers.
It will be useful in CRI-O as a lot of thrown away containers will be
created and the mapped images would keep growing without a way of
cleaning them up.

store: support mapped layers deletion

---

userns.go
userns_test.go

when it finds multiple available ranges, make sure the host id is
correctly initialized.

userns: make sure host id is not always 0

---

docs/containers-storage.conf.5.md
utils.go
utils_test.go

Expand env variables in paths
Part of https://github.com/containers/buildah/issues/2311
Signed-off-by: Ashley Cui <acui@redhat.com>

Allow env variables in graphroot and runroot

---

pkg/archive/archive.go
pkg/archive/archive_test.go
pkg/archive/diff.go

avoid creating a new buffer for each file in the archive but
preallocate a 1M buffer.  Another advantage of having a bigger buffer
is that we reduce the number of read and write syscalls.

archive: preallocate a buffer for io.Copy

---

pkg/fileutils/fileutils.go

When building the regex that matches patterns, the ending bit that matches items below directories that match the pattern should be built using the OS-specific path separator, which is not always `/`.

fileutils.Pattern.compile(): end the regex with the right path separator

---

docs/containers-storage.conf.5.md
storage_test.conf
utils.go
utils_test.go

Previously only restricted to home, uid, and user
as per https://github.com/containers/buildah/issues/2311#issuecomment-671076880
Signed-off-by: Ashley Cui <acui@redhat.com>

Allow any env variable for graphroot, runroot, storagepath

---

contrib/cirrus/add_second_partition.sh
contrib/cirrus/build_and_test.sh
contrib/cirrus/lib.sh.t
contrib/cirrus/ooe.sh
contrib/cirrus/setup.sh
hack/btrfs_tag.sh
hack/gccgo-wrapper.sh
hack/generate-authors.sh
hack/get_ci_vm.sh
hack/git-validation.sh
hack/gofmt.sh
hack/govet.sh
hack/libdm_tag.sh
tests/helpers.bash
tests/test_drivers.bash
tests/test_runner.bash
vagrant/provision.sh
vagrant/runinvm.sh

It's not possible to run any of the scripts on distributions which do
have `bash` not in `/bin`. This is being fixed by using `/usr/bin/env
bash` instead.

Use `bash` binary from env instead of /bin/bash for scripts

---

drivers/overlay/overlay.go

We have a request from a user who wants to use imagestores and
to be able to update them from podman.
Currently if I setup /var/lib/shared as an additional store
and I attempt update the share with a command like:
Error: lock "/var/lib/shared/overlay-images/images.lock" is not a read-only lock
I can not because Podman is still using the additonal store.
User expected something like:
Error: overlay: Unknown option additionalimagestore
To work.
I looked further and figured overlay.imagestore would work, but it still failed.
This PR allows users to specify additionalimagestores on the command line, and to use
more likely options to make it work.
I also cleanup some of the option parsing in overlay.go to handle overlay, overlay2, and "."
prefixes.
I checked and none of the other drivers use …

Allow users to override imagestores

---

drivers/counter.go

if a previously mounted container was unmounted
externally (e.g. through conmon cleanup for Podman containers), the
ref counter will lose track of it and report it as still mounted.
Closes: https://github.com/containers/storage/issues/697

counter: check for external umounts

---

layers.go

Relate to #705
Signed-off-by: Jeff Zvier <zvier20@gmail.com>

fix goroutine leak with close tatLogger in a defer clause

---

utils.go

It is too risky to add all system options.
This is supposed to work for HPC customers, so we can just
grab this setting if set in system wide settings.

For podman v2.0 we need to use use ignore_chown_errors field if set

---

drivers/devmapper/deviceset.go
drivers/devmapper/devmapper_test.go
drivers/devmapper/driver.go

This is a port of a few upstream PRs:
* https://github.com/moby/moby/pull/34573 devicemapper: remove container rootfs mountPath after umount
* https://github.com/moby/moby/pull/36438 devmapper/Remove(): use Rmdir, ignore errors
* https://github.com/moby/moby/pull/36307 devmapper cleanup improvements
* https://github.com/moby/moby/pull/40056 devmapper: fix unit test
plus a change to use `mount.Unmount` instead of `unix.Unmount` for the sake of better errors.
The port of https://github.com/moby/moby/pull/34573 is pretty important, as it may prevent those nasty EBUSY errors. Others are in the "nice to have" category.
Please see individual commits and/or the above PRs for details.

Devmapper fixes and cleanups

---

.cirrus.yml
contrib/cirrus/build_and_test.sh
tests/test_runner.bash

Previously, VM Images were built from a side-band process tacked onto
containers/podman automation. This has recently been split off into it's
own repository containers/automation_images. This PR makes use of
freshly built images produced using the new workflow. Additionally, to
support testing of a runc -> crun transition, both packages are
installed in the newly referenced images.

Cirrus: Use images from automation_images

---

go.mod
pkg/mount/mountinfo.go

Carry of #720 
Closes: #723 
Commit 1a2847751 (inadvertently?) changed go version in go.mod from 1.13
to 1.15.
A "go <version>" line in go.mod sets minimum go version required for the
package (see [1]). I don't think containers/storage suddenly requires go
1.15+.
Set it to 1.14, which is currently the oldest supported release.
[1] https://golang.org/ref/mod#go-mod-file-go
Since moby/sys/mountinfo v0.2.0, the path does not have to be
normalized, so drop our wrapper.
Note this slightly change the call semantics: previously, a non-existing
path resulting in an error (wrapped ENOENT), while now it will return
"not mounted". The change is intentional -- the call is not to check if
the path exists, it is to check whether it is mounted.

Fix go.mod; simplify pkg/mount.Mounted

---

docs/containers-storage.md

Containers storage is committed to inclusivity, a core value of open source. Historically, there have been technology terms that are problematic and divisive, and should be changed. We are currently taking time to audit our repository in order to eliminate such terminology, and replace it with more inclusive terms. We are starting where we can, with our own code, comments, and documentation. However, some of these terms are currently used within the Linux kernel and must be used as-is at this time. When the kernel maintainers rectify this usage, containers storage will follow suit immediately.
For more information: https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language?sc_cid=701600000011gf0AAA
Signed-off-by: Ashley Cui <acui@redhat.com>

add note regarding problematic language in codebase

---

.gitignore
pkg/archive/archive.go

check the base name of the src and dest,
if they are the same and dest is a directory, should error like cp behavior
```
$ mkdir abc
$ mkdir test
$ touch test/abc
$ cp test/abc .
cp: cannot overwrite directory './abc' with non-directory
```
```
$ docker exec test touch /root/file1
$ mkdir -p /tmp/file1
$ docker cp test:/root/file1 /tmp
cannot overwrite directory "/tmp/file1" with non-directory "/tmp"
```
Fixes: https://github.com/containers/podman/issues/7790
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>

Fixes: sometimes should be the same with the behavior of the cp command

---

hack/spc_ci_test.sh

Some of the tools we install no longer support being built or installed using Go 1.8 or 1.9, so install them using a more current version, then switch to the version specified by the invoking script to run the rest of the builds and tests.

[release-1.11] spc_ci_test.sh: run "make install.tools" with current Go

---

layers.go

The storage cache is not completely cleaned when removing images.
Remove also the entries referencing layers by compressed and uncompressed sums.

layers: on delete clear also the compressed/uncompressed cache reference

---

pkg/archive/archive.go

archive: fix createTarFile loses the IMA attribute
reason: Lsetxattr the xattrs in the end, because system.Chtimes and other operations
may let the file lose IMA attribute
Signed-off-by: yangfeiyu<yangfeiyu20102011@163.com>

archive: fix createTarFile loses the IMA attribute

---

pkg/idtools/parser.go
pkg/idtools/parser_test.go

This leads to people accidently putting characters into options
and not getting back good errors.
Fixes: https://github.com/containers/storage/issues/739

ParseIDMap should not ignore nonDigits

---

layers.go
store.go
utils.go

Golang built in functions like os.Create and others print the name of
the file system object when they fail.  Wrapping them a second time
with the file system object, makes the error message look like crap
when reported to the user.

Stop excessive wrapping

---

drivers/overlay/overlay.go

We are trying to drop buildah and eventually podman to warn by default
Since these warning messages happen all the time, I believe they should be
infos.

Drop Warn to Info for common issues

---

pkg/idtools/idtools.go

Sometimes users are hitting errors caused by insufficient uids/gids
in their user namespace. This is often caused by bad ranges or no ranges
in /etc/subuid and /etc/subgid files.
This PR attempts to improve the error message reporting the failure and
points users at these files.

Mention /etc/subuid and /etc/subgid files in error message

---

store.go

I got fooled by this code, and attempted a PR to clean it up, that
was a mistake.  I assumed that the call should fail if the Container
call failed. But the store.Mount(id, mountlabel) handles container
mounts as well as layer mounts. This means the ID could be a container
or a different layer. When the attempt to read the container fails, we
continue assuming that the id is a layer and attempt to mount it as a layer.
If the id is a container then we grap the toplayer of the container and use
it is as an id.
This PR does not change the functionality of the code, but makes it easier
for future programmers to understand the functionality.

 Cleanup code to explain what is going on here. 

---

drivers/chown_unix.go

go 1.14 and beyond doesn't catch EINTR in the syscall package anymore. This causes manual calls to the syscall package to fail from interrupts, which is really not a failure, as the command should just be retried.
however, the os package does this for us. Luckily, there's an `os.Lchown`
unfortunately, for the other syscall functions, there will need to be a function wrapper, but I believe that should be addressed in a separate PR
Signed-off-by: Peter Hunt <pehunt@redhat.com>

platformLchown: use os package instead

---

store.go
utils.go

Attempting to override the location of the storage.conf file, using
the SetDefaultConfigFilePath for testing is failing in Podman.
This patch will use the replace configuration file.

If caller Sets the DefaultConfigFilePath, we need to use it

---

layers.go
pkg/archive/archive.go

Archive: defer close after DecompressStream to fix resource leak
Signed-off-by: yangfeiyu <yangfeiyu20102011@163.com>

archive: defer close after DecompressStream to fix resource leak

---

contrib/cirrus/lib.sh
contrib/cirrus/setup.sh

Fixes error encountered in #757 CI:
```
[+0546s] Attempt 7 of 7 (retry on non-zero exit):
[+0546s] Reading package lists...
[+0546s] Building dependency tree...
[+0546s] Reading state information...
[+0546s] Calculating upgrade...
[+0546s] The following packages have been kept back:
[+0546s]   base-files linux-gcp linux-headers-gcp linux-image-gcp sosreport
[+0546s]   ubuntu-server
[+0547s] 0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
[+0547s] 1 not fully installed or removed.
[+0547s] After this operation, 0 B of additional disk space will be used.
[+0547s] Setting up grub-efi-amd64-signed (1.142.8+2.04-1ubuntu26.6) ...
[+0547s] mount: /var/lib/grub/esp: special device /dev/disk/by-id/google-persistent-disk-0-part15 does not exist.
[+0547s] dpkg: error processing …
```

Cirrus: Avoid upgrading grub-efi-amd64-signed

---

drivers/chown_unix.go
drivers/copy/copy_linux.go
pkg/archive/archive.go
pkg/archive/changes_linux.go
pkg/system/xattrs_linux.go

This way the error messages are more informative, and the use of the functions are more in-line with the standard ones (from `os). From the other side, it introduces a hassle of properly unwinding the errors (and this is why I hesitated to make this change).
Convert all the users accordingly (assuming there are no users outside of this repo).

system.*xattr: wrap errors into os.PathError

---

drivers/chown_unix.go
pkg/system/chmod.go
pkg/system/lchown.go

The following failure has been observed in CI (see [1], [2]):
storage-chown-by-maps: chown("xxx"): interrupted system call
While chown and chmod should be auto-restartable by the kernel (provided
all the signal handlers are installed with SA_RESTART flag), it looks
like it is not always the case, or there might be some exclusions,
so this should be handled.
Surely, the possibility of getting EINTR is amplified since Go 1.14
introduced async preemptible goroutimes (see [3]), the feature that
is implemented via frequently sending signal 22 to all threads.
Add and use wrappers for Chmod and Lchown that retry on EINTR.
[1] https://github.com/containers/podman/issues/8152
[2] https://github.com/cri-o/cri-o/pull/4310#issuecomment-718361022
[3] https://golang.org/doc/go1.14#runtime
Previous …

chmod/chown: handle EINTR

---

userns.go
userns_test.go

The logic of range subtraction [a,b)-[c,d) can be viewed as intersection
of [a,b) with (-inf, c) and [d, +inf), respectively. This makes the
logic simpler, that we no longer need to check 5 different cases.
It also fixes bugs that returns incorrect range.
Closes #763
Signed-off-by: Kan Li <likan@google.com>

Simplify ID range subtraction logic and bug fixes.

---

utils.go

Ref: #733
With this PR the usage of rootless_storage_path from user configuration is restored.
The order of precedence in which the storage path for rootless run is taken is as follows:
1. graphroot defined in $HOME/.config/containers/storage.conf
2. rootless_storage_path defined in $HOME/.config/containers/storage.conf
3. rootless_storage_path defined in /etc/containers/storage.conf
4. podman default ($HOME/.local/share/containers/storage)

Restore usage of rootless_storage_path in user storage.conf

---

pkg/chrootarchive/archive.go

Fix CVE-2019-14271 loading of nsswitch based config inside chroot under Glibc
Based on code from moby
https://github.com/moby/moby/pull/39612/files

Need to load nsswitch based config outside of container

---

docs/containers-storage.conf.5.md
drivers/driver.go
drivers/overlay/overlay.go
pkg/archive/archive.go
pkg/archive/archive_ffjson.go
pkg/archive/archive_linux.go
pkg/archive/archive_other.go
pkg/archive/archive_test.go
pkg/archive/archive_unix.go
pkg/archive/archive_windows.go
pkg/archive/diff.go
pkg/config/config.go
storage.conf
store.go

force_mask sets a permission mask used for the new files and directories.
It is useful for using a NFS share for the rootless storage.  It requires this change in fuse-overlayfs:
permissions_xattr, if it is set then it for each file write its original permissions to the specified extended attribute.
Together with force_mask= it allows to use NFS as a backing store for rootless containers:
https://github.com/containers/fuse-overlayfs/pull/246
```
[storage]
driver = "overlay"
graphroot = "/mnt/nfs/home/storage"
[storage.options]
mountopt = "xattr_permissions=2"
[storage.options.overlay]
force_mask = "0755"
ignore_chown_errors = "true"
```

storage: add option force_mask= and permissions_xattr=

---

drivers/overlay/overlay.go

When creating a new layer that has a parent, assign the new layer's "diff" directory the same permissions as the parent layer's "diff" directory, rather than the permissions of the parent of its parent layer's "diff" directory.
Before the recent round of changes, that directory would be initialized with 0700 permissions, so layers created by new code on top of layers created by the older version would be marked 0700, and were not usable by UIDs other than 0.
Spotted in CI tests for buildah that try to use overlay to create containers on top of base images that were imported using a slightly older version of podman, for example https://cirrus-ci.com/task/6024517489262592.

overlay: set permissions on "diff" correctly

---

pkg/unshare/unshare.go

We were never using the entry in the /etc/passwd file
if $HOME was not set.

Fix unshare.HomeDir to use entry in /etc/passwd

---

utils.go

Currently rootless users of storage.conf in the home
dir ignore the storage options.

Fix reading of ~/.config/containers/storage.conf

---

docs/containers-storage.conf.5.md
storage.conf
store.go
utils.go

I merged a patch that was a mistake that returned
rootless storage opts early. User had a broken
storage.conf that caused me to get confused.

Revert returning storageOpts

---

pkg/archive/archive.go

handleTarTypeBlockCharFifo() would skip the creation anyway, so let's return earlier and avoid later problems with failing chown/chmod calls.
Reproducer:
1. Configure ~/.config/containers/storage.conf to use the "vfs" driver for a non-root user
2. As non-root run: `podman pull docker.io/library/openjdk:14`
It will fail with:
```
ERRO[0048] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: lchown /dev/initctl: no such file or directory 
```

archive: Skip FIFO creation in userns

---

docs/containers-storage.conf.5.md
docs/containers-storage.md
storage.conf
store.go

Systemd is now complaining or mentioning /var/run as a legacy directory.
It has been many years where /var/run is a symlink to /run on all
most distributions, make the change to the default.
Partial fix for https://github.com/containers/podman/issues/8369

Switch references of /var/run -> /run

---

drivers/overlay/overlay.go
pkg/idtools/idtools.go
pkg/idtools/idtools_test.go

if a single user is mapped in the user namespace, handle it as root.
It is needed for running unprivileged containers with a single user available without being forced to run with euid and egid set to 0.
Needs: https://github.com/containers/fuse-overlayfs/pull/268

idtools: handle single user mapped as root

---

store.go
utils.go

Currently we ignore STORAGE_DRIVER enviroment variable in
rootless mode, always forcing it to be Overlay if fuse-overlay
is installed of vfs.
This patch will respect both the STORAGE_DRIVER and STORAGE_OPT
environment variable if set in rootless mode.

Use STORAGE_DRIVER environment variable in rootless mode

---

drivers/aufs/aufs.go
drivers/btrfs/btrfs.go
drivers/devmapper/driver.go
drivers/driver.go
drivers/overlay/overlay.go
drivers/quota/projectquota.go
drivers/vfs/driver.go
drivers/windows/windows.go
drivers/zfs/zfs.go
pkg/directory/directory.go
pkg/directory/directory_test.go
pkg/directory/directory_unix.go
pkg/directory/directory_windows.go

To convert to CRI stats for CRI-O, we need to improve the performance of finding the disk stats. The current implementation walks the `/diff` directory and adds up the size and inodes.
Luckily, with XFS and project quotas, we can simply query the value.
This PR adds a couple of things, broken into smaller commits:
- updates pkg/directory to have a function GetDiskUsage, which does what directory.Size did, but also counts the inodes
- Add a similar GetDiskUsage function to the projectquota package, but this one queries the quota instead of walking
- Adds a ReadWriteDiskUsage endpoint for all drivers, most of which simply call directory.GetDiskUsage
- updates overlay to call projectquota.GetDiskUsage (if we successfully initialized our quota object)

Improve project quota to support querying disk usage

---

drivers/driver_freebsd.go
pkg/archive/archive_freebsd.go
pkg/homedir/homedir_others.go
pkg/mount/mounter_unsupported.go
pkg/system/mknod_freebsd.go

I added `pkg/archive/archive_freebsd.go` which is copy of `pkg/archive/archive_unix.go` with only one modification as FreeBSD requires `dev` to be `uint64` since 12.0: https://github.com/golang/go/commit/dc6eb200dd59dfedaa5259565b8ef1aa96a39271
I'm not experienced with Go build system and I'm not sure how to avoid this code duplication - I'm open to suggestion.
Ref https://github.com/containers/skopeo/issues/1163

Fix FreeBSD suport

---

cmd/containers-storage/layer.go
docs/containers-storage-get-layer-data.md
docs/containers-storage-list-layer-data.md
docs/containers-storage-set-layer-data.md
layers.go
layers_ffjson.go
store.go
tests/bigdata.bats

similarly to containers and images, add support for storing big data
also for layers, so that it is possible to store arbitrary data when
it is not feasible to embed it in the layers JSON metadata file.
Subset of: https://github.com/containers/storage/pull/775

layers: support BigData

---

drivers/overlay/overlay.go

make sure the metacopy=on mount option is specified when it was
present in the d.options.mountOptions.
It solves a problem where the NaiveDiffer doesn't specify
"metacopy=on" when mounting a different layer and the kernel refuses
to load file attributes (even for root), failing with the error:
kernel: overlayfs: refusing to follow metacopy origin for ...

overlay: force metacopy=on for naivediff

---

drivers/overlay/overlay.go

tested on Fedora Rawhide with kernel
5.11.0-0.rc6.20210204git61556703b610.144.fc34.x86_64
There is currently an issue when context= is specified and the mount
fails with EACCES.  We can drop it once it works in the kernel.

overlay: support native rootless mounts

---

containers.go
drivers/driver.go
drivers/overlay/check.go
drivers/overlay/overlay.go
store.go

add a new class of containers that are not guaranteed to survive a crash.  The advantage of such containers is that storage can be
optimized to skip some synchronizations with the underlying storage.

store: support volatile containers

---

.cirrus.yml
drivers/overlay/overlay.go

Backport https://github.com/containers/storage/pull/815 to release-1.24 to address a BZ.
@rhatdan We'll need a new tag of v1.24 to vendor after this merges

v1.24 Backport: overlay: force metacopy=on for naivediff

---

drivers/overlay/check.go
drivers/overlay/overlay.go

Distributions are shipping metacopy option along with kernels that do
not support it.  We should warn on this situation rather then fail.

We should ignore metacopy option on kernels that do not support it

---

pkg/homedir/homedir_others.go
pkg/homedir/homedir_unix.go

There's already GetDataHome for getting XDG_DATA_HOME and GetConfigHome
for getting XDG_CONFIG_HOME. So add GetCacheHome for getting
XDG_CACHE_HOME, for use by containers/image.
See also containers/image#1142
Signed-off-by: G.I. Doe <gogit@pm.me>

homedir: add GetCacheHome

---

pkg/homedir/homedir_others.go
pkg/homedir/homedir_unix.go

There's already GetDataHome for getting XDG_DATA_HOME and GetConfigHome
for getting XDG_CONFIG_HOME. So add GetCacheHome for getting
XDG_CACHE_HOME, for use by containers/image.
See also containers/image#1142
Signed-off-by: G.I. Doe <gogit@pm.me>

[1.24] homedir: add GetCacheHome

---

drivers/overlay/overlay.go

If the symlinks under the l directory are lost during a
sudden reboot, we can hit an error when grabbing the lower
directories and reading the symlinks before they are recreated
in the Get function. Add a call to recreateSymlinks in this
code path as well.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1921128

Call recreateSymlinks when not found during Readlink

---

Makefile
contrib/cirrus/build_and_test.sh
drivers/aufs/aufs.go
drivers/btrfs/btrfs.go
drivers/devmapper/driver.go
drivers/graphtest/graphtest_unix.go
drivers/graphtest/testutil_unix.go
drivers/vfs/driver.go
drivers/zfs/zfs.go
pkg/archive/archive.go
pkg/archive/archive_test.go
pkg/archive/changes_linux.go
pkg/chrootarchive/archive_test.go
pkg/directory/directory_test.go
pkg/directory/directory_unix.go
pkg/directory/directory_windows.go
pkg/idtools/idtools_unix_test.go
pkg/lockfile/lockfile_test.go
pkg/lockfile/lockfile_unix.go
pkg/mount/mount.go
pkg/mount/mounter_linux_test.go
pkg/mount/sharedsubtree_linux_test.go
utils.go
utils_test.go

Fix a race where the state lock in a Unixy lockfile structure wasn't being used to protect access to all of the structure's state fields, fixing #831.
Fix usage of sync/atomic in the corresponding unit tests to not mix atomic adds and reads with non-atomic reads, something which the race detector complained about.
Start running unit tests again in CI.  It was not intentionally that we stopped doing that.

pkg/lockfile: fix a race and re-enable unit tests

---

drivers/overlay/overlay.go

Currently it is difficult to diagnose mount failures in overlay storage.
This issue is we are not sure of all of the mount options used when
attempting to mount the file system.
This PR adds missing data.

Add more mount information to errors

---

AUTHORS
docs/containers-storage.conf.5.md
types/options.go
types/options_test.go

Fixes containers/podman#9547
The storage driver set in `/etc/containers/storage.conf` was ignored for rootless configurations.
Rootless configurations would use overlay or vfs by default.
If the `STORAGE_DRIVER` environment was variable set, this value would be used instead.
This commit changes this behavior to inherit the driver set in `/etc/containers/storage.conf`.
To inherit the driver in rootless configurations, the driver must be valid in a rootless context.
The valid rootless drivers are btrfs, overlay, and vfs at this time.
To remain consistent with previous behavior, the `STORAGE_DRIVER` environment variable supersedes any driver set in `/etc/containers/storage.conf` and does not need to be a valid rootless driver.
buildah's documentation for the `--storage-driver` command …

Inherit system storage driver in rootless configurations

---

cmd/containers-storage/create.go
drivers/overlay/overlay.go
tests/create-container.bats

overlay creates the directory "$workdir/work/incompat/volatile", not
"$workdir/incompat/volatile".
commit ffe1eb2df5e0ecac7ce794a1925dece6890579c5 introduced the issue.
Closes: https://github.com/containers/podman/issues/9507

overlay: fix path to incompat/volatile

---

.github/dependabot.yml

We now follow the official [dependabot guide][0] for this repository,
which should work with vendoring of go modules, too.
[0]: https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates

Add dependabot.yml configuration file

---

drivers/overlay/overlay.go
drivers/overlay/overlay_cgo.go
drivers/overlay/overlay_nocgo.go
drivers/overlay/overlay_unsupported.go
types/options.go

add a public function to check whether the kernel supports native overlay.
If the existing storage was created using a mount_program, refuse to use the native overlay as they are not fully compatible, e.g. native overlay uses device whiteout files while a mount_program such as fuse-overlayfs could be using a different format to accomodate older kernels where unprivileged users cannot create whiteout devices.
Users will need the equivalent of "podman system reset" to move to native support.

overlay: add detection for overlay support in a user namespace

---

drivers/overlay/overlay.go

if the mount_program is set to the empty string then clear its value
and not use a mount program instead of failing.

overlay: allow to reset mount_program

---

drivers/chown_unix.go

Where we ignored a pkg/system.ErrNotSupportedPlatform error from pkg/system.Lgetxattr(), also ignore ENOTSUP/EOPNOTSUPP, as we already do elsewhere.  Should fix https://github.com/containers/podman/issues/9687.

chown: ignore both pkg/system.EOPNOTSUPP and pkg/system.ErrNotSupportedPlatform

---

drivers/copy/copy_linux.go

os.ModeSocket refers to a UNIX socket, not a FIFO.
I've noticed the issue while working on https://github.com/containers/buildah/pull/3075

copy: create a unix socket with os.ModeSocket

---

drivers/overlay/overlay.go
tests/overlay-recreate.bats

Extend the overlay driver's recreateSymlinks() function to not give up at the first sign of trouble, but to keep on going until it can no
longer make progress, and add an integration test to exercise it.

overlay.recreateSymlinks: handle missing "link" files, add a test

---

storage.conf

If users do not set the storage driver in their storage.conf, tools that
use containers/storage will print a warning. Since we recommend that
users should use "overlay" driver by default, we should set the settings
in our default storage.conf. This ways distros that just grab the
storage.conf in the storage library will work without the warning.

Set default to overlay from storage.conf

---

go.mod
go.sum
idset.go
idset_test.go
store.go
userns.go
userns_test.go
vendor/github.com/google/go-intervals/LICENSE
vendor/github.com/google/go-intervals/intervalset/intervalset.go
vendor/github.com/google/go-intervals/intervalset/intervalset_immutable.go
vendor/modules.txt

This implements the algorithm proposed in
https://github.com/containers/storage/issues/852#issuecomment-798954173,
which is:
1. find available IDs from subuid/subgid file; by subtracting the used
IDs (from other containers) as well as additional IDs, we get the IDs
available to allocate;
2. target ID range is [0, requestedSize), subtract the additional IDs;
3. allocate IDs from range in step 1; the number to allocate is the
number of IDs in step 2;
4. generate a mapping from IDs in step 3 to the ones in step 2.
Closes: https://github.com/containers/storage/issues/852
Signed-off-by: Kan Li <likan@google.com>

Rework autons ID mapping generation.

---

drivers/copy/copy_linux.go
drivers/overlay/check.go
pkg/archive/archive.go
pkg/archive/archive_linux.go
pkg/archive/archive_linux_test.go
pkg/archive/changes_linux.go

unprivileged users cannot use the trusted.* xattrs.  Since for rootless we always mount overlay with userxattr, we can just check if
running in rootless mode and use user.* instead of trusted.*.
Closes: https://github.com/containers/podman/issues/9936

rootless overlay: use user.* instead of trusted.*

---

drivers/driver.go
drivers/overlay/overlay.go
layers.go
pkg/config/config.go
store.go
types/options.go

https://github.com/containers/podman/issues/4739
This enables podman to create containers using layers stored in a specified directory instead of pulling them from the registry. Leveraging this feature with remotely-mountable layers provided by stargz/zstd:chunked or CVMFS, podman can achieve lazy pulling.
That directory is named "additional layer store" (call ALS in this doc) and has the following structure.
```
<ALS root>/base64("key1=value1")/base64("key2=value2")/.../
`-- diff
`-- info
```
`diff` directory contains the extracted layer diff contents specified by the key-value pairs.
`info` file contains `*c/storage.Layer` struct that indicates the information of this layer contents (`*c/storage.Layer.ID`, `*c/storage.Layer.Parent` and `*c/storage.Layer.Created` can be empty as it'll be …

Support additional layer store (patch for containers/storage)

---

types/options.go

Currently in Podman if we reset the CONTAINERS_STORAGE_CONF path, we get
the graph driver options from the original config file as well as the
options from the override path. This PR resets the storageconf to the
initial state when called multiple times.

    ReloadConfigurationFile should Reset storage options

---

drivers/btrfs/btrfs.go

Before this change, cleanup of the btrfs driver (occuring on each driver
shutdown) resulted in disabling quotas. It was done with an assumption
that quotas can be enabled or disabled on a subvolume level, which is
not true - enabling or disabling quota is always done on a filesystem
level.
That was leading to disabling quota on btrfs filesystems on btrfs driver
shutdown.
This change fixes that behavior and removes misleading `subvol` prefix
from functions and methods which set up quota (on a filesystem level).
Ref: moby/moby#34593
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

btrfs: Do not disable quota on cleanup

---

pkg/unshare/unshare.go

add a function to check whether the current process has the
CAP_SYS_ADMIN capability in its effective capabilities set.

unshare: new function HasCapSysAdmin

---

drivers/overlay/overlay.go

Certain platforms might not have container_file_t defined, so we need to
check if the label is defined before attempting to use it.
Discussion is going on in: https://github.com/containers/podman/issues/9682

Validate selinux label before attempting to use it

---

store.go
tests/stores.bats

Fixes:  https://github.com/containers/podman/issues/9412

Allow users to tag images in read/only image stores

---

drivers/overlay/overlay.go

Most linux kernels do not support overlay mounts in rootless mode,
we should not be reporting this as an error, but drop it to debug
level.
Fixes: https://github.com/containers/podman/issues/10153

Log expected rootless overlay mount failures as debug level

---

types/options.go
types/options_test.go
types/utils.go

The current code was hanging for me, this makes sure the path is
expanded properly when it is read.
Fixes: https://github.com/containers/podman/issues/10181

Expand Variables on rootlessStoragePath

---

pkg/fileutils/fileutils_test.go

With Go 1.16 and later, `pkg/fileutils.NewPatternMatcher()` will flag patterns with bad syntax immediately.  With older compilers, it would have returned a matcher object which flagged syntax errors only when the matcher was actually used to check a path.  Update tests to accept either behavior.

TestMatch: handle cases where NewPatternMatcher catches syntax errors

---

drivers/devmapper/deviceset.go

When "docker load $image" and "docker rmi $image" commands are repeatedly executed in the background, the dockerd daemon process is killed. As a result, the DM device where the image resides may be unavailable. The image can be queried, but the container fails to be run. After function “devices.issueDiscard(info)” is executed and before function "devices.deleteTransaction(info, syncDelete)" is executed, at this point, dockerd daemon's withdrawal would result in dm device discarded. Howerver, the dm device is not deleted at the same time.
Signed-off-by: gaohuatao <gaohuatao@huawei.com>

Expand the scope of transaction in the process of deleting device

---

store.go

I thought the previos lock was a read/only lock, which is why I was
freeing and taking the read/write lock.  Since previous lock was
read/write, no reason for this code.

Remove unlock/lock caused by Incorrect assumption

---

drivers/driver.go
drivers/overlay/overlay.go
pkg/idtools/idtools.go
pkg/idtools/idtools_test.go
store.go

enable fuse-overlayfs shifting only when the specified mapping is contiguous.
Closes: https://github.com/containers/podman/issues/10272

store: allow shifting only with contiguous mappings

---

containers.go
images.go
layers.go
store.go

simplify the pattern if store.Modified() => store.Load() with a single function call store.ReloadIfChanged().
In addition to the code simplification, it solves a race condition that when only a RLock() is hold and that multiple goroutines could
run the sequence store.Modified() and store.Load().  In this case only one goroutine would see store.Modified( and run store.Load().
Other goroutines could access the old data while the goroutine that saw the change modifies the store data.
Closes: https://github.com/containers/storage/issues/880

store: replace Modified+Load with ReloadIfChanged

---

drivers/driver.go
drivers/overlay/overlay.go
errors.go
layers.go
pkg/chunked/compression.go
pkg/chunked/storage.go
pkg/chunked/zstdchunked_test.go
pkg/config/config.go
store.go
types/errors.go
types/options.go

a bunch of new APIs to enable zstd:chunked support in containers/image.
add a new custom variant of the zstd compression that permits to retrieve each file separately.
The idea is based on CRFS and its stargz format for having seekable and indexable tarballs.
One disadvantage of the stargz format is that a custom file is added to the tarball to store the layer metadata, and the metadata file is part of the image itself.  Clients that are not aware of the stargz format will propagate the metadata file inside of the containers.
The zstd compression supports embedding additional data as part of the stream that the zstd decompressor will ignore (skippable frame), so the issue above with CRFS can be solved directly within the zstd compression format.
Beside this minor advantage, zstd is much …

Enable zstd:chunked support in containers/image

---

drivers/driver.go
drivers/overlay/overlay.go
store.go

This is causing breakage in rootless podman run --usens=keep-id.
This reverts commit d5db906d7c856b52d2b4f09d9007e809c6d080bc.

Revert "store: allow shifting only with contiguous mappings"

---

pkg/archive/archive_linux.go
pkg/archive/archive_linux_test.go
pkg/archive/changes.go

See comment for the situation that arises, we've seen this with images
generated by very old dockers (and possibly others?).
I added a test for both syscall.ENOTDIR and unix.ENOTDIR even though they
*should be* aliases to be extra defensive (syscall.Stat_t and unix.Stat_t
were aliases for a while, but now they are not), but I can drop it if
necessary.
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>

archive/overlay: ignore failures from nested whiteouts

---

drivers/driver.go
drivers/overlay/overlay.go
store.go

reintroduce `store:  allow shifting only with contiguous mappings` after it was reverted.
enable fuse-overlayfs shifting only when the specified mapping is contiguous.
Closes: https://github.com/containers/podman/issues/10272
The difference with the first version:
```diff
diff --git a/store.go b/store.go
index 22f932698..759407c63 100644
--- a/store.go
+++ b/store.go
@@ -1114,7 +1114,7 @@ func (s *store) CreateImage(id string, names []string, layer, metadata string, o
func (s *store) imageTopLayerForMapping(image *Image, ristore ROImageStore, createMappedLayer bool, rlstore LayerStore, lstores []ROLayerStore, options types.IDMappingOptions) (*Layer, error) {
layerMatchesMappingOptions := func(layer *Layer, options …
```

reintroduce store: allow shifting only with contiguous mappings

---

drivers/driver.go
drivers/overlay/overlay.go
layers.go

Currently, layers aquired from additional layer store cannot be exported (e.g. `podman save`, `podman push`) as mentioned in https://github.com/containers/storage/pull/795#issuecomment-799057091.
```
Error: unable to save "ghcr.io/stargz-containers/postgres:13.1-esgz": error copying image to the remote destination: Error writing blob: error happened during read: Digest did not match, expected sha256:0167446b81cb115e90d668017ed409b449aee3a8fade44c7a96d36ebb0937ca5, got sha256:0a45da8cdff8388828644ad2052e91595733e558067b60b9f4bd290035964193
```
This is because the current additional layer store exposes only *extracted view* of layers. Tar is not reproducible so the runtime cannot reproduce the tar archive that has the same diff ID as the original.
This commit solves this issue by …

Enable to export layers from Additional Layer Store

---

drivers/overlay/overlay.go

NaiveDiff was enabled since the initial implementation to be
conservative.  There is not really any good reason for using it
instead of native diff.
Switch to native diff for better performance.
Closes: https://github.com/containers/storage/issues/917

overlay: enable native diff for fuse-overlayfs

---

layers.go

Return the error early instead of having big branch to improve
readability of the code.

delete_internal: return error early

---

containers.go
images.go
layers.go
store.go

use s.graphLock.Modified() instead of s.graphLock.TouchedSince().
TouchedSince() seems to fail in some cases when comparing the inode mtime with the current time.
Avoid such kind of problems in a critical code path as store.mount(), as we must be sure there is already a driver home mount present, otherwise it the next process may cover the container mount with the home mount.
Closes: https://github.com/containers/podman/issues/10454

store: fix graphLock reload

---

drivers/overlay/overlay.go

currently the kernel doesn't support both userxattr and metacopy=on
options.  When they are specified the mount fails with EINVAL.
Downgrade the warning message to debug level when running as
rootless.

overlay: make userxattr,metacopy=on debug message

---

docs/containers-storage.md
types/default_override_test.conf
types/utils.go
types/utils_test.go

Following the discussion from [here](https://github.com/containers/skopeo/issues/1272) 
The `DefaultStoreOptions` now checks if the environment variable `CONTAINERS_STORAGE_CONF` is set and uses that path 
for the configuration file. This is in line with how podman does it.
Please let me know your thoughts

Added support for CONTAINERS_STORAGE_CONF override

---

store.go

Fixes: https://github.com/containers/podman/issues/10535

canUseShifting can segfault

---

pkg/lockfile/lockfile_unix.go

drop a call to Seek and use the Pread and Pwrite syscalls instead that
already accept an offset.

lockfile: merge Seek+Read/Write into Pread/Pwrite

---

drivers/devmapper/deviceset.go

When cancel the deferred removal, if the device is already gone,
continue. According to the original logic, if the device does not exist,
an error is reported.
Signed-off-by: gaohuatao <gaohuatao@huawei.com>

Fix cancel deferred remove bug

---

drivers/overlay/check.go

make sure "userxattr" is specified, otherwise the "user.overlay."
xattrs are not treated specially and copied up as for the root case.
Closes: https://github.com/containers/storage/issues/947

overlay: fix check for rootless native diff

---

types/utils.go

Other parts of the code are using this directory, so we end up
with us creating an empty directory.
I don't see a reason why we would just use this directory only if
the init program is systemd?
Fixes: https://github.com/containers/podman/issues/10782

Use /run/user/UID in rootless mode if writable

---

types/options.go

Currently if a user puts a typo into a storage.conf
or puts the keys in the wrong section, then tools using
container/storage ignore them. This patch will print them
as warnings, so that the user has some idea what is going on.

Report bad entries in storage.conf to the user

---

pkg/chunked/storage_linux.go

`source` is the path to the layer that already contains the file that
is looked up.

chunked: fix the path used for layers dedup

---

pkg/lockfile/lockfile_unix.go
pkg/lockfile/lockfile_unix_test.go

If the lockfile directory gets removed but the container runtime is
still running with an open storage instance, then we can trigger a
runtime panic by:
1. Starting CRI-O
2. Removing the lockfile dir, e.g.:
`sudo rm -rf /var/lib/containers/storage/overlay-images`
3. Running `crictl images`
```
panic: error opening "/var/lib/containers/storage/overlay-images/images.lock": no such file or directory
goroutine 93 [running]:
github.com/containers/storage/pkg/lockfile.(*lockfile).lock(0xc0006b83c0, 0x2000000)
/go/src/github.com/cri-o/cri-o/vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go:107 +0x388
github.com/containers/storage/pkg/lockfile.(*lockfile).RLock(0xc0006b83c0)
/go/src/github.com/cri-o/cri-o/vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go:146 …
```

Fix runtime panic for opening lockfile if parent dir got removed

---

pkg/fileutils/fileutils.go
pkg/fileutils/fileutils_test.go

It is legal to use !./PATH and !/PATH in a .containerignore or
.dockerignore file.
Currently we fail to match on these patterns,  Removing the leadking
"/" and cleaning the path, fixes the problem.
Fixes: https://github.com/containers/buildah/issues/3272

Cleanup exclude exceptions path

---

pkg/lockfile/lockfile_unix.go
pkg/lockfile/lockfile_unix_test.go

Required for CRI-O 1.20 release branch.
Cherry-picked: 16de6d32b4f82fa6c4a5456450fb95de65e794a6
Refers to https://github.com/containers/storage/pull/957
---
If the lockfile directory gets removed but the container runtime is
still running with an open storage instance, then we can trigger a
runtime panic by:
1. Starting CRI-O
2. Removing the lockfile dir, e.g.:
`sudo rm -rf /var/lib/containers/storage/overlay-images`
3. Running `crictl images`
```
panic: error opening "/var/lib/containers/storage/overlay-images/images.lock": no such file or directory
goroutine 93 [running]:
github.com/containers/storage/pkg/lockfile.(*lockfile).lock(0xc0006b83c0, 0x2000000)
/go/src/github.com/cri-o/cri-o/vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go:107 +0x388 …
```

[1.24] Fix runtime panic for opening lockfile if parent dir got removed

---

pkg/lockfile/lockfile_unix.go
pkg/lockfile/lockfile_unix_test.go

Required for CRI-O 1.19 release branch.
Cherry-picked: 16de6d32b4f82fa6c4a5456450fb95de65e794a6
Refers to https://github.com/containers/storage/pull/957
---
If the lockfile directory gets removed but the container runtime is
still running with an open storage instance, then we can trigger a
runtime panic by:
1. Starting CRI-O
2. Removing the lockfile dir, e.g.:
`sudo rm -rf /var/lib/containers/storage/overlay-images`
3. Running `crictl images`
```
panic: error opening "/var/lib/containers/storage/overlay-images/images.lock": no such file or directory
goroutine 93 [running]:
github.com/containers/storage/pkg/lockfile.(*lockfile).lock(0xc0006b83c0, 0x2000000)
/go/src/github.com/cri-o/cri-o/vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go:107 +0x388 …
```

[1.20] Fix runtime panic for opening lockfile if parent dir got removed

---

types/utils.go

This feature was originally added for  #568, and I mistakenly removed
it.

Revert #952, we don't want to use /run/user on non systemd systems

---

drivers/overlay/overlay.go

When checking if we can use the kernel's overlay filesystem, verify that we can create whiteouts in the format the kernel expects (character devices with major and minor of 0), and if we fail to do that, don't try to use the kernel's overlay filesystem.  I think this is a "we can mount kernel overlay, but not everything else works" case that pops up among the gating test errors in https://bugzilla.redhat.com/show_bug.cgi?id=1955166.

overlay: check if we can mknod() kernel whiteout

---

docs/containers-storage.conf.5.md
drivers/overlay/overlay.go
drivers/quota/projectquota.go
drivers/quota/projectquota_unsupported.go
storage.conf

xfs quota for overlay also supports setting the maximum number of
inodes. OpenShift would like to be able to set this to control the
number of inodes added to an image or to a volume.

Add inode support to quota

---

drivers/overlay/overlay.go
tests/overlay-recreate.bats

Extend the overlay driver's recreateSymlinks() function to not give up
at the first sign of trouble, but to keep on going until it can no
longer make progress, and add an integration test to exercise it.
Signed-off-by: Nalin Dahyabhai <nalin@redhat.com>

[1.20-stable] overlay.recreateSymlinks: handle missing "link" files, add a test

---

pkg/chunked/compression.go
pkg/chunked/compressor/compressor.go
pkg/chunked/internal/compression.go
pkg/chunked/storage_linux.go
pkg/chunked/zstdchunked_test.go

`containers/image/pkg/compression` depends on that function, so it's highly undesirable for it to drag in all of containers/storage.
So, move it into a separate subpackage, along with its exclusive dependency tree.
Code that is called both from the new `pkg/chunked/compressor` and the original `pkg/chunked` has been moved into `pkg/chunked/internal` , so that we don't expose any new public API. That move was made purely mechanically without any concern for conceptual consistency, to minimize the size of the dependency (and not to spend time on that until the concept is proven to be useful).
Should not change behavior.

Split pkg/chunked.ZstdCompressor into a separate subpackage

---

drivers/overlay/overlay.go
tests/overlay-recreate.bats

Extend the overlay driver's recreateSymlinks() function to not give up
at the first sign of trouble, but to keep on going until it can no
longer make progress, and add an integration test to exercise it.
Signed-off-by: Nalin Dahyabhai <nalin@redhat.com>

[release-1.24] overlay.recreateSymlinks: handle missing "link" files, add a test

---

docs/containers-storage.conf.5.md
drivers/quota/projectquota.go

This patch fixes the handling of inodes and sizes, currently if
user sets indoes and sizes together, quota is only set on sizes.
Second problem with quota is that we have to have unigue projectids
for each directory. Originally container/storage only did quota on
rootfs, now we want to support it on volumes as well. We need to be
able to get unigue projectids for these two different parent
directories. The added function, attempts to maintain at least 10,000
unigue id's based on the inode of the parent directory. I know that this
is not perfect and we have a potential for overlay.  If you have a
better algorythm, I would love to use it.

Fix handling of quota on volumes

---

hack/libsubid_tag.sh
pkg/idtools/idtools_supported.go
pkg/idtools/idtools_unsupported.go

We now switch to a `libsubid` tag to increase the usability of the
library on systems not having the dependency in place.
Fixes https://github.com/containers/storage/issues/985

Invert libsubid tag

---

drivers/overlay/check_115.go
drivers/overlay/check_116.go
drivers/overlay/overlay.go

At startup, check if we see any aufs-style whiteout in any of our layers.  This can be expensive, so if we don't find any at startup, note that and bypass the check later until the system reboots.  If we do find some, leave a note that we needed to use a mount_program so that we don't have to bother with even this in the future.

overlay: check for aufs-style whiteout at startup

---

layers.go

When we're applying a diff, we compress the headers and stash them elsewhere so that we can use them to correctly reconstruct the layer if we need to extract its contents later.
By default, the compression uses a 1MB block, and up to GOMAXPROCS threads, which results in allocating GOMAXPROCS megabytes of memory up front.  That can be much more than we need, especially if the system has many, many cores.  Drop it down to 1 megabyte.

ApplyDiff: compress saved headers without concurrency

---

layers.go

Cherry-pick of https://github.com/containers/storage/pull/989

[1.24] ApplyDiff: compress saved headers without concurrency

---

layers.go

Cherry-pick of https://github.com/containers/storage/pull/989

[1.20] ApplyDiff: compress saved headers without concurrency

---

pkg/chunked/storage_linux.go

enable partial pulls only when it is explicitely configured in the
storage.conf file:
[storage.options]
pull_options = {enable_partial_images = "true"}
This is to prevent the experimental feature to leak into CRI-O.
The default value will change in future once the feature is stable.

chunked: allow to disable partial images feature

---

pkg/ioutils/readers.go

If the underlying `io.Reader` implements `WriteTo`, make the wrapped `ReadCloser` implement it as well.
This causes the values returned by `pkg/archive.DecompressStream` to implement `WriteTo` (for gzip and zstd, not bzip2 and xz), and that in turn eliminates a 32kB memory allocation when decompressing layers during pull.

Have NewReadCloserWrapper pass through io.WriterTo

---

layers.go
store.go

This allows callers of `Store.PutLayer` to provide the values if they have already computed them, so that `ApplyDiff` does not need to compute them again.
Intended to allow fixing the second half of https://github.com/containers/image/issues/1160 .
This could quite significantly reduce CPU usage.
(Note that it remains the case that during pulls, both `c/image/storage` and `ApplyDiff` decompress the stream; c/image/storage stores the compressed, not the decompressed, version in a temporary file. Nothing changes about that here - it's not obvious that changing it is worth it, and anyway it's a different concept for a different PR/discussion.)
See the individual commit messages for details.
<s>WARNING: Absolutely untested at this point.</s>

Add LayerOptions.OriginalDigest and LayerOptions.UncompressedDigest

---

pkg/chunked/storage_linux.go

if the option use_hard_links is set:
[storage.options]
pull_options = {use_hard_links = "true"}
then attempt to deduplicate files using hard links first.
the partial images feature is disabled by default, to enable it we need now:
pull_options = {enable_partial_images = "true"}

chunked: add new pull options use_hard_links and enable_partial_images

---

pkg/config/config.go

Fix error "Failed to decode the keys inodes" when using inodes in storage.conf
as documented https://github.com/containers/storage/blob/main/storage.conf#L73
https://github.com/containers/storage/blob/c9f1d016b9e7692e70b1338045af61c89fd63a0b/types/options.go#L280
Signed-off-by: Qi Wang <qiwan@redhat.com>

Add Inodes to OverlayOptionsConfig

---

pkg/chunked/storage_linux.go

before deduplicating with hard links make sure the two files share the same UID, GID, file mode and extended attributes.

chunked: restrict dedup with hard links

---

store.go

Make sure that the layer store is locked when loading the layers.
Reported-in: github.com/containers/podman/issues/11487
@nalind PTAL

(*Store)Layer(): fix race when loading layers

---

cmd/containers-storage/container.go
store.go
tests/idmaps.bats

do not pick the first available image if it was requested to not use
any mapping.
It causes a problem where an image is already present in the local
store with a mapping, then a container that doesn't specify any
mapping would end up to reuse that:
$ podman system reset -y
$ podman run --rm --uidmap 0:10000:1000 centos ls -ld /home
drwxr-xr-x. 2 root root 6 Nov  3  2020 /home
$ podman run --rm centos ls -ld /home
drwxr-xr-x. 2 10000 10000 6 Nov  3  2020 /home

store: don't ignore empty mappings for top layer

---

drivers/overlay/overlay.go

When quotas are enabled, partial pulls currently fail with an error like:
Error: committing the finished image: rename /var/lib/containers/storage/overlay/staging/012887766 /var/lib/containers/storage/overlay/b9b6a85242afa733a717aa45d7c0d80a444e224c96fb46677453aeef44caa0d6/diff: invalid cross-device link
Disable quotas when creating a read-only layer, which is also the
expectation from the existing code in Create() and from the
documentation:
**size**=""
Maximum size of a read/write layer.   This flag can be used to set quota on the size of a read/write layer of a container. (format: <number>[<unit>], where unit = b (bytes), k (kilobytes), m (megabytes), or g (gigabytes))

overlay: disable quota for images

---

pkg/chunked/storage_linux.go

if the option ostree_repos is set:
[storage.options]
pull_options = {enable_partial_images = "true", ostree_repos = "/foo:/bar"}
then attempt to deduplicate from the specified list of OSTree repositories.
In order to be usable, an OSTree repository must be configured to track
the checksum for its files payload (payload link), that is disabled by
default:
ostree config --repo=/path/to/repo set core.payload-link-threshold N
Where N is the minimum size for files to be tracked by their payload
and must be a nonzero value.

chunked: implement OSTree deduplication

---

pkg/lockfile/lockfile_unix.go

Users are setting up readonly shares and sometimes they forget, or do
not even know that they need to create the lockfile.
Even in the quay.io/podman/stable images Dockerfile, I have to manually
create these files.
Fixes: https://github.com/containers/storage/issues/1029

Create readonly locks if the lockfile does not exists

---

store.go

Drivers have the ability to support size and inodes quota, but
we don't allow these options to be passed down to the driver.
With this fix, Podman should be able to support --storage-opt size=
per container.
Helps Fix: https://github.com/containers/podman/issues/11016

Allow setting quota for individual containers

---

store.go

the NaiveDiff driver could cause a mount to happen without any locking
in place.
For such reason, treat the Diff operation similarly to Mount.
Closes: https://github.com/containers/storage/issues/1034
Alternative to https://github.com/containers/storage/pull/1033

store: lock graphLock during Diff

---

pkg/idtools/idtools_unix.go
pkg/idtools/idtools_unix_test.go

https://github.com/containers/storage/blob/73df15cb57ffd432da5f0e26ef6538441a00021a/pkg/idtools/idtools_unix.go#L49 will result an infinite loop when the path is relative.
Add validation to avoid it.
Signed-off-by: chenk008 <kongchen28@gmail.com>

Fix: relative path will result infinite loop

---

pkg/chunked/storage_linux.go

Using unix.AT_EMPTY_PATH requires CAP_DAC_READ_SEARCH.  Use an
equivalent variant that uses /proc/self/fd that can be used with
rootless.

chunked: fix another occurrence of linkat

---

drivers/overlay/overlay.go

If we've determined that we need to ignore a `metacopy=on` mount option, ignore it when it's a globally-set option, too.
Should fix RHBZ #1979966.

overlay.get: if we're ignoring metacopy=on, ignore it when it's global

---

pkg/chunked/storage_linux.go
pkg/idtools/idtools.go

since we now support reading additional IDs with libsubid, clarify
that the /etc/subuid and /etc/subgid files are honored only when
shadow-utils is configured to use them.
[NO TESTS NEEDED]

pkg/chunked, pkg/idtools: adjust error message

---

docs/containers-storage.conf.5.md
storage.conf

We have had cases where users assume that create a storage.conf file in
their home directory, will still inherit fields from the system
storage.conf files. Need to clear this up in the storage.conf file and
man page.
Fixes: https://github.com/containers/podman/issues/11778

[CI:DOCS] Clearup inheritance rules for storage.conf

---

pkg/idtools/idtools.go
pkg/idtools/idtools_test.go

drop a special case for RootPair that prevented the conversion of the
UID/GID when it was matching the root user in the container.
Closes: https://github.com/containers/storage/issues/1056

idtools: fix ToHost conversion

---

pkg/reexec/command_linux.go
pkg/reexec/command_unix.go
pkg/reexec/command_unsupported.go
pkg/reexec/command_windows.go
pkg/reexec/reexec.go

If we start preparing to reexec ourselves, but didn't call `Init()` earlier, `panic()`.  The alternative is that the child process we start
won't do the work we want it to do as a dedicated subprocess, failing in a way which could be difficult to troubleshoot.
Fixes https://github.com/containers/image/issues/1401 by making it easier to spot the bug.

reexec.Command(): panic if reexec.Init() wasn't called

---

drivers/graphtest/graphtest_unix.go
drivers/graphtest/testutil.go

… instead of open-coding loops, primarily to simplify.
In one case this is a speedup, in the other it’s a noticeable slowdown, a correctness improvement in theory at least.

Use math/rand.Rand.Read to generate slices of random data

---

pkg/reexec/reexec.go

In cases where one of our initializers needs to itself use reexec, they shouldn't panic().
Follow-up to #1058.

reexec: mark us as initialized when calling initializers

---

store.go
tests/idmaps.bats

When walking the list of layers in an image to decide which of them to remove as part of removing that image, we check that each candidate layer is a) not being used as the top layer for any other images, and b) that the only layer that lists a candidate layer as its parent layer is either the top layer of the image we're removing, or the previous layer that we decided should be removed.
When the image has multiple top layers because some of them are alternate top layers which use different ID mappings, that second check didn't account for those mapped layers as being layers that shouldn't prevent us from removing a candidate layer.
Fixes https://github.com/containers/podman/issues/12316.

store.DeleteImage: correctly account for mapped layers

---

drivers/overlay/overlay.go

use idtools.MkdirAllAndChownNew() instead of idtools.MkdirAllAs() to
create new directories, so it doesn't change ownership of existing
parent directories.
Closes: https://github.com/containers/storage/issues/1068

overlay: chown only newly created directories

---

drivers/overlay/overlay.go

Use the debug level whenn adding the metacopy options.  The default one
is warn which is causing regression.

overlay: silence metacopy warning

---

pkg/chunked/storage_linux.go

some improvements and fixes for issues I've found while playing with docker.io/gscrivano/zstd-chunked:fcos-rawhide and docker.io/gscrivano/zstd-chunked:fcos-latest.
More details in each commit.

chunked: various improvements

---

pkg/archive/archive.go
pkg/archive/archive_test.go
pkg/chunked/storage_linux.go

ignore the security.selinux xattr if it is present in the tarball header, since invalid labels cannot be set by unprivileged users and the `lsetxattr` syscall fails with EINVAL.
Closes: https://github.com/containers/storage/issues/1076

archive: ignore the security.selinux xattr

---

types/options.go

Currently DefaultConfigFile does not report back the storage.conf file
that is actually used if /etc/containers/storage.conf exists it should
be reported back to the user. This issue was seen with Podman.

Reset defaultConfigFile if defaultOverrideConfigFile exits.

---

types/options.go

While reloading from config files `graph` and `run` root could be set to
empty. We should fall back to default if they are empty.
Closes: https://github.com/containers/podman/issues/12467

options: fall back to default `graph` and `run` root for empty case

---

pkg/idtools/idtools_supported.go

the functions get_subuid_ranges and get_subgid_ranges were renamed
respectively to subid_get_uid_ranges and subid_get_gid_ranges in
libsubid version 4.

idtools: support libsubid 4

---

layers.go
tests/apply-junk.bats

Don't `ReadAll()` from a `Reader` to create a buffer and then create another `Reader` to read from that buffer.

layerStore.Diff(): don't add an unnecessary buffer

---

hack/libsubid_tag.sh
pkg/idtools/idtools_supported.go

libsubid changes its ABI in version 4.  Account for the different name
in the configure script.

build: fix libsubid test

---

store.go

Backport the fix for #1037 to
the release-1.36 branch so that it can then be backported to Podman's
v3.4.2-rhel branch for RHEL 8.5.0.2
Note: #1097 was completed to the 1.37 branch in error. Podman
v3.4.2-rhel is still on c/storage v1.36.  #1098 was submited to main
in error, hopefully the third time is the charm?
Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

Backport store: lock graphLock during to 1.36

---

pkg/idtools/idtools.go

While the IDMapping methods are preferable for most users, sometimes it
is necessary to map a single ID using a given mapping. In particular
this is needed for psgo to be able to map the user and group entries in
/proc/$pid/status using the user namespace of the target process.
See https://github.com/containers/psgo/pull/92.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

pkg: idtools: export RawTo{Container,Host}

---

store.go

if the container deletion fails with the simple os.RemoveAll(path),
then attempt again using system.EnsureRemoveAll(path).
The difference is that system.EnsureRemoveAll(path) tries to umount
eventual mounts that are keeping the directory busy.
It might help with: https://github.com/containers/podman/issues/11594

store: use system.EnsureRemoveAll to rm container

---

store.go

A common error when dealing with corrupted images is
> error locating item named "manifest" for image with ID "...": file does not exist
In many cases, the process writing to the containers storage has been
killed while pulling, building or committing an image.  The best thing
to do in this case is to remove the image as it is not usable.
Add a note to the error to consider removing the image to resolve the
issue to guide the users a bit more.
Fixes: containers/podman/issues/12854

ImageBigData: add note to error

---

Makefile
pkg/chunked/compression.go
pkg/pools/pools_test.go
store.go
types/options.go

Run codespell on code

---

pkg/archive/archive.go
pkg/archive/archive_test.go

the tar format doesn't support sockets so avoid adding them to the tar
stream.
Closes: https://github.com/containers/storage/issues/1115

archive: skip adding sockets to the tarball

---

pkg/archive/archive.go

when the option ForceMask is in place and the file UID, GID and mode
are written to a xattr skip the lchown syscall.
[NO TESTS NEEDED] as it requires a setup with NFS.

archive: skip lchown if force_mask is set

---

drivers/fsdiff.go
drivers/overlay/overlay.go

When mounting a layer, if the layer in question lives in an additional store, default to mounting it read-only, which is how we're treating the additional store's layers.  If we need to generate a diff using the naive diff implementation, this will prevent errors that would crop up if we tried and failed to mount the layer read-write, per #1121.
When mounting a parent layer in `drivers.NaiveDiffDriver.Changes()`, default to mounting it read-only, too, since a layer that is the basis for other layers shouldn't ever need to be mounted read-write anyway.

overlay.Get(): default to read-only for layers in additionalStores

---

pkg/config/config.go
types/options.go

switched os.Open to os.Create because os.Open() creates a file in read only mode
Signed-off-by: cdoern <cbdoer23@g.holycross.edu>

fix types.Save()

---

pkg/chunked/cache_linux.go

if the layer cache doesn't already exist, automatically create it from
the layer TOC.
commit 10697a05a27fa82db0552d83a4bee5a3703f974f introduced this
regression.

chunked: fix read layer cache

---

layers.go

RFC. This is absolutely untested, and I don’t really know what I’m doing WRT any pre-existing design about crash-resilience or the like.
Currently, we just tell the graph driver to start deleting data, and only after that succeeds, delete the layer metadata. If the graph driver’s deletion process is interrupted for any reason, that could result in a visible / “usable” layer that will nevertheless fail somewhere in the graph driver if on any actual use.
We have an `incompleteFlag` mechanism for layers that have been created but don’t have the content populated on pull; just reuse it for any other deletes.
(In `layerStore.load`, `deleteInternal` is called on layers with that flag already set; in that case we don’t update it again and don’t need to save the layer again, until cleanup …

RFC: Mark layers for deletion before actually doing so

---

drivers/overlay/overlay.go

… because it was very non-obvious to me, just reading the code of the loop.

Document that duplicate links are a possibility

---

drivers/chown.go
drivers/chown_unix.go
drivers/chown_windows.go

make sure the same inode is not chowned twice.  Track all the inodes that are chowned and skip the same inode if it is encountered multiple times.
Closes: https://github.com/containers/storage/issues/1143

drivers, chown: support chown of hard links

---

layers.go

`id` is known to be non-empty because we generate a random value earlier in the function, in that case.

Remove dead code

---

pkg/chunked/storage_linux.go
pkg/idtools/idtools.go

Based on a conversation on the Podman mailing list:
Mentioning podman-system-migrate in the error message may help users
resolve their issues faster.
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>
@giuseppe PTAL
It would be displayed for non-Podman clients as well but I think that's a fair trade off.

insufficient IDs errors: mention podman-system-migrate

---

drivers/overlay/overlay.go

When we need to shell out to a helper binary to be able to pass relative locations for directories listed in the mount options, whether or not the mount is meant to be writable isn't a factor.

overlay: mountFrom read-only mounts using relative paths

---

containers.go
errors.go
images.go
images_test.go
layers.go
store.go
utils.go

Adds `SetNameWithOptions` so operations which are invoke in parallel
manner can use it without destroying names from storage.
For instance
We are deleting names which were already written in store.
This creates faulty behavior when builds are invoked in parallel manner, as
this removes names for other builds.
To fix this behavior we must append to already written names and
override if needed. But this should be optional and not break public API
Following patch will be used by parallel operations at podman or buildah end, directly or indirectly.
PR replaces: https://github.com/containers/storage/pull/1152

race, storage:  add independent `AddNames` and `RemoveNames` for images,layers and containers

---

drivers/overlay/overlay.go

There's some code here that checks if we've overflown the amount of data that mount() can take but it's not quite right: with enough container layers and an unlucky choice for your `graphRoot` you could land on the page size _exactly_ and it would crash.
Fixes containers/storage#1159

overlay: Account for the trailing '\0' in mount() string.

---

pkg/unshare/unshare_linux.go

ExecRunnable is invoked by buildah and error from c/storage is logged to
stdout. This creates a drift between the between the behavior which is
generated by rootless and rootful buildah.
This corrects the behavior for rootless buildah so it has parity with
buildah invoked for root user.
This helps in issue being discussed here: https://github.com/containers/buildah/pull/3804#discussion_r820904895

ExecRunnable: prevent logging on stderr when its not expected
